package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppEmployeeReqJ222 generated by hbm2java
 */
@Entity
@Table(name="APP_EMPLOYEE_REQ_J222"
    ,schema="SHAMS"
)
public class AppEmployeeReqJ222  implements java.io.Serializable {


     private long reqSp;
     private AppReqTypeJ111 appReqTypeJ111;
     private PerEmploymentMasters perEmploymentMasters;
     private String employeeNo;
     private Date execDate;
     private Date reqDate;
     private String reqDateTime;
     private String doneDateTime;
     private Date doneDate;
     private String chkView;
     private String rmrk;
     private Short dayNo;
     private BigDecimal val65;
     private BigDecimal val70;
     private String locCode;
     private Byte statusCode;
     private String tafkit;
     private Short bankCode;
     private long sarfCode;
     private BigDecimal val30;
     private String fiscalDegreeCode;
     private String locationCode;
     private Short statusGroup;
     private String jobCode;
     private Set<AppEmployeeReqJ444> appEmployeeReqJ444s = new HashSet<AppEmployeeReqJ444>(0);
     private Set<AppEmployeeReqJ2221> appEmployeeReqJ2221s = new HashSet<AppEmployeeReqJ2221>(0);

    public AppEmployeeReqJ222() {
    }

	
    public AppEmployeeReqJ222(long reqSp, AppReqTypeJ111 appReqTypeJ111, String employeeNo) {
        this.reqSp = reqSp;
        this.appReqTypeJ111 = appReqTypeJ111;
        this.employeeNo = employeeNo;
    }
    public AppEmployeeReqJ222(long reqSp, AppReqTypeJ111 appReqTypeJ111, PerEmploymentMasters perEmploymentMasters, String employeeNo, Date execDate, Date reqDate, String reqDateTime, String doneDateTime, Date doneDate, String chkView, String rmrk, Short dayNo, BigDecimal val65, BigDecimal val70, String locCode, Byte statusCode, String tafkit, Short bankCode, BigDecimal val30, String fiscalDegreeCode, String locationCode, Short statusGroup, String jobCode, Set<AppEmployeeReqJ444> appEmployeeReqJ444s, Set<AppEmployeeReqJ2221> appEmployeeReqJ2221s) {
       this.reqSp = reqSp;
       this.appReqTypeJ111 = appReqTypeJ111;
       this.perEmploymentMasters = perEmploymentMasters;
       this.employeeNo = employeeNo;
       this.execDate = execDate;
       this.reqDate = reqDate;
       this.reqDateTime = reqDateTime;
       this.doneDateTime = doneDateTime;
       this.doneDate = doneDate;
       this.chkView = chkView;
       this.rmrk = rmrk;
       this.dayNo = dayNo;
       this.val65 = val65;
       this.val70 = val70;
       this.locCode = locCode;
       this.statusCode = statusCode;
       this.tafkit = tafkit;
       this.bankCode = bankCode;
       this.val30 = val30;
       this.fiscalDegreeCode = fiscalDegreeCode;
       this.locationCode = locationCode;
       this.statusGroup = statusGroup;
       this.jobCode = jobCode;
       this.appEmployeeReqJ444s = appEmployeeReqJ444s;
       this.appEmployeeReqJ2221s = appEmployeeReqJ2221s;
    }
   
     @Id 

    
    @Column(name="REQ_SP", unique=true, nullable=false, precision=16, scale=0)
    public long getReqSp() {
        return this.reqSp;
    }
    
    public void setReqSp(long reqSp) {
        this.reqSp = reqSp;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="APP_REQ_SEQ", nullable=false)
    public AppReqTypeJ111 getAppReqTypeJ111() {
        return this.appReqTypeJ111;
    }
    
    public void setAppReqTypeJ111(AppReqTypeJ111 appReqTypeJ111) {
        this.appReqTypeJ111 = appReqTypeJ111;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID")
    public PerEmploymentMasters getPerEmploymentMasters() {
        return this.perEmploymentMasters;
    }
    
    public void setPerEmploymentMasters(PerEmploymentMasters perEmploymentMasters) {
        this.perEmploymentMasters = perEmploymentMasters;
    }

    
    @Column(name="EMPLOYEE_NO", nullable=false, length=10)
    public String getEmployeeNo() {
        return this.employeeNo;
    }
    
    public void setEmployeeNo(String employeeNo) {
        this.employeeNo = employeeNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXEC_DATE", length=7)
    public Date getExecDate() {
        return this.execDate;
    }
    
    public void setExecDate(Date execDate) {
        this.execDate = execDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="REQ_DATE", length=7)
    public Date getReqDate() {
        return this.reqDate;
    }
    
    public void setReqDate(Date reqDate) {
        this.reqDate = reqDate;
    }

    
    @Column(name="REQ_DATE_TIME", length=40)
    public String getReqDateTime() {
        return this.reqDateTime;
    }
    
    public void setReqDateTime(String reqDateTime) {
        this.reqDateTime = reqDateTime;
    }

    
    @Column(name="DONE_DATE_TIME", length=40)
    public String getDoneDateTime() {
        return this.doneDateTime;
    }
    
    public void setDoneDateTime(String doneDateTime) {
        this.doneDateTime = doneDateTime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DONE_DATE", length=7)
    public Date getDoneDate() {
        return this.doneDate;
    }
    
    public void setDoneDate(Date doneDate) {
        this.doneDate = doneDate;
    }

    
    @Column(name="CHK_VIEW", length=2)
    public String getChkView() {
        return this.chkView;
    }
    
    public void setChkView(String chkView) {
        this.chkView = chkView;
    }

    
    @Column(name="RMRK", length=200)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }

    
    @Column(name="DAY_NO", precision=3, scale=0)
    public Short getDayNo() {
        return this.dayNo;
    }
    
    public void setDayNo(Short dayNo) {
        this.dayNo = dayNo;
    }

    
    @Column(name="VAL_65", precision=11)
    public BigDecimal getVal65() {
        return this.val65;
    }
    
    public void setVal65(BigDecimal val65) {
        this.val65 = val65;
    }

    
    @Column(name="VAL_70", precision=11)
    public BigDecimal getVal70() {
        return this.val70;
    }
    
    public void setVal70(BigDecimal val70) {
        this.val70 = val70;
    }

    
    @Column(name="LOC_CODE", length=3)
    public String getLocCode() {
        return this.locCode;
    }
    
    public void setLocCode(String locCode) {
        this.locCode = locCode;
    }

    
    @Column(name="STATUS_CODE", precision=2, scale=0)
    public Byte getStatusCode() {
        return this.statusCode;
    }
    
    public void setStatusCode(Byte statusCode) {
        this.statusCode = statusCode;
    }

    
    @Column(name="TAFKIT", length=200)
    public String getTafkit() {
        return this.tafkit;
    }
    
    public void setTafkit(String tafkit) {
        this.tafkit = tafkit;
    }

    
    @Column(name="BANK_CODE", precision=4, scale=0)
    public Short getBankCode() {
        return this.bankCode;
    }
    
    public void setBankCode(Short bankCode) {
        this.bankCode = bankCode;
    }

    
    @Column(name="SARF_CODE", precision=10, scale=0)
    public long getSarfCode() {
        return this.sarfCode;
    }
    
    public void setSarfCode(long sarfCode) {
        this.sarfCode = sarfCode;
    }

    
    @Column(name="VAL_30", precision=11)
    public BigDecimal getVal30() {
        return this.val30;
    }
    
    public void setVal30(BigDecimal val30) {
        this.val30 = val30;
    }

    
    @Column(name="FISCAL_DEGREE_CODE", length=3)
    public String getFiscalDegreeCode() {
        return this.fiscalDegreeCode;
    }
    
    public void setFiscalDegreeCode(String fiscalDegreeCode) {
        this.fiscalDegreeCode = fiscalDegreeCode;
    }

    
    @Column(name="LOCATION_CODE", length=3)
    public String getLocationCode() {
        return this.locationCode;
    }
    
    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode;
    }

    
    @Column(name="STATUS_GROUP", precision=4, scale=0)
    public Short getStatusGroup() {
        return this.statusGroup;
    }
    
    public void setStatusGroup(Short statusGroup) {
        this.statusGroup = statusGroup;
    }

    
    @Column(name="JOB_CODE", length=5)
    public String getJobCode() {
        return this.jobCode;
    }
    
    public void setJobCode(String jobCode) {
        this.jobCode = jobCode;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="appEmployeeReqJ222")
    public Set<AppEmployeeReqJ444> getAppEmployeeReqJ444s() {
        return this.appEmployeeReqJ444s;
    }
    
    public void setAppEmployeeReqJ444s(Set<AppEmployeeReqJ444> appEmployeeReqJ444s) {
        this.appEmployeeReqJ444s = appEmployeeReqJ444s;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="appEmployeeReqJ222")
    public Set<AppEmployeeReqJ2221> getAppEmployeeReqJ2221s() {
        return this.appEmployeeReqJ2221s;
    }
    
    public void setAppEmployeeReqJ2221s(Set<AppEmployeeReqJ2221> appEmployeeReqJ2221s) {
        this.appEmployeeReqJ2221s = appEmployeeReqJ2221s;
    }




}


