package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AppEmployeeReqJ2221 generated by hbm2java
 */
@Entity
@Table(name="APP_EMPLOYEE_REQ_J2221"
    ,schema="SHAMS"
)
public class AppEmployeeReqJ2221  implements java.io.Serializable {


     private AppEmployeeReqJ2221Id id;
     private PayBandCode payBandCode;
     private String employeeNo;
     private BigDecimal val;
     private BigDecimal creditBalance;
     private String chkIns;

    public AppEmployeeReqJ2221() {
    }

	
    public AppEmployeeReqJ2221(AppEmployeeReqJ2221Id id, PayBandCode payBandCode, BigDecimal val) {
        this.id = id;
        this.payBandCode = payBandCode;
        this.val = val;
    }
    public AppEmployeeReqJ2221(AppEmployeeReqJ2221Id id, PayBandCode payBandCode, String employeeNo, BigDecimal val, BigDecimal creditBalance, String chkIns) {
       this.id = id;
       this.payBandCode = payBandCode;
       this.employeeNo = employeeNo;
       this.val = val;
       this.creditBalance = creditBalance;
       this.chkIns = chkIns;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="bandCode", column=@Column(name="BAND_CODE", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="bandType", column=@Column(name="BAND_TYPE", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="reqSp", column=@Column(name="REQ_SP", nullable=false, precision=16, scale=0) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, length=10) ) } )
    public AppEmployeeReqJ2221Id getId() {
        return this.id;
    }
    
    public void setId(AppEmployeeReqJ2221Id id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="BAND_TYPE", referencedColumnName="BAND_TYPE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="BAND_CODE", referencedColumnName="BAND_CODE", nullable=false, insertable=false, updatable=false) } )
    public PayBandCode getPayBandCode() {
        return this.payBandCode;
    }
    
    public void setPayBandCode(PayBandCode payBandCode) {
        this.payBandCode = payBandCode;
    }

    
    @Column(name="EMPLOYEE_NO", length=10)
    public String getEmployeeNo() {
        return this.employeeNo;
    }
    
    public void setEmployeeNo(String employeeNo) {
        this.employeeNo = employeeNo;
    }

    
    @Column(name="VAL", nullable=false, precision=11)
    public BigDecimal getVal() {
        return this.val;
    }
    
    public void setVal(BigDecimal val) {
        this.val = val;
    }

    
    @Column(name="CREDIT_BALANCE", precision=11)
    public BigDecimal getCreditBalance() {
        return this.creditBalance;
    }
    
    public void setCreditBalance(BigDecimal creditBalance) {
        this.creditBalance = creditBalance;
    }

    
    @Column(name="CHK_INS", length=1)
    public String getChkIns() {
        return this.chkIns;
    }
    
    public void setChkIns(String chkIns) {
        this.chkIns = chkIns;
    }




}


