package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AppEmployeeReqJ444Id generated by hbm2java
 */
@Embeddable
public class AppEmployeeReqJ444Id  implements java.io.Serializable {


     private long reqSp;
     private String employeeId;

    public AppEmployeeReqJ444Id() {
    }

    public AppEmployeeReqJ444Id(long reqSp, String employeeId) {
       this.reqSp = reqSp;
       this.employeeId = employeeId;
    }
   


    @Column(name="REQ_SP", nullable=false, precision=16, scale=0)
    public long getReqSp() {
        return this.reqSp;
    }
    
    public void setReqSp(long reqSp) {
        this.reqSp = reqSp;
    }


    @Column(name="EMPLOYEE_ID", nullable=false, length=10)
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AppEmployeeReqJ444Id) ) return false;
		 AppEmployeeReqJ444Id castOther = ( AppEmployeeReqJ444Id ) other; 
         
		 return (this.getReqSp()==castOther.getReqSp())
 && ( (this.getEmployeeId()==castOther.getEmployeeId()) || ( this.getEmployeeId()!=null && castOther.getEmployeeId()!=null && this.getEmployeeId().equals(castOther.getEmployeeId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getReqSp();
         result = 37 * result + ( getEmployeeId() == null ? 0 : this.getEmployeeId().hashCode() );
         return result;
   }   


}


