package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AppEmployeeReqJ2221Id generated by hbm2java
 */
@Embeddable
public class AppEmployeeReqJ2221Id  implements java.io.Serializable {


     private long reqSp;
     private short bandCode;
     private byte bandType;

    public AppEmployeeReqJ2221Id() {
    }

    public AppEmployeeReqJ2221Id(long reqSp, short bandCode, byte bandType) {
       this.reqSp = reqSp;
       this.bandCode = bandCode;
       this.bandType = bandType;
    }
   


    @Column(name="REQ_SP", nullable=false, precision=16, scale=0)
    public long getReqSp() {
        return this.reqSp;
    }
    
    public void setReqSp(long reqSp) {
        this.reqSp = reqSp;
    }


    @Column(name="BAND_CODE", nullable=false, precision=4, scale=0)
    public short getBandCode() {
        return this.bandCode;
    }
    
    public void setBandCode(short bandCode) {
        this.bandCode = bandCode;
    }


    @Column(name="BAND_TYPE", nullable=false, precision=2, scale=0)
    public byte getBandType() {
        return this.bandType;
    }
    
    public void setBandType(byte bandType) {
        this.bandType = bandType;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AppEmployeeReqJ2221Id) ) return false;
		 AppEmployeeReqJ2221Id castOther = ( AppEmployeeReqJ2221Id ) other; 
         
		 return (this.getReqSp()==castOther.getReqSp())
 && (this.getBandCode()==castOther.getBandCode())
 && (this.getBandType()==castOther.getBandType());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getReqSp();
         result = 37 * result + this.getBandCode();
         result = 37 * result + this.getBandType();
         return result;
   }   


}


