package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppEmployeeReqJ222 generated by hbm2java
 */
@Entity
@Table(name="APP_EMPLOYEE_REQ_J222"
    ,schema="SHAMS"
)
public class AppEmployeeReqJ222  implements java.io.Serializable {


     private long reqSp;
     private PerEmploymentMasters perEmploymentMasters;
     private AppReqTypeJ111 appReqTypeJ111;
     private Date reqDate;
     private String reqDateTime;
     private String employeeNo;
     private Date doneDate;
     private Date execDate;
     private String doneDateTime;
     private String chkView;
     private String chkOver;
     private String rmrk;
     private Set<AppEmployeeReqJ444> appEmployeeReqJ444s = new HashSet<AppEmployeeReqJ444>(0);

    public AppEmployeeReqJ222() {
    }

	
    public AppEmployeeReqJ222(long reqSp, AppReqTypeJ111 appReqTypeJ111, String employeeNo) {
        this.reqSp = reqSp;
        this.appReqTypeJ111 = appReqTypeJ111;
        this.employeeNo = employeeNo;
    }
    public AppEmployeeReqJ222(long reqSp, PerEmploymentMasters perEmploymentMasters, AppReqTypeJ111 appReqTypeJ111, Date reqDate, String reqDateTime, String employeeNo, Date doneDate, Date execDate, String doneDateTime, String chkView, String chkOver, String rmrk, Set<AppEmployeeReqJ444> appEmployeeReqJ444s) {
       this.reqSp = reqSp;
       this.perEmploymentMasters = perEmploymentMasters;
       this.appReqTypeJ111 = appReqTypeJ111;
       this.reqDate = reqDate;
       this.reqDateTime = reqDateTime;
       this.employeeNo = employeeNo;
       this.doneDate = doneDate;
       this.execDate = execDate;
       this.doneDateTime = doneDateTime;
       this.chkView = chkView;
       this.chkOver = chkOver;
       this.rmrk = rmrk;
       this.appEmployeeReqJ444s = appEmployeeReqJ444s;
    }
   
     @Id 

    
    @Column(name="REQ_SP", unique=true, nullable=false, precision=16, scale=0)
    public long getReqSp() {
        return this.reqSp;
    }
    
    public void setReqSp(long reqSp) {
        this.reqSp = reqSp;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID")
    public PerEmploymentMasters getPerEmploymentMasters() {
        return this.perEmploymentMasters;
    }
    
    public void setPerEmploymentMasters(PerEmploymentMasters perEmploymentMasters) {
        this.perEmploymentMasters = perEmploymentMasters;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="APP_REQ_SEQ", nullable=false)
    public AppReqTypeJ111 getAppReqTypeJ111() {
        return this.appReqTypeJ111;
    }
    
    public void setAppReqTypeJ111(AppReqTypeJ111 appReqTypeJ111) {
        this.appReqTypeJ111 = appReqTypeJ111;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="REQ_DATE", length=7)
    public Date getReqDate() {
        return this.reqDate;
    }
    
    public void setReqDate(Date reqDate) {
        this.reqDate = reqDate;
    }

    
    @Column(name="REQ_DATE_TIME", length=40)
    public String getReqDateTime() {
        return this.reqDateTime;
    }
    
    public void setReqDateTime(String reqDateTime) {
        this.reqDateTime = reqDateTime;
    }

    
    @Column(name="EMPLOYEE_NO", nullable=false, length=10)
    public String getEmployeeNo() {
        return this.employeeNo;
    }
    
    public void setEmployeeNo(String employeeNo) {
        this.employeeNo = employeeNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DONE_DATE", length=7)
    public Date getDoneDate() {
        return this.doneDate;
    }
    
    public void setDoneDate(Date doneDate) {
        this.doneDate = doneDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXEC_DATE", length=7)
    public Date getExecDate() {
        return this.execDate;
    }
    
    public void setExecDate(Date execDate) {
        this.execDate = execDate;
    }

    
    @Column(name="DONE_DATE_TIME", length=40)
    public String getDoneDateTime() {
        return this.doneDateTime;
    }
    
    public void setDoneDateTime(String doneDateTime) {
        this.doneDateTime = doneDateTime;
    }

    
    @Column(name="CHK_VIEW", length=2)
    public String getChkView() {
        return this.chkView;
    }
    
    public void setChkView(String chkView) {
        this.chkView = chkView;
    }

    
    @Column(name="CHK_OVER", length=2)
    public String getChkOver() {
        return this.chkOver;
    }
    
    public void setChkOver(String chkOver) {
        this.chkOver = chkOver;
    }

    
    @Column(name="RMRK", length=200)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="appEmployeeReqJ222")
    public Set<AppEmployeeReqJ444> getAppEmployeeReqJ444s() {
        return this.appEmployeeReqJ444s;
    }
    
    public void setAppEmployeeReqJ444s(Set<AppEmployeeReqJ444> appEmployeeReqJ444s) {
        this.appEmployeeReqJ444s = appEmployeeReqJ444s;
    }




}


