package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AppReqTypeJ111 generated by hbm2java
 */
@Entity
@Table(name="APP_REQ_TYPE_J111"
    ,schema="SHAMS"
)
public class AppReqTypeJ111  implements java.io.Serializable {


     private int appReqSeq;
     private AppName appName;
     private String appReqName;
     private Set<AppEmployeeReqJ222> appEmployeeReqJ222s = new HashSet<AppEmployeeReqJ222>(0);

    public AppReqTypeJ111() {
    }

	
    public AppReqTypeJ111(int appReqSeq) {
        this.appReqSeq = appReqSeq;
    }
    public AppReqTypeJ111(int appReqSeq, AppName appName, String appReqName, Set<AppEmployeeReqJ222> appEmployeeReqJ222s) {
       this.appReqSeq = appReqSeq;
       this.appName = appName;
       this.appReqName = appReqName;
       this.appEmployeeReqJ222s = appEmployeeReqJ222s;
    }
   
     @Id 

    
    @Column(name="APP_REQ_SEQ", unique=true, nullable=false, precision=9, scale=0)
    public int getAppReqSeq() {
        return this.appReqSeq;
    }
    
    public void setAppReqSeq(int appReqSeq) {
        this.appReqSeq = appReqSeq;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="APPLICATION_ID")
    public AppName getAppName() {
        return this.appName;
    }
    
    public void setAppName(AppName appName) {
        this.appName = appName;
    }

    
    @Column(name="APP_REQ_NAME", length=100)
    public String getAppReqName() {
        return this.appReqName;
    }
    
    public void setAppReqName(String appReqName) {
        this.appReqName = appReqName;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="appReqTypeJ111")
    public Set<AppEmployeeReqJ222> getAppEmployeeReqJ222s() {
        return this.appEmployeeReqJ222s;
    }
    
    public void setAppEmployeeReqJ222s(Set<AppEmployeeReqJ222> appEmployeeReqJ222s) {
        this.appEmployeeReqJ222s = appEmployeeReqJ222s;
    }




}


