package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AppSubTabAuthType generated by hbm2java
 */
@Entity
@Table(name="APP_SUB_TAB_AUTH_TYPE"
    ,schema="SHAMS"
    , uniqueConstraints = @UniqueConstraint(columnNames="AUTH_TYPE_ID") 
)
public class AppSubTabAuthType  implements java.io.Serializable {


     private AppSubTabAuthTypeId id;

    public AppSubTabAuthType() {
    }

    public AppSubTabAuthType(AppSubTabAuthTypeId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="authTypeId", column=@Column(name="AUTH_TYPE_ID", unique=true, nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="authTypeName", column=@Column(name="AUTH_TYPE_NAME", nullable=false, length=30) ) } )
    public AppSubTabAuthTypeId getId() {
        return this.id;
    }
    
    public void setId(AppSubTabAuthTypeId id) {
        this.id = id;
    }




}


