package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AppSubElem generated by hbm2java
 */
@Entity
@Table(name="APP_SUB_ELEM"
    ,schema="SHAMS"
    , uniqueConstraints = @UniqueConstraint(columnNames={"APPLICATION_ID", "TAB_ID", "SUB_TAB_ID", "ELEMENT_ID"}) 
)
public class AppSubElem  implements java.io.Serializable {


     private AppSubElemId id;

    public AppSubElem() {
    }

    public AppSubElem(AppSubElemId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="applicationId", column=@Column(name="APPLICATION_ID", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="tabId", column=@Column(name="TAB_ID", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="subTabId", column=@Column(name="SUB_TAB_ID", nullable=false, precision=8, scale=0) ), 
        @AttributeOverride(name="elementId", column=@Column(name="ELEMENT_ID", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="elementName", column=@Column(name="ELEMENT_NAME", nullable=false, length=20) ), 
        @AttributeOverride(name="elementType", column=@Column(name="ELEMENT_TYPE", length=10) ) } )
    public AppSubElemId getId() {
        return this.id;
    }
    
    public void setId(AppSubElemId id) {
        this.id = id;
    }




}


