package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AppSubElemSpecAuth generated by hbm2java
 */
@Entity
@Table(name="APP_SUB_ELEM_SPEC_AUTH"
    ,schema="SHAMS"
    , uniqueConstraints = @UniqueConstraint(columnNames={"APPLICATION_ID", "TAB_ID", "SUB_TAB_ID", "ELEMENT_ID", "EMPLOYEE_ID"}) 
)
public class AppSubElemSpecAuth  implements java.io.Serializable {


     private AppSubElemSpecAuthId id;
     private PerEmploymentMasters perEmploymentMastersByEmployeeId;
     private PerEmploymentMasters perEmploymentMastersByEmployeeIdAction;

    public AppSubElemSpecAuth() {
    }

	
    public AppSubElemSpecAuth(AppSubElemSpecAuthId id, PerEmploymentMasters perEmploymentMastersByEmployeeId) {
        this.id = id;
        this.perEmploymentMastersByEmployeeId = perEmploymentMastersByEmployeeId;
    }
    public AppSubElemSpecAuth(AppSubElemSpecAuthId id, PerEmploymentMasters perEmploymentMastersByEmployeeId, PerEmploymentMasters perEmploymentMastersByEmployeeIdAction) {
       this.id = id;
       this.perEmploymentMastersByEmployeeId = perEmploymentMastersByEmployeeId;
       this.perEmploymentMastersByEmployeeIdAction = perEmploymentMastersByEmployeeIdAction;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="applicationId", column=@Column(name="APPLICATION_ID", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="tabId", column=@Column(name="TAB_ID", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="subTabId", column=@Column(name="SUB_TAB_ID", nullable=false, precision=8, scale=0) ), 
        @AttributeOverride(name="elementId", column=@Column(name="ELEMENT_ID", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, length=10) ), 
        @AttributeOverride(name="employeeIdAction", column=@Column(name="EMPLOYEE_ID_ACTION", length=10) ), 
        @AttributeOverride(name="actionDate", column=@Column(name="ACTION_DATE", length=7) ), 
        @AttributeOverride(name="actionDateDetails", column=@Column(name="ACTION_DATE_DETAILS", length=25) ), 
        @AttributeOverride(name="primaryAuthPass", column=@Column(name="PRIMARY_AUTH_PASS", precision=2, scale=0) ) } )
    public AppSubElemSpecAuthId getId() {
        return this.id;
    }
    
    public void setId(AppSubElemSpecAuthId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false)
    public PerEmploymentMasters getPerEmploymentMastersByEmployeeId() {
        return this.perEmploymentMastersByEmployeeId;
    }
    
    public void setPerEmploymentMastersByEmployeeId(PerEmploymentMasters perEmploymentMastersByEmployeeId) {
        this.perEmploymentMastersByEmployeeId = perEmploymentMastersByEmployeeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMPLOYEE_ID_ACTION", insertable=false, updatable=false)
    public PerEmploymentMasters getPerEmploymentMastersByEmployeeIdAction() {
        return this.perEmploymentMastersByEmployeeIdAction;
    }
    
    public void setPerEmploymentMastersByEmployeeIdAction(PerEmploymentMasters perEmploymentMastersByEmployeeIdAction) {
        this.perEmploymentMastersByEmployeeIdAction = perEmploymentMastersByEmployeeIdAction;
    }




}


