package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AppSubTab generated by hbm2java
 */
@Entity
@Table(name="APP_SUB_TAB"
    ,schema="SHAMS"
    , uniqueConstraints = @UniqueConstraint(columnNames={"APPLICATION_ID", "TAB_ID", "SUB_TAB_ID"}) 
)
public class AppSubTab  implements java.io.Serializable {


     private AppSubTabId id;

    public AppSubTab() {
    }

    public AppSubTab(AppSubTabId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="applicationId", column=@Column(name="APPLICATION_ID", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="tabId", column=@Column(name="TAB_ID", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="subTabId", column=@Column(name="SUB_TAB_ID", nullable=false, precision=8, scale=0) ), 
        @AttributeOverride(name="subTabName", column=@Column(name="SUB_TAB_NAME", nullable=false, length=100) ), 
        @AttributeOverride(name="subTabAccessservlet", column=@Column(name="SUB_TAB_ACCESSSERVLET", nullable=false, length=100) ), 
        @AttributeOverride(name="availableToUserControl", column=@Column(name="AVAILABLE_TO_USER_CONTROL", length=10) ), 
        @AttributeOverride(name="subTabIndex", column=@Column(name="SUB_TAB_INDEX", precision=8, scale=0) ), 
        @AttributeOverride(name="authTypeId", column=@Column(name="AUTH_TYPE_ID", precision=3, scale=0) ) } )
    public AppSubTabId getId() {
        return this.id;
    }
    
    public void setId(AppSubTabId id) {
        this.id = id;
    }




}


