package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AppSubElem generated by hbm2java
 */
@Entity
@Table(name="APP_SUB_ELEM"
    ,schema="SHAMS"
)
public class AppSubElem  implements java.io.Serializable {


     private AppSubElemId id;
     private AppSubTab appSubTab;
     private String elementName;
     private String elementType;
     private Set<AppSubElemSpecAuth> appSubElemSpecAuths = new HashSet<AppSubElemSpecAuth>(0);

    public AppSubElem() {
    }

	
    public AppSubElem(AppSubElemId id, AppSubTab appSubTab, String elementName) {
        this.id = id;
        this.appSubTab = appSubTab;
        this.elementName = elementName;
    }
    public AppSubElem(AppSubElemId id, AppSubTab appSubTab, String elementName, String elementType, Set<AppSubElemSpecAuth> appSubElemSpecAuths) {
       this.id = id;
       this.appSubTab = appSubTab;
       this.elementName = elementName;
       this.elementType = elementType;
       this.appSubElemSpecAuths = appSubElemSpecAuths;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="applicationId", column=@Column(name="APPLICATION_ID", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="tabId", column=@Column(name="TAB_ID", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="subTabId", column=@Column(name="SUB_TAB_ID", nullable=false, precision=8, scale=0) ), 
        @AttributeOverride(name="elementId", column=@Column(name="ELEMENT_ID", nullable=false, precision=5, scale=0) ) } )
    public AppSubElemId getId() {
        return this.id;
    }
    
    public void setId(AppSubElemId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="APPLICATION_ID", referencedColumnName="APPLICATION_ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="TAB_ID", referencedColumnName="TAB_ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="SUB_TAB_ID", referencedColumnName="SUB_TAB_ID", nullable=false, insertable=false, updatable=false) } )
    public AppSubTab getAppSubTab() {
        return this.appSubTab;
    }
    
    public void setAppSubTab(AppSubTab appSubTab) {
        this.appSubTab = appSubTab;
    }

    
    @Column(name="ELEMENT_NAME", nullable=false, length=20)
    public String getElementName() {
        return this.elementName;
    }
    
    public void setElementName(String elementName) {
        this.elementName = elementName;
    }

    
    @Column(name="ELEMENT_TYPE", length=10)
    public String getElementType() {
        return this.elementType;
    }
    
    public void setElementType(String elementType) {
        this.elementType = elementType;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="appSubElem")
    public Set<AppSubElemSpecAuth> getAppSubElemSpecAuths() {
        return this.appSubElemSpecAuths;
    }
    
    public void setAppSubElemSpecAuths(Set<AppSubElemSpecAuth> appSubElemSpecAuths) {
        this.appSubElemSpecAuths = appSubElemSpecAuths;
    }




}


