package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppSubTabSpecAuth generated by hbm2java
 */
@Entity
@Table(name="APP_SUB_TAB_SPEC_AUTH"
    ,schema="SHAMS"
)
public class AppSubTabSpecAuth  implements java.io.Serializable {


     private AppSubTabSpecAuthId id;
     private AppSubTab appSubTab;
     private PerEmploymentMasters perEmploymentMastersByEmployeeId;
     private PerEmploymentMasters perEmploymentMastersByEmployeeIdAction;
     private Date actionDate;
     private String actionDateDetails;
     private byte primaryAuthPass;

    public AppSubTabSpecAuth() {
    }

	
    public AppSubTabSpecAuth(AppSubTabSpecAuthId id, AppSubTab appSubTab, PerEmploymentMasters perEmploymentMastersByEmployeeId, byte primaryAuthPass) {
        this.id = id;
        this.appSubTab = appSubTab;
        this.perEmploymentMastersByEmployeeId = perEmploymentMastersByEmployeeId;
        this.primaryAuthPass = primaryAuthPass;
    }
    public AppSubTabSpecAuth(AppSubTabSpecAuthId id, AppSubTab appSubTab, PerEmploymentMasters perEmploymentMastersByEmployeeId, PerEmploymentMasters perEmploymentMastersByEmployeeIdAction, Date actionDate, String actionDateDetails, byte primaryAuthPass) {
       this.id = id;
       this.appSubTab = appSubTab;
       this.perEmploymentMastersByEmployeeId = perEmploymentMastersByEmployeeId;
       this.perEmploymentMastersByEmployeeIdAction = perEmploymentMastersByEmployeeIdAction;
       this.actionDate = actionDate;
       this.actionDateDetails = actionDateDetails;
       this.primaryAuthPass = primaryAuthPass;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="subTabId", column=@Column(name="SUB_TAB_ID", nullable=false, precision=8, scale=0) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, length=10) ), 
        @AttributeOverride(name="applicationId", column=@Column(name="APPLICATION_ID", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="tabId", column=@Column(name="TAB_ID", nullable=false, precision=5, scale=0) ) } )
    public AppSubTabSpecAuthId getId() {
        return this.id;
    }
    
    public void setId(AppSubTabSpecAuthId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="APPLICATION_ID", referencedColumnName="APPLICATION_ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="TAB_ID", referencedColumnName="TAB_ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="SUB_TAB_ID", referencedColumnName="SUB_TAB_ID", nullable=false, insertable=false, updatable=false) } )
    public AppSubTab getAppSubTab() {
        return this.appSubTab;
    }
    
    public void setAppSubTab(AppSubTab appSubTab) {
        this.appSubTab = appSubTab;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false)
    public PerEmploymentMasters getPerEmploymentMastersByEmployeeId() {
        return this.perEmploymentMastersByEmployeeId;
    }
    
    public void setPerEmploymentMastersByEmployeeId(PerEmploymentMasters perEmploymentMastersByEmployeeId) {
        this.perEmploymentMastersByEmployeeId = perEmploymentMastersByEmployeeId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID_ACTION")
    public PerEmploymentMasters getPerEmploymentMastersByEmployeeIdAction() {
        return this.perEmploymentMastersByEmployeeIdAction;
    }
    
    public void setPerEmploymentMastersByEmployeeIdAction(PerEmploymentMasters perEmploymentMastersByEmployeeIdAction) {
        this.perEmploymentMastersByEmployeeIdAction = perEmploymentMastersByEmployeeIdAction;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ACTION_DATE", length=7)
    public Date getActionDate() {
        return this.actionDate;
    }
    
    public void setActionDate(Date actionDate) {
        this.actionDate = actionDate;
    }

    
    @Column(name="ACTION_DATE_DETAILS", length=25)
    public String getActionDateDetails() {
        return this.actionDateDetails;
    }
    
    public void setActionDateDetails(String actionDateDetails) {
        this.actionDateDetails = actionDateDetails;
    }

    
    @Column(name="PRIMARY_AUTH_PASS", nullable=false, precision=2, scale=0)
    public byte getPrimaryAuthPass() {
        return this.primaryAuthPass;
    }
    
    public void setPrimaryAuthPass(byte primaryAuthPass) {
        this.primaryAuthPass = primaryAuthPass;
    }




}


