package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AppTabs generated by hbm2java
 */
@Entity
@Table(name="APP_TABS"
    ,schema="SHAMS"
    , uniqueConstraints = @UniqueConstraint(columnNames={"APPLICATION_ID", "TAB_ID"}) 
)
public class AppTabs  implements java.io.Serializable {


     private AppTabsId id;

    public AppTabs() {
    }

    public AppTabs(AppTabsId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="applicationId", column=@Column(name="APPLICATION_ID", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="tabId", column=@Column(name="TAB_ID", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="tabName", column=@Column(name="TAB_NAME", nullable=false, length=50) ), 
        @AttributeOverride(name="tabFafaIcon", column=@Column(name="TAB_FAFA_ICON", length=50) ), 
        @AttributeOverride(name="tabIndex", column=@Column(name="TAB_INDEX", precision=5, scale=0) ) } )
    public AppTabsId getId() {
        return this.id;
    }
    
    public void setId(AppTabsId id) {
        this.id = id;
    }




}


