package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BudProjectSub generated by hbm2java
 */
@Entity
@Table(name="BUD_PROJECT_SUB"
    ,schema="SHAMS"
)
public class BudProjectSub  implements java.io.Serializable {


     private BudProjectSubId id;
     private BudProject budProject;
     private String projectSubName;
     private String filterProjectSubName;
     private Date projectSubStartDate;
     private BigDecimal projectSubPeriod;
     private String remarks;
     private BigDecimal estimatedCost;
     private String recordCreationUser;
     private Date recordCreationDate;
     private String lastUpdateUser;
     private Date lastUpdateDate;
     private String lastUpdateTransaction;
     private Set<PerEmploymentMasters> perEmploymentMastersesForPeremBudProjSFromFk = new HashSet<PerEmploymentMasters>(0);
     private Set<PerAnnualEvalModel> perAnnualEvalModels = new HashSet<PerAnnualEvalModel>(0);
     private Set<PerEmpHistory> perEmpHistoriesForPerehBudProjSFromFk = new HashSet<PerEmpHistory>(0);
     private Set<PerAnnualEval> perAnnualEvals = new HashSet<PerAnnualEval>(0);
     private Set<PerEmploymentMasters> perEmploymentMastersesForPeremBudProjSFk = new HashSet<PerEmploymentMasters>(0);
     private Set<PerEmpHistory> perEmpHistoriesForPerehBudProjSFk = new HashSet<PerEmpHistory>(0);

    public BudProjectSub() {
    }

	
    public BudProjectSub(BudProjectSubId id, BudProject budProject) {
        this.id = id;
        this.budProject = budProject;
    }
    public BudProjectSub(BudProjectSubId id, BudProject budProject, String projectSubName, String filterProjectSubName, Date projectSubStartDate, BigDecimal projectSubPeriod, String remarks, BigDecimal estimatedCost, String recordCreationUser, Date recordCreationDate, String lastUpdateUser, Date lastUpdateDate, String lastUpdateTransaction, Set<PerEmploymentMasters> perEmploymentMastersesForPeremBudProjSFromFk, Set<PerAnnualEvalModel> perAnnualEvalModels, Set<PerEmpHistory> perEmpHistoriesForPerehBudProjSFromFk, Set<PerAnnualEval> perAnnualEvals, Set<PerEmploymentMasters> perEmploymentMastersesForPeremBudProjSFk, Set<PerEmpHistory> perEmpHistoriesForPerehBudProjSFk) {
       this.id = id;
       this.budProject = budProject;
       this.projectSubName = projectSubName;
       this.filterProjectSubName = filterProjectSubName;
       this.projectSubStartDate = projectSubStartDate;
       this.projectSubPeriod = projectSubPeriod;
       this.remarks = remarks;
       this.estimatedCost = estimatedCost;
       this.recordCreationUser = recordCreationUser;
       this.recordCreationDate = recordCreationDate;
       this.lastUpdateUser = lastUpdateUser;
       this.lastUpdateDate = lastUpdateDate;
       this.lastUpdateTransaction = lastUpdateTransaction;
       this.perEmploymentMastersesForPeremBudProjSFromFk = perEmploymentMastersesForPeremBudProjSFromFk;
       this.perAnnualEvalModels = perAnnualEvalModels;
       this.perEmpHistoriesForPerehBudProjSFromFk = perEmpHistoriesForPerehBudProjSFromFk;
       this.perAnnualEvals = perAnnualEvals;
       this.perEmploymentMastersesForPeremBudProjSFk = perEmploymentMastersesForPeremBudProjSFk;
       this.perEmpHistoriesForPerehBudProjSFk = perEmpHistoriesForPerehBudProjSFk;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="projectCode", column=@Column(name="PROJECT_CODE", nullable=false, length=10) ), 
        @AttributeOverride(name="projectSubCode", column=@Column(name="PROJECT_SUB_CODE", nullable=false, length=6) ) } )
    public BudProjectSubId getId() {
        return this.id;
    }
    
    public void setId(BudProjectSubId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PROJECT_CODE", nullable=false, insertable=false, updatable=false)
    public BudProject getBudProject() {
        return this.budProject;
    }
    
    public void setBudProject(BudProject budProject) {
        this.budProject = budProject;
    }

    
    @Column(name="PROJECT_SUB_NAME", length=200)
    public String getProjectSubName() {
        return this.projectSubName;
    }
    
    public void setProjectSubName(String projectSubName) {
        this.projectSubName = projectSubName;
    }

    
    @Column(name="FILTER_PROJECT_SUB_NAME", length=200)
    public String getFilterProjectSubName() {
        return this.filterProjectSubName;
    }
    
    public void setFilterProjectSubName(String filterProjectSubName) {
        this.filterProjectSubName = filterProjectSubName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PROJECT_SUB_START_DATE", length=7)
    public Date getProjectSubStartDate() {
        return this.projectSubStartDate;
    }
    
    public void setProjectSubStartDate(Date projectSubStartDate) {
        this.projectSubStartDate = projectSubStartDate;
    }

    
    @Column(name="PROJECT_SUB_PERIOD", precision=5)
    public BigDecimal getProjectSubPeriod() {
        return this.projectSubPeriod;
    }
    
    public void setProjectSubPeriod(BigDecimal projectSubPeriod) {
        this.projectSubPeriod = projectSubPeriod;
    }

    
    @Column(name="REMARKS", length=100)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    
    @Column(name="ESTIMATED_COST", precision=12)
    public BigDecimal getEstimatedCost() {
        return this.estimatedCost;
    }
    
    public void setEstimatedCost(BigDecimal estimatedCost) {
        this.estimatedCost = estimatedCost;
    }

    
    @Column(name="RECORD_CREATION_USER", length=10)
    public String getRecordCreationUser() {
        return this.recordCreationUser;
    }
    
    public void setRecordCreationUser(String recordCreationUser) {
        this.recordCreationUser = recordCreationUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATION_DATE", length=7)
    public Date getRecordCreationDate() {
        return this.recordCreationDate;
    }
    
    public void setRecordCreationDate(Date recordCreationDate) {
        this.recordCreationDate = recordCreationDate;
    }

    
    @Column(name="LAST_UPDATE_USER", length=10)
    public String getLastUpdateUser() {
        return this.lastUpdateUser;
    }
    
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LAST_UPDATE_DATE", length=7)
    public Date getLastUpdateDate() {
        return this.lastUpdateDate;
    }
    
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    
    @Column(name="LAST_UPDATE_TRANSACTION", length=1)
    public String getLastUpdateTransaction() {
        return this.lastUpdateTransaction;
    }
    
    public void setLastUpdateTransaction(String lastUpdateTransaction) {
        this.lastUpdateTransaction = lastUpdateTransaction;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="budProjectSubByPeremBudProjSFromFk")
    public Set<PerEmploymentMasters> getPerEmploymentMastersesForPeremBudProjSFromFk() {
        return this.perEmploymentMastersesForPeremBudProjSFromFk;
    }
    
    public void setPerEmploymentMastersesForPeremBudProjSFromFk(Set<PerEmploymentMasters> perEmploymentMastersesForPeremBudProjSFromFk) {
        this.perEmploymentMastersesForPeremBudProjSFromFk = perEmploymentMastersesForPeremBudProjSFromFk;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="budProjectSub")
    public Set<PerAnnualEvalModel> getPerAnnualEvalModels() {
        return this.perAnnualEvalModels;
    }
    
    public void setPerAnnualEvalModels(Set<PerAnnualEvalModel> perAnnualEvalModels) {
        this.perAnnualEvalModels = perAnnualEvalModels;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="budProjectSubByPerehBudProjSFromFk")
    public Set<PerEmpHistory> getPerEmpHistoriesForPerehBudProjSFromFk() {
        return this.perEmpHistoriesForPerehBudProjSFromFk;
    }
    
    public void setPerEmpHistoriesForPerehBudProjSFromFk(Set<PerEmpHistory> perEmpHistoriesForPerehBudProjSFromFk) {
        this.perEmpHistoriesForPerehBudProjSFromFk = perEmpHistoriesForPerehBudProjSFromFk;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="budProjectSub")
    public Set<PerAnnualEval> getPerAnnualEvals() {
        return this.perAnnualEvals;
    }
    
    public void setPerAnnualEvals(Set<PerAnnualEval> perAnnualEvals) {
        this.perAnnualEvals = perAnnualEvals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="budProjectSubByPeremBudProjSFk")
    public Set<PerEmploymentMasters> getPerEmploymentMastersesForPeremBudProjSFk() {
        return this.perEmploymentMastersesForPeremBudProjSFk;
    }
    
    public void setPerEmploymentMastersesForPeremBudProjSFk(Set<PerEmploymentMasters> perEmploymentMastersesForPeremBudProjSFk) {
        this.perEmploymentMastersesForPeremBudProjSFk = perEmploymentMastersesForPeremBudProjSFk;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="budProjectSubByPerehBudProjSFk")
    public Set<PerEmpHistory> getPerEmpHistoriesForPerehBudProjSFk() {
        return this.perEmpHistoriesForPerehBudProjSFk;
    }
    
    public void setPerEmpHistoriesForPerehBudProjSFk(Set<PerEmpHistory> perEmpHistoriesForPerehBudProjSFk) {
        this.perEmpHistoriesForPerehBudProjSFk = perEmpHistoriesForPerehBudProjSFk;
    }




}


