package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * NvUsers generated by hbm2java
 */
@Entity
@Table(name="NV_USERS"
    ,schema="SHAMS"
    , uniqueConstraints = @UniqueConstraint(columnNames="LOGIN_NAME") 
)
public class NvUsers  implements java.io.Serializable {


     private BigDecimal userId;
     private String userName;
     private String userPass;
     private String confirmPass;
     private String userData;
     private String loginName;
     private String userType;
     private Set<PayDeserveEmpFileDtlRuf> payDeserveEmpFileDtlRufs = new HashSet<PayDeserveEmpFileDtlRuf>(0);
     private Set<PayEmployeeReq> payEmployeeReqs = new HashSet<PayEmployeeReq>(0);
     private Set<PayDeserveEmpFile> payDeserveEmpFiles = new HashSet<PayDeserveEmpFile>(0);

    public NvUsers() {
    }

	
    public NvUsers(BigDecimal userId) {
        this.userId = userId;
    }
    public NvUsers(BigDecimal userId, String userName, String userPass, String confirmPass, String userData, String loginName, String userType, Set<PayDeserveEmpFileDtlRuf> payDeserveEmpFileDtlRufs, Set<PayEmployeeReq> payEmployeeReqs, Set<PayDeserveEmpFile> payDeserveEmpFiles) {
       this.userId = userId;
       this.userName = userName;
       this.userPass = userPass;
       this.confirmPass = confirmPass;
       this.userData = userData;
       this.loginName = loginName;
       this.userType = userType;
       this.payDeserveEmpFileDtlRufs = payDeserveEmpFileDtlRufs;
       this.payEmployeeReqs = payEmployeeReqs;
       this.payDeserveEmpFiles = payDeserveEmpFiles;
    }
   
     @Id 

    
    @Column(name="USER_ID", unique=true, nullable=false, precision=22)
    public BigDecimal getUserId() {
        return this.userId;
    }
    
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    
    @Column(name="USER_NAME", length=200)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="USER_PASS", length=20)
    public String getUserPass() {
        return this.userPass;
    }
    
    public void setUserPass(String userPass) {
        this.userPass = userPass;
    }

    
    @Column(name="CONFIRM_PASS", length=20)
    public String getConfirmPass() {
        return this.confirmPass;
    }
    
    public void setConfirmPass(String confirmPass) {
        this.confirmPass = confirmPass;
    }

    
    @Column(name="USER_DATA", length=1000)
    public String getUserData() {
        return this.userData;
    }
    
    public void setUserData(String userData) {
        this.userData = userData;
    }

    
    @Column(name="LOGIN_NAME", unique=true, length=50)
    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    
    @Column(name="USER_TYPE", length=1)
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nvUsers")
    public Set<PayDeserveEmpFileDtlRuf> getPayDeserveEmpFileDtlRufs() {
        return this.payDeserveEmpFileDtlRufs;
    }
    
    public void setPayDeserveEmpFileDtlRufs(Set<PayDeserveEmpFileDtlRuf> payDeserveEmpFileDtlRufs) {
        this.payDeserveEmpFileDtlRufs = payDeserveEmpFileDtlRufs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nvUsers")
    public Set<PayEmployeeReq> getPayEmployeeReqs() {
        return this.payEmployeeReqs;
    }
    
    public void setPayEmployeeReqs(Set<PayEmployeeReq> payEmployeeReqs) {
        this.payEmployeeReqs = payEmployeeReqs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nvUsers")
    public Set<PayDeserveEmpFile> getPayDeserveEmpFiles() {
        return this.payDeserveEmpFiles;
    }
    
    public void setPayDeserveEmpFiles(Set<PayDeserveEmpFile> payDeserveEmpFiles) {
        this.payDeserveEmpFiles = payDeserveEmpFiles;
    }




}


