package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PayBandClassificationFile generated by hbm2java
 */
@Entity
@Table(name="PAY_BAND_CLASSIFICATION_FILE"
    ,schema="SHAMS"
)
public class PayBandClassificationFile  implements java.io.Serializable {


     private PayBandClassificationFileId id;
     private PayBandCode payBandCode;
     private PayMethodFileDtl payMethodFileDtl;
     private Byte chkMm;
     private Boolean chkModify;

    public PayBandClassificationFile() {
    }

	
    public PayBandClassificationFile(PayBandClassificationFileId id, PayBandCode payBandCode, PayMethodFileDtl payMethodFileDtl) {
        this.id = id;
        this.payBandCode = payBandCode;
        this.payMethodFileDtl = payMethodFileDtl;
    }
    public PayBandClassificationFile(PayBandClassificationFileId id, PayBandCode payBandCode, PayMethodFileDtl payMethodFileDtl, Byte chkMm, Boolean chkModify) {
       this.id = id;
       this.payBandCode = payBandCode;
       this.payMethodFileDtl = payMethodFileDtl;
       this.chkMm = chkMm;
       this.chkModify = chkModify;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fileSp", column=@Column(name="FILE_SP", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="methodType", column=@Column(name="METHOD_TYPE", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="bandCode", column=@Column(name="BAND_CODE", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="bandType", column=@Column(name="BAND_TYPE", nullable=false, precision=2, scale=0) ) } )
    public PayBandClassificationFileId getId() {
        return this.id;
    }
    
    public void setId(PayBandClassificationFileId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="BAND_TYPE", referencedColumnName="BAND_TYPE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="BAND_CODE", referencedColumnName="BAND_CODE", nullable=false, insertable=false, updatable=false) } )
    public PayBandCode getPayBandCode() {
        return this.payBandCode;
    }
    
    public void setPayBandCode(PayBandCode payBandCode) {
        this.payBandCode = payBandCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="METHOD_TYPE", referencedColumnName="METHOD_TYPE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="FILE_SP", referencedColumnName="FILE_SP", nullable=false, insertable=false, updatable=false) } )
    public PayMethodFileDtl getPayMethodFileDtl() {
        return this.payMethodFileDtl;
    }
    
    public void setPayMethodFileDtl(PayMethodFileDtl payMethodFileDtl) {
        this.payMethodFileDtl = payMethodFileDtl;
    }

    
    @Column(name="CHK_MM", precision=2, scale=0)
    public Byte getChkMm() {
        return this.chkMm;
    }
    
    public void setChkMm(Byte chkMm) {
        this.chkMm = chkMm;
    }

    
    @Column(name="CHK_MODIFY", precision=1, scale=0)
    public Boolean getChkModify() {
        return this.chkModify;
    }
    
    public void setChkModify(Boolean chkModify) {
        this.chkModify = chkModify;
    }




}


