package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PayBandType generated by hbm2java
 */
@Entity
@Table(name="PAY_BAND_TYPE"
    ,schema="SHAMS"
)
public class PayBandType  implements java.io.Serializable {


     private byte bandType;
     private String typeName;
     private Set<PayBandCode> payBandCodes = new HashSet<PayBandCode>(0);

    public PayBandType() {
    }

	
    public PayBandType(byte bandType) {
        this.bandType = bandType;
    }
    public PayBandType(byte bandType, String typeName, Set<PayBandCode> payBandCodes) {
       this.bandType = bandType;
       this.typeName = typeName;
       this.payBandCodes = payBandCodes;
    }
   
     @Id 

    
    @Column(name="BAND_TYPE", unique=true, nullable=false, precision=2, scale=0)
    public byte getBandType() {
        return this.bandType;
    }
    
    public void setBandType(byte bandType) {
        this.bandType = bandType;
    }

    
    @Column(name="TYPE_NAME", length=60)
    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="payBandType")
    public Set<PayBandCode> getPayBandCodes() {
        return this.payBandCodes;
    }
    
    public void setPayBandCodes(Set<PayBandCode> payBandCodes) {
        this.payBandCodes = payBandCodes;
    }




}


