package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PayBandCodeId generated by hbm2java
 */
@Embeddable
public class PayBandCodeId  implements java.io.Serializable {


     private byte bandType;
     private short bandCode;

    public PayBandCodeId() {
    }

    public PayBandCodeId(byte bandType, short bandCode) {
       this.bandType = bandType;
       this.bandCode = bandCode;
    }
   


    @Column(name="BAND_TYPE", nullable=false, precision=2, scale=0)
    public byte getBandType() {
        return this.bandType;
    }
    
    public void setBandType(byte bandType) {
        this.bandType = bandType;
    }


    @Column(name="BAND_CODE", nullable=false, precision=4, scale=0)
    public short getBandCode() {
        return this.bandCode;
    }
    
    public void setBandCode(short bandCode) {
        this.bandCode = bandCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PayBandCodeId) ) return false;
		 PayBandCodeId castOther = ( PayBandCodeId ) other; 
         
		 return (this.getBandType()==castOther.getBandType())
 && (this.getBandCode()==castOther.getBandCode());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getBandType();
         result = 37 * result + this.getBandCode();
         return result;
   }   


}


