package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PayDeserveEmpFileDtlRuf generated by hbm2java
 */
@Entity
@Table(name="PAY_DESERVE_EMP_FILE_DTL_RUF"
    ,schema="SHAMS"
)
public class PayDeserveEmpFileDtlRuf  implements java.io.Serializable {


     private int accessSp;
     private PayDeserveEmpFile payDeserveEmpFile;
     private PayEmployeeMaster payEmployeeMaster;
     private NvUsers nvUsers;
     private String employeeNo;
     private BigDecimal val;
     private Date currDate;
     private String currTime;
     private Date rufDate;
     private String rufTime;
     private String rmrk;

    public PayDeserveEmpFileDtlRuf() {
    }

	
    public PayDeserveEmpFileDtlRuf(int accessSp, PayDeserveEmpFile payDeserveEmpFile, PayEmployeeMaster payEmployeeMaster, String employeeNo) {
        this.accessSp = accessSp;
        this.payDeserveEmpFile = payDeserveEmpFile;
        this.payEmployeeMaster = payEmployeeMaster;
        this.employeeNo = employeeNo;
    }
    public PayDeserveEmpFileDtlRuf(int accessSp, PayDeserveEmpFile payDeserveEmpFile, PayEmployeeMaster payEmployeeMaster, NvUsers nvUsers, String employeeNo, BigDecimal val, Date currDate, String currTime, Date rufDate, String rufTime, String rmrk) {
       this.accessSp = accessSp;
       this.payDeserveEmpFile = payDeserveEmpFile;
       this.payEmployeeMaster = payEmployeeMaster;
       this.nvUsers = nvUsers;
       this.employeeNo = employeeNo;
       this.val = val;
       this.currDate = currDate;
       this.currTime = currTime;
       this.rufDate = rufDate;
       this.rufTime = rufTime;
       this.rmrk = rmrk;
    }
   
     @Id 

    
    @Column(name="ACCESS_SP", unique=true, nullable=false, precision=7, scale=0)
    public int getAccessSp() {
        return this.accessSp;
    }
    
    public void setAccessSp(int accessSp) {
        this.accessSp = accessSp;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="OPEN_MM", referencedColumnName="OPEN_MM", nullable=false), 
        @JoinColumn(name="OPEN_YYYY", referencedColumnName="OPEN_YYYY", nullable=false), 
        @JoinColumn(name="LOC_CODE", referencedColumnName="LOC_CODE", nullable=false), 
        @JoinColumn(name="BAND_TYPE", referencedColumnName="BAND_TYPE", nullable=false), 
        @JoinColumn(name="LOCATION_CODE", referencedColumnName="LOCATION_CODE", nullable=false), 
        @JoinColumn(name="BAND_CODE", referencedColumnName="BAND_CODE", nullable=false) } )
    public PayDeserveEmpFile getPayDeserveEmpFile() {
        return this.payDeserveEmpFile;
    }
    
    public void setPayDeserveEmpFile(PayDeserveEmpFile payDeserveEmpFile) {
        this.payDeserveEmpFile = payDeserveEmpFile;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false)
    public PayEmployeeMaster getPayEmployeeMaster() {
        return this.payEmployeeMaster;
    }
    
    public void setPayEmployeeMaster(PayEmployeeMaster payEmployeeMaster) {
        this.payEmployeeMaster = payEmployeeMaster;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USER_ID")
    public NvUsers getNvUsers() {
        return this.nvUsers;
    }
    
    public void setNvUsers(NvUsers nvUsers) {
        this.nvUsers = nvUsers;
    }

    
    @Column(name="EMPLOYEE_NO", nullable=false, length=10)
    public String getEmployeeNo() {
        return this.employeeNo;
    }
    
    public void setEmployeeNo(String employeeNo) {
        this.employeeNo = employeeNo;
    }

    
    @Column(name="VAL", precision=11)
    public BigDecimal getVal() {
        return this.val;
    }
    
    public void setVal(BigDecimal val) {
        this.val = val;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CURR_DATE", length=7)
    public Date getCurrDate() {
        return this.currDate;
    }
    
    public void setCurrDate(Date currDate) {
        this.currDate = currDate;
    }

    
    @Column(name="CURR_TIME", length=40)
    public String getCurrTime() {
        return this.currTime;
    }
    
    public void setCurrTime(String currTime) {
        this.currTime = currTime;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RUF_DATE", length=7)
    public Date getRufDate() {
        return this.rufDate;
    }
    
    public void setRufDate(Date rufDate) {
        this.rufDate = rufDate;
    }

    
    @Column(name="RUF_TIME", length=40)
    public String getRufTime() {
        return this.rufTime;
    }
    
    public void setRufTime(String rufTime) {
        this.rufTime = rufTime;
    }

    
    @Column(name="RMRK", length=200)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }




}


