package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PayDeserveEmpFileDtlId generated by hbm2java
 */
@Embeddable
public class PayDeserveEmpFileDtlId  implements java.io.Serializable {


     private short openYyyy;
     private byte openMm;
     private byte bandType;
     private String locationCode;
     private String locCode;
     private short bandCode;
     private int accessSp;

    public PayDeserveEmpFileDtlId() {
    }

    public PayDeserveEmpFileDtlId(short openYyyy, byte openMm, byte bandType, String locationCode, String locCode, short bandCode, int accessSp) {
       this.openYyyy = openYyyy;
       this.openMm = openMm;
       this.bandType = bandType;
       this.locationCode = locationCode;
       this.locCode = locCode;
       this.bandCode = bandCode;
       this.accessSp = accessSp;
    }
   


    @Column(name="OPEN_YYYY", nullable=false, precision=4, scale=0)
    public short getOpenYyyy() {
        return this.openYyyy;
    }
    
    public void setOpenYyyy(short openYyyy) {
        this.openYyyy = openYyyy;
    }


    @Column(name="OPEN_MM", nullable=false, precision=2, scale=0)
    public byte getOpenMm() {
        return this.openMm;
    }
    
    public void setOpenMm(byte openMm) {
        this.openMm = openMm;
    }


    @Column(name="BAND_TYPE", nullable=false, precision=2, scale=0)
    public byte getBandType() {
        return this.bandType;
    }
    
    public void setBandType(byte bandType) {
        this.bandType = bandType;
    }


    @Column(name="LOCATION_CODE", nullable=false, length=3)
    public String getLocationCode() {
        return this.locationCode;
    }
    
    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode;
    }


    @Column(name="LOC_CODE", nullable=false, length=3)
    public String getLocCode() {
        return this.locCode;
    }
    
    public void setLocCode(String locCode) {
        this.locCode = locCode;
    }


    @Column(name="BAND_CODE", nullable=false, precision=4, scale=0)
    public short getBandCode() {
        return this.bandCode;
    }
    
    public void setBandCode(short bandCode) {
        this.bandCode = bandCode;
    }


    @Column(name="ACCESS_SP", nullable=false, precision=7, scale=0)
    public int getAccessSp() {
        return this.accessSp;
    }
    
    public void setAccessSp(int accessSp) {
        this.accessSp = accessSp;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PayDeserveEmpFileDtlId) ) return false;
		 PayDeserveEmpFileDtlId castOther = ( PayDeserveEmpFileDtlId ) other; 
         
		 return (this.getOpenYyyy()==castOther.getOpenYyyy())
 && (this.getOpenMm()==castOther.getOpenMm())
 && (this.getBandType()==castOther.getBandType())
 && ( (this.getLocationCode()==castOther.getLocationCode()) || ( this.getLocationCode()!=null && castOther.getLocationCode()!=null && this.getLocationCode().equals(castOther.getLocationCode()) ) )
 && ( (this.getLocCode()==castOther.getLocCode()) || ( this.getLocCode()!=null && castOther.getLocCode()!=null && this.getLocCode().equals(castOther.getLocCode()) ) )
 && (this.getBandCode()==castOther.getBandCode())
 && (this.getAccessSp()==castOther.getAccessSp());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOpenYyyy();
         result = 37 * result + this.getOpenMm();
         result = 37 * result + this.getBandType();
         result = 37 * result + ( getLocationCode() == null ? 0 : this.getLocationCode().hashCode() );
         result = 37 * result + ( getLocCode() == null ? 0 : this.getLocCode().hashCode() );
         result = 37 * result + this.getBandCode();
         result = 37 * result + this.getAccessSp();
         return result;
   }   


}


