package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PayDeserveEmpFileDtl generated by hbm2java
 */
@Entity
@Table(name="PAY_DESERVE_EMP_FILE_DTL"
    ,schema="SHAMS"
)
public class PayDeserveEmpFileDtl  implements java.io.Serializable {


     private PayDeserveEmpFileDtlId id;
     private PayEmployeeMaster payEmployeeMasterByEmployeeId;
     private PayEmployeeMaster payEmployeeMasterByEmployeeIdUser;
     private PayDeserveEmpFile payDeserveEmpFile;
     private String employeeNo;
     private BigDecimal val;
     private Date currDate;
     private String currTime;
     private String rmrk;

    public PayDeserveEmpFileDtl() {
    }

	
    public PayDeserveEmpFileDtl(PayDeserveEmpFileDtlId id, PayEmployeeMaster payEmployeeMasterByEmployeeId, PayDeserveEmpFile payDeserveEmpFile, String employeeNo) {
        this.id = id;
        this.payEmployeeMasterByEmployeeId = payEmployeeMasterByEmployeeId;
        this.payDeserveEmpFile = payDeserveEmpFile;
        this.employeeNo = employeeNo;
    }
    public PayDeserveEmpFileDtl(PayDeserveEmpFileDtlId id, PayEmployeeMaster payEmployeeMasterByEmployeeId, PayEmployeeMaster payEmployeeMasterByEmployeeIdUser, PayDeserveEmpFile payDeserveEmpFile, String employeeNo, BigDecimal val, Date currDate, String currTime, String rmrk) {
       this.id = id;
       this.payEmployeeMasterByEmployeeId = payEmployeeMasterByEmployeeId;
       this.payEmployeeMasterByEmployeeIdUser = payEmployeeMasterByEmployeeIdUser;
       this.payDeserveEmpFile = payDeserveEmpFile;
       this.employeeNo = employeeNo;
       this.val = val;
       this.currDate = currDate;
       this.currTime = currTime;
       this.rmrk = rmrk;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="openYyyy", column=@Column(name="OPEN_YYYY", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="openMm", column=@Column(name="OPEN_MM", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="bandType", column=@Column(name="BAND_TYPE", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="locationCode", column=@Column(name="LOCATION_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="locCode", column=@Column(name="LOC_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="bandCode", column=@Column(name="BAND_CODE", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="accessSp", column=@Column(name="ACCESS_SP", nullable=false, precision=7, scale=0) ) } )
    public PayDeserveEmpFileDtlId getId() {
        return this.id;
    }
    
    public void setId(PayDeserveEmpFileDtlId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false)
    public PayEmployeeMaster getPayEmployeeMasterByEmployeeId() {
        return this.payEmployeeMasterByEmployeeId;
    }
    
    public void setPayEmployeeMasterByEmployeeId(PayEmployeeMaster payEmployeeMasterByEmployeeId) {
        this.payEmployeeMasterByEmployeeId = payEmployeeMasterByEmployeeId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID_USER")
    public PayEmployeeMaster getPayEmployeeMasterByEmployeeIdUser() {
        return this.payEmployeeMasterByEmployeeIdUser;
    }
    
    public void setPayEmployeeMasterByEmployeeIdUser(PayEmployeeMaster payEmployeeMasterByEmployeeIdUser) {
        this.payEmployeeMasterByEmployeeIdUser = payEmployeeMasterByEmployeeIdUser;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="OPEN_MM", referencedColumnName="OPEN_MM", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="OPEN_YYYY", referencedColumnName="OPEN_YYYY", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="LOC_CODE", referencedColumnName="LOC_CODE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="BAND_TYPE", referencedColumnName="BAND_TYPE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="LOCATION_CODE", referencedColumnName="LOCATION_CODE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="BAND_CODE", referencedColumnName="BAND_CODE", nullable=false, insertable=false, updatable=false) } )
    public PayDeserveEmpFile getPayDeserveEmpFile() {
        return this.payDeserveEmpFile;
    }
    
    public void setPayDeserveEmpFile(PayDeserveEmpFile payDeserveEmpFile) {
        this.payDeserveEmpFile = payDeserveEmpFile;
    }

    
    @Column(name="EMPLOYEE_NO", nullable=false, length=10)
    public String getEmployeeNo() {
        return this.employeeNo;
    }
    
    public void setEmployeeNo(String employeeNo) {
        this.employeeNo = employeeNo;
    }

    
    @Column(name="VAL", precision=11)
    public BigDecimal getVal() {
        return this.val;
    }
    
    public void setVal(BigDecimal val) {
        this.val = val;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CURR_DATE", length=7)
    public Date getCurrDate() {
        return this.currDate;
    }
    
    public void setCurrDate(Date currDate) {
        this.currDate = currDate;
    }

    
    @Column(name="CURR_TIME", length=240)
    public String getCurrTime() {
        return this.currTime;
    }
    
    public void setCurrTime(String currTime) {
        this.currTime = currTime;
    }

    
    @Column(name="RMRK", length=200)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }




}


