package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PayDeserveEmpFileStop generated by hbm2java
 */
@Entity
@Table(name="PAY_DESERVE_EMP_FILE_STOP"
    ,schema="SHAMS"
)
public class PayDeserveEmpFileStop  implements java.io.Serializable {


     private PayDeserveEmpFileStopId id;
     private PayEmployeeMaster payEmployeeMaster;
     private String employeeNo;
     private Date SFromDate;
     private Date SToDate;
     private Date currDate;
     private String currTime;
     private String rmrk;
     private Set<PayDeserveEmpFileStopDtl> payDeserveEmpFileStopDtls = new HashSet<PayDeserveEmpFileStopDtl>(0);

    public PayDeserveEmpFileStop() {
    }

	
    public PayDeserveEmpFileStop(PayDeserveEmpFileStopId id, PayEmployeeMaster payEmployeeMaster) {
        this.id = id;
        this.payEmployeeMaster = payEmployeeMaster;
    }
    public PayDeserveEmpFileStop(PayDeserveEmpFileStopId id, PayEmployeeMaster payEmployeeMaster, String employeeNo, Date SFromDate, Date SToDate, Date currDate, String currTime, String rmrk, Set<PayDeserveEmpFileStopDtl> payDeserveEmpFileStopDtls) {
       this.id = id;
       this.payEmployeeMaster = payEmployeeMaster;
       this.employeeNo = employeeNo;
       this.SFromDate = SFromDate;
       this.SToDate = SToDate;
       this.currDate = currDate;
       this.currTime = currTime;
       this.rmrk = rmrk;
       this.payDeserveEmpFileStopDtls = payDeserveEmpFileStopDtls;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, length=10) ), 
        @AttributeOverride(name="stopSp", column=@Column(name="STOP_SP", nullable=false, precision=6, scale=0) ) } )
    public PayDeserveEmpFileStopId getId() {
        return this.id;
    }
    
    public void setId(PayDeserveEmpFileStopId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false)
    public PayEmployeeMaster getPayEmployeeMaster() {
        return this.payEmployeeMaster;
    }
    
    public void setPayEmployeeMaster(PayEmployeeMaster payEmployeeMaster) {
        this.payEmployeeMaster = payEmployeeMaster;
    }

    
    @Column(name="EMPLOYEE_NO", length=240)
    public String getEmployeeNo() {
        return this.employeeNo;
    }
    
    public void setEmployeeNo(String employeeNo) {
        this.employeeNo = employeeNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="S_FROM_DATE", length=7)
    public Date getSFromDate() {
        return this.SFromDate;
    }
    
    public void setSFromDate(Date SFromDate) {
        this.SFromDate = SFromDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="S_TO_DATE", length=7)
    public Date getSToDate() {
        return this.SToDate;
    }
    
    public void setSToDate(Date SToDate) {
        this.SToDate = SToDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CURR_DATE", length=7)
    public Date getCurrDate() {
        return this.currDate;
    }
    
    public void setCurrDate(Date currDate) {
        this.currDate = currDate;
    }

    
    @Column(name="CURR_TIME", length=240)
    public String getCurrTime() {
        return this.currTime;
    }
    
    public void setCurrTime(String currTime) {
        this.currTime = currTime;
    }

    
    @Column(name="RMRK", length=200)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="payDeserveEmpFileStop")
    public Set<PayDeserveEmpFileStopDtl> getPayDeserveEmpFileStopDtls() {
        return this.payDeserveEmpFileStopDtls;
    }
    
    public void setPayDeserveEmpFileStopDtls(Set<PayDeserveEmpFileStopDtl> payDeserveEmpFileStopDtls) {
        this.payDeserveEmpFileStopDtls = payDeserveEmpFileStopDtls;
    }




}


