package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PayDeserveEmpFileStopId generated by hbm2java
 */
@Embeddable
public class PayDeserveEmpFileStopId  implements java.io.Serializable {


     private String employeeId;
     private int stopSp;

    public PayDeserveEmpFileStopId() {
    }

    public PayDeserveEmpFileStopId(String employeeId, int stopSp) {
       this.employeeId = employeeId;
       this.stopSp = stopSp;
    }
   


    @Column(name="EMPLOYEE_ID", nullable=false, length=10)
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }


    @Column(name="STOP_SP", nullable=false, precision=6, scale=0)
    public int getStopSp() {
        return this.stopSp;
    }
    
    public void setStopSp(int stopSp) {
        this.stopSp = stopSp;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PayDeserveEmpFileStopId) ) return false;
		 PayDeserveEmpFileStopId castOther = ( PayDeserveEmpFileStopId ) other; 
         
		 return ( (this.getEmployeeId()==castOther.getEmployeeId()) || ( this.getEmployeeId()!=null && castOther.getEmployeeId()!=null && this.getEmployeeId().equals(castOther.getEmployeeId()) ) )
 && (this.getStopSp()==castOther.getStopSp());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmployeeId() == null ? 0 : this.getEmployeeId().hashCode() );
         result = 37 * result + this.getStopSp();
         return result;
   }   


}


