package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PayEmployeeReqDtl generated by hbm2java
 */
@Entity
@Table(name="PAY_EMPLOYEE_REQ_DTL"
    ,schema="SHAMS"
)
public class PayEmployeeReqDtl  implements java.io.Serializable {


     private PayEmployeeReqDtlId id;
     private PayEmployeeReq payEmployeeReq;
     private PayBandCode payBandCode;
     private BigDecimal val;
     private Boolean creditType;
     private BigDecimal creditBalance;
     private String fiscalDegreeCode;
     private Byte statusCode;
     private Short statusGroup;
     private Short bankCode;
     private Long sarfCode;
     private String jobCode;
     private String orgId;
     private String locCode;
     private String locationCode;
     private Boolean insClass;
     private Integer execSeq;
     private Short dayNo;
     private BigDecimal val30;
     private BigDecimal val65;
     private BigDecimal val70;
     private String tafkit;

    public PayEmployeeReqDtl() {
    }

	
    public PayEmployeeReqDtl(PayEmployeeReqDtlId id, PayEmployeeReq payEmployeeReq, PayBandCode payBandCode, BigDecimal val) {
        this.id = id;
        this.payEmployeeReq = payEmployeeReq;
        this.payBandCode = payBandCode;
        this.val = val;
    }
    public PayEmployeeReqDtl(PayEmployeeReqDtlId id, PayEmployeeReq payEmployeeReq, PayBandCode payBandCode, BigDecimal val, Boolean creditType, BigDecimal creditBalance, String fiscalDegreeCode, Byte statusCode, Short statusGroup, Short bankCode, Long sarfCode, String jobCode, String orgId, String locCode, String locationCode, Boolean insClass, Integer execSeq, Short dayNo, BigDecimal val30, BigDecimal val65, BigDecimal val70, String tafkit) {
       this.id = id;
       this.payEmployeeReq = payEmployeeReq;
       this.payBandCode = payBandCode;
       this.val = val;
       this.creditType = creditType;
       this.creditBalance = creditBalance;
       this.fiscalDegreeCode = fiscalDegreeCode;
       this.statusCode = statusCode;
       this.statusGroup = statusGroup;
       this.bankCode = bankCode;
       this.sarfCode = sarfCode;
       this.jobCode = jobCode;
       this.orgId = orgId;
       this.locCode = locCode;
       this.locationCode = locationCode;
       this.insClass = insClass;
       this.execSeq = execSeq;
       this.dayNo = dayNo;
       this.val30 = val30;
       this.val65 = val65;
       this.val70 = val70;
       this.tafkit = tafkit;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="reqSp", column=@Column(name="REQ_SP", nullable=false, precision=16, scale=0) ), 
        @AttributeOverride(name="bandType", column=@Column(name="BAND_TYPE", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="bandCode", column=@Column(name="BAND_CODE", nullable=false, precision=4, scale=0) ) } )
    public PayEmployeeReqDtlId getId() {
        return this.id;
    }
    
    public void setId(PayEmployeeReqDtlId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="REQ_SP", nullable=false, insertable=false, updatable=false)
    public PayEmployeeReq getPayEmployeeReq() {
        return this.payEmployeeReq;
    }
    
    public void setPayEmployeeReq(PayEmployeeReq payEmployeeReq) {
        this.payEmployeeReq = payEmployeeReq;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="BAND_TYPE", referencedColumnName="BAND_TYPE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="BAND_CODE", referencedColumnName="BAND_CODE", nullable=false, insertable=false, updatable=false) } )
    public PayBandCode getPayBandCode() {
        return this.payBandCode;
    }
    
    public void setPayBandCode(PayBandCode payBandCode) {
        this.payBandCode = payBandCode;
    }

    
    @Column(name="VAL", nullable=false, precision=11)
    public BigDecimal getVal() {
        return this.val;
    }
    
    public void setVal(BigDecimal val) {
        this.val = val;
    }

    
    @Column(name="CREDIT_TYPE", precision=1, scale=0)
    public Boolean getCreditType() {
        return this.creditType;
    }
    
    public void setCreditType(Boolean creditType) {
        this.creditType = creditType;
    }

    
    @Column(name="CREDIT_BALANCE", precision=11)
    public BigDecimal getCreditBalance() {
        return this.creditBalance;
    }
    
    public void setCreditBalance(BigDecimal creditBalance) {
        this.creditBalance = creditBalance;
    }

    
    @Column(name="FISCAL_DEGREE_CODE", length=3)
    public String getFiscalDegreeCode() {
        return this.fiscalDegreeCode;
    }
    
    public void setFiscalDegreeCode(String fiscalDegreeCode) {
        this.fiscalDegreeCode = fiscalDegreeCode;
    }

    
    @Column(name="STATUS_CODE", precision=2, scale=0)
    public Byte getStatusCode() {
        return this.statusCode;
    }
    
    public void setStatusCode(Byte statusCode) {
        this.statusCode = statusCode;
    }

    
    @Column(name="STATUS_GROUP", precision=4, scale=0)
    public Short getStatusGroup() {
        return this.statusGroup;
    }
    
    public void setStatusGroup(Short statusGroup) {
        this.statusGroup = statusGroup;
    }

    
    @Column(name="BANK_CODE", precision=4, scale=0)
    public Short getBankCode() {
        return this.bankCode;
    }
    
    public void setBankCode(Short bankCode) {
        this.bankCode = bankCode;
    }

    
    @Column(name="SARF_CODE", precision=10, scale=0)
    public Long getSarfCode() {
        return this.sarfCode;
    }
    
    public void setSarfCode(Long sarfCode) {
        this.sarfCode = sarfCode;
    }

    
    @Column(name="JOB_CODE", length=5)
    public String getJobCode() {
        return this.jobCode;
    }
    
    public void setJobCode(String jobCode) {
        this.jobCode = jobCode;
    }

    
    @Column(name="ORG_ID", length=5)
    public String getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    
    @Column(name="LOC_CODE", length=3)
    public String getLocCode() {
        return this.locCode;
    }
    
    public void setLocCode(String locCode) {
        this.locCode = locCode;
    }

    
    @Column(name="LOCATION_CODE", length=3)
    public String getLocationCode() {
        return this.locationCode;
    }
    
    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode;
    }

    
    @Column(name="INS_CLASS", precision=1, scale=0)
    public Boolean getInsClass() {
        return this.insClass;
    }
    
    public void setInsClass(Boolean insClass) {
        this.insClass = insClass;
    }

    
    @Column(name="EXEC_SEQ", precision=6, scale=0)
    public Integer getExecSeq() {
        return this.execSeq;
    }
    
    public void setExecSeq(Integer execSeq) {
        this.execSeq = execSeq;
    }

    
    @Column(name="DAY_NO", precision=3, scale=0)
    public Short getDayNo() {
        return this.dayNo;
    }
    
    public void setDayNo(Short dayNo) {
        this.dayNo = dayNo;
    }

    
    @Column(name="VAL_30", precision=11)
    public BigDecimal getVal30() {
        return this.val30;
    }
    
    public void setVal30(BigDecimal val30) {
        this.val30 = val30;
    }

    
    @Column(name="VAL_65", precision=11)
    public BigDecimal getVal65() {
        return this.val65;
    }
    
    public void setVal65(BigDecimal val65) {
        this.val65 = val65;
    }

    
    @Column(name="VAL_70", precision=11)
    public BigDecimal getVal70() {
        return this.val70;
    }
    
    public void setVal70(BigDecimal val70) {
        this.val70 = val70;
    }

    
    @Column(name="TAFKIT", length=200)
    public String getTafkit() {
        return this.tafkit;
    }
    
    public void setTafkit(String tafkit) {
        this.tafkit = tafkit;
    }




}


