package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PayExecutionOpen generated by hbm2java
 */
@Entity
@Table(name="PAY_EXECUTION_OPEN"
    ,schema="SHAMS"
)
public class PayExecutionOpen  implements java.io.Serializable {


     private PayExecutionOpenId id;
     private Boolean chkOpen;
     private String rmrk;
     private Set<PayExecutionDate> payExecutionDates = new HashSet<PayExecutionDate>(0);
     private Set<PayDeserveEmp> payDeserveEmps = new HashSet<PayDeserveEmp>(0);
     private Set<PayDeserveEmpFile> payDeserveEmpFiles = new HashSet<PayDeserveEmpFile>(0);

    public PayExecutionOpen() {
    }

	
    public PayExecutionOpen(PayExecutionOpenId id) {
        this.id = id;
    }
    public PayExecutionOpen(PayExecutionOpenId id, Boolean chkOpen, String rmrk, Set<PayExecutionDate> payExecutionDates, Set<PayDeserveEmp> payDeserveEmps, Set<PayDeserveEmpFile> payDeserveEmpFiles) {
       this.id = id;
       this.chkOpen = chkOpen;
       this.rmrk = rmrk;
       this.payExecutionDates = payExecutionDates;
       this.payDeserveEmps = payDeserveEmps;
       this.payDeserveEmpFiles = payDeserveEmpFiles;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="openMm", column=@Column(name="OPEN_MM", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="openYyyy", column=@Column(name="OPEN_YYYY", nullable=false, precision=4, scale=0) ) } )
    public PayExecutionOpenId getId() {
        return this.id;
    }
    
    public void setId(PayExecutionOpenId id) {
        this.id = id;
    }

    
    @Column(name="CHK_OPEN", precision=1, scale=0)
    public Boolean getChkOpen() {
        return this.chkOpen;
    }
    
    public void setChkOpen(Boolean chkOpen) {
        this.chkOpen = chkOpen;
    }

    
    @Column(name="RMRK", length=150)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="payExecutionOpen")
    public Set<PayExecutionDate> getPayExecutionDates() {
        return this.payExecutionDates;
    }
    
    public void setPayExecutionDates(Set<PayExecutionDate> payExecutionDates) {
        this.payExecutionDates = payExecutionDates;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="payExecutionOpen")
    public Set<PayDeserveEmp> getPayDeserveEmps() {
        return this.payDeserveEmps;
    }
    
    public void setPayDeserveEmps(Set<PayDeserveEmp> payDeserveEmps) {
        this.payDeserveEmps = payDeserveEmps;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="payExecutionOpen")
    public Set<PayDeserveEmpFile> getPayDeserveEmpFiles() {
        return this.payDeserveEmpFiles;
    }
    
    public void setPayDeserveEmpFiles(Set<PayDeserveEmpFile> payDeserveEmpFiles) {
        this.payDeserveEmpFiles = payDeserveEmpFiles;
    }




}


