package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PayEmployeeReq generated by hbm2java
 */
@Entity
@Table(name="PAY_EMPLOYEE_REQ"
    ,schema="SHAMS"
)
public class PayEmployeeReq  implements java.io.Serializable {


     private long reqSp;
     private PerEmploymentMasters perEmploymentMasters;
     private NvUsers nvUsers;
     private Date reqDate;
     private Date execDate;
     private String chkView;
     private String doneDateTime;
     private String employeeNo;
     private String reqDateTime;
     private String rmrk;
     private Set<PayEmployeeReqDtl> payEmployeeReqDtls = new HashSet<PayEmployeeReqDtl>(0);

    public PayEmployeeReq() {
    }

	
    public PayEmployeeReq(long reqSp, String employeeNo) {
        this.reqSp = reqSp;
        this.employeeNo = employeeNo;
    }
    public PayEmployeeReq(long reqSp, PerEmploymentMasters perEmploymentMasters, NvUsers nvUsers, Date reqDate, Date execDate, String chkView, String doneDateTime, String employeeNo, String reqDateTime, String rmrk, Set<PayEmployeeReqDtl> payEmployeeReqDtls) {
       this.reqSp = reqSp;
       this.perEmploymentMasters = perEmploymentMasters;
       this.nvUsers = nvUsers;
       this.reqDate = reqDate;
       this.execDate = execDate;
       this.chkView = chkView;
       this.doneDateTime = doneDateTime;
       this.employeeNo = employeeNo;
       this.reqDateTime = reqDateTime;
       this.rmrk = rmrk;
       this.payEmployeeReqDtls = payEmployeeReqDtls;
    }
   
     @Id 

    
    @Column(name="REQ_SP", unique=true, nullable=false, precision=16, scale=0)
    public long getReqSp() {
        return this.reqSp;
    }
    
    public void setReqSp(long reqSp) {
        this.reqSp = reqSp;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMPLOYEE_ID")
    public PerEmploymentMasters getPerEmploymentMasters() {
        return this.perEmploymentMasters;
    }
    
    public void setPerEmploymentMasters(PerEmploymentMasters perEmploymentMasters) {
        this.perEmploymentMasters = perEmploymentMasters;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USER_ID")
    public NvUsers getNvUsers() {
        return this.nvUsers;
    }
    
    public void setNvUsers(NvUsers nvUsers) {
        this.nvUsers = nvUsers;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="REQ_DATE", length=7)
    public Date getReqDate() {
        return this.reqDate;
    }
    
    public void setReqDate(Date reqDate) {
        this.reqDate = reqDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXEC_DATE", length=7)
    public Date getExecDate() {
        return this.execDate;
    }
    
    public void setExecDate(Date execDate) {
        this.execDate = execDate;
    }

    
    @Column(name="CHK_VIEW", length=2)
    public String getChkView() {
        return this.chkView;
    }
    
    public void setChkView(String chkView) {
        this.chkView = chkView;
    }

    
    @Column(name="DONE_DATE_TIME", length=40)
    public String getDoneDateTime() {
        return this.doneDateTime;
    }
    
    public void setDoneDateTime(String doneDateTime) {
        this.doneDateTime = doneDateTime;
    }

    
    @Column(name="EMPLOYEE_NO", nullable=false, length=10)
    public String getEmployeeNo() {
        return this.employeeNo;
    }
    
    public void setEmployeeNo(String employeeNo) {
        this.employeeNo = employeeNo;
    }

    
    @Column(name="REQ_DATE_TIME", length=40)
    public String getReqDateTime() {
        return this.reqDateTime;
    }
    
    public void setReqDateTime(String reqDateTime) {
        this.reqDateTime = reqDateTime;
    }

    
    @Column(name="RMRK", length=200)
    public String getRmrk() {
        return this.rmrk;
    }
    
    public void setRmrk(String rmrk) {
        this.rmrk = rmrk;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="payEmployeeReq")
    public Set<PayEmployeeReqDtl> getPayEmployeeReqDtls() {
        return this.payEmployeeReqDtls;
    }
    
    public void setPayEmployeeReqDtls(Set<PayEmployeeReqDtl> payEmployeeReqDtls) {
        this.payEmployeeReqDtls = payEmployeeReqDtls;
    }




}


