package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PayFinancialGroupBand generated by hbm2java
 */
@Entity
@Table(name="PAY_FINANCIAL_GROUP_BAND"
    ,schema="SHAMS"
)
public class PayFinancialGroupBand  implements java.io.Serializable {


     private PayFinancialGroupBandId id;
     private PayBandCode payBandCode;
     private PayFinancialGroupType payFinancialGroupType;
     private PayMethodType payMethodType;
     private Boolean chkBand;

    public PayFinancialGroupBand() {
    }

	
    public PayFinancialGroupBand(PayFinancialGroupBandId id, PayBandCode payBandCode, PayFinancialGroupType payFinancialGroupType, PayMethodType payMethodType) {
        this.id = id;
        this.payBandCode = payBandCode;
        this.payFinancialGroupType = payFinancialGroupType;
        this.payMethodType = payMethodType;
    }
    public PayFinancialGroupBand(PayFinancialGroupBandId id, PayBandCode payBandCode, PayFinancialGroupType payFinancialGroupType, PayMethodType payMethodType, Boolean chkBand) {
       this.id = id;
       this.payBandCode = payBandCode;
       this.payFinancialGroupType = payFinancialGroupType;
       this.payMethodType = payMethodType;
       this.chkBand = chkBand;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="methodType", column=@Column(name="METHOD_TYPE", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="statusCode", column=@Column(name="STATUS_CODE", nullable=false, precision=2, scale=0) ), 
        @AttributeOverride(name="statusGroup", column=@Column(name="STATUS_GROUP", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="bandCode", column=@Column(name="BAND_CODE", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="bandType", column=@Column(name="BAND_TYPE", nullable=false, precision=2, scale=0) ) } )
    public PayFinancialGroupBandId getId() {
        return this.id;
    }
    
    public void setId(PayFinancialGroupBandId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="BAND_TYPE", referencedColumnName="BAND_TYPE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="BAND_CODE", referencedColumnName="BAND_CODE", nullable=false, insertable=false, updatable=false) } )
    public PayBandCode getPayBandCode() {
        return this.payBandCode;
    }
    
    public void setPayBandCode(PayBandCode payBandCode) {
        this.payBandCode = payBandCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="STATUS_CODE", referencedColumnName="STATUS_CODE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="STATUS_GROUP", referencedColumnName="STATUS_GROUP", nullable=false, insertable=false, updatable=false) } )
    public PayFinancialGroupType getPayFinancialGroupType() {
        return this.payFinancialGroupType;
    }
    
    public void setPayFinancialGroupType(PayFinancialGroupType payFinancialGroupType) {
        this.payFinancialGroupType = payFinancialGroupType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="METHOD_TYPE", nullable=false, insertable=false, updatable=false)
    public PayMethodType getPayMethodType() {
        return this.payMethodType;
    }
    
    public void setPayMethodType(PayMethodType payMethodType) {
        this.payMethodType = payMethodType;
    }

    
    @Column(name="CHK_BAND", precision=1, scale=0)
    public Boolean getChkBand() {
        return this.chkBand;
    }
    
    public void setChkBand(Boolean chkBand) {
        this.chkBand = chkBand;
    }




}


