package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PayMethodFileType generated by hbm2java
 */
@Entity
@Table(name="PAY_METHOD_FILE_TYPE"
    ,schema="SHAMS"
)
public class PayMethodFileType  implements java.io.Serializable {


     private PayMethodFileTypeId id;
     private PayMethodFile payMethodFile;

    public PayMethodFileType() {
    }

    public PayMethodFileType(PayMethodFileTypeId id, PayMethodFile payMethodFile) {
       this.id = id;
       this.payMethodFile = payMethodFile;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fileSp", column=@Column(name="FILE_SP", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="bandType", column=@Column(name="BAND_TYPE", nullable=false, precision=2, scale=0) ) } )
    public PayMethodFileTypeId getId() {
        return this.id;
    }
    
    public void setId(PayMethodFileTypeId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="FILE_SP", nullable=false, insertable=false, updatable=false)
    public PayMethodFile getPayMethodFile() {
        return this.payMethodFile;
    }
    
    public void setPayMethodFile(PayMethodFile payMethodFile) {
        this.payMethodFile = payMethodFile;
    }




}


