package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PaySarfCodeEmp generated by hbm2java
 */
@Entity
@Table(name="PAY_SARF_CODE_EMP"
    ,schema="SHAMS"
)
public class PaySarfCodeEmp  implements java.io.Serializable {


     private PaySarfCodeEmpId id;
     private PayEmployeeMaster payEmployeeMaster;
     private PaySarfCode paySarfCode;
     private String locationCode;
     private String employeeNo;

    public PaySarfCodeEmp() {
    }

	
    public PaySarfCodeEmp(PaySarfCodeEmpId id, PayEmployeeMaster payEmployeeMaster, PaySarfCode paySarfCode, String locationCode) {
        this.id = id;
        this.payEmployeeMaster = payEmployeeMaster;
        this.paySarfCode = paySarfCode;
        this.locationCode = locationCode;
    }
    public PaySarfCodeEmp(PaySarfCodeEmpId id, PayEmployeeMaster payEmployeeMaster, PaySarfCode paySarfCode, String locationCode, String employeeNo) {
       this.id = id;
       this.payEmployeeMaster = payEmployeeMaster;
       this.paySarfCode = paySarfCode;
       this.locationCode = locationCode;
       this.employeeNo = employeeNo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="sarfCode", column=@Column(name="SARF_CODE", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, length=10) ) } )
    public PaySarfCodeEmpId getId() {
        return this.id;
    }
    
    public void setId(PaySarfCodeEmpId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false)
    public PayEmployeeMaster getPayEmployeeMaster() {
        return this.payEmployeeMaster;
    }
    
    public void setPayEmployeeMaster(PayEmployeeMaster payEmployeeMaster) {
        this.payEmployeeMaster = payEmployeeMaster;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="SARF_CODE", nullable=false, insertable=false, updatable=false)
    public PaySarfCode getPaySarfCode() {
        return this.paySarfCode;
    }
    
    public void setPaySarfCode(PaySarfCode paySarfCode) {
        this.paySarfCode = paySarfCode;
    }

    
    @Column(name="LOCATION_CODE", nullable=false, length=3)
    public String getLocationCode() {
        return this.locationCode;
    }
    
    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode;
    }

    
    @Column(name="EMPLOYEE_NO", length=10)
    public String getEmployeeNo() {
        return this.employeeNo;
    }
    
    public void setEmployeeNo(String employeeNo) {
        this.employeeNo = employeeNo;
    }




}


