package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PerAnnualEvalModEmpTot generated by hbm2java
 */
@Entity
@Table(name="PER_ANNUAL_EVAL_MOD_EMP_TOT"
    ,schema="SHAMS"
)
public class PerAnnualEvalModEmpTot  implements java.io.Serializable {


     private PerAnnualEvalModEmpTotId id;
     private PerEmploymentMasters perEmploymentMasters;
     private PerGroupDegree perGroupDegree;
     private PerJobCode perJobCode;
     private Set<PerAnnualEvaModEmpTotDtl> perAnnualEvaModEmpTotDtls = new HashSet<PerAnnualEvaModEmpTotDtl>(0);

    public PerAnnualEvalModEmpTot() {
    }

	
    public PerAnnualEvalModEmpTot(PerAnnualEvalModEmpTotId id, PerEmploymentMasters perEmploymentMasters) {
        this.id = id;
        this.perEmploymentMasters = perEmploymentMasters;
    }
    public PerAnnualEvalModEmpTot(PerAnnualEvalModEmpTotId id, PerEmploymentMasters perEmploymentMasters, PerGroupDegree perGroupDegree, PerJobCode perJobCode, Set<PerAnnualEvaModEmpTotDtl> perAnnualEvaModEmpTotDtls) {
       this.id = id;
       this.perEmploymentMasters = perEmploymentMasters;
       this.perGroupDegree = perGroupDegree;
       this.perJobCode = perJobCode;
       this.perAnnualEvaModEmpTotDtls = perAnnualEvaModEmpTotDtls;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, length=10) ), 
        @AttributeOverride(name="empSerial", column=@Column(name="EMP_SERIAL", nullable=false, length=5) ) } )
    public PerAnnualEvalModEmpTotId getId() {
        return this.id;
    }
    
    public void setId(PerAnnualEvalModEmpTotId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false)
    public PerEmploymentMasters getPerEmploymentMasters() {
        return this.perEmploymentMasters;
    }
    
    public void setPerEmploymentMasters(PerEmploymentMasters perEmploymentMasters) {
        this.perEmploymentMasters = perEmploymentMasters;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="GROUP_TYPE_CODE", referencedColumnName="GROUP_TYPE_CODE"), 
        @JoinColumn(name="FISCAL_DEGREE_CODE", referencedColumnName="FISCAL_DEGREE_CODE") } )
    public PerGroupDegree getPerGroupDegree() {
        return this.perGroupDegree;
    }
    
    public void setPerGroupDegree(PerGroupDegree perGroupDegree) {
        this.perGroupDegree = perGroupDegree;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="JOB_CODE")
    public PerJobCode getPerJobCode() {
        return this.perJobCode;
    }
    
    public void setPerJobCode(PerJobCode perJobCode) {
        this.perJobCode = perJobCode;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perAnnualEvalModEmpTot")
    public Set<PerAnnualEvaModEmpTotDtl> getPerAnnualEvaModEmpTotDtls() {
        return this.perAnnualEvaModEmpTotDtls;
    }
    
    public void setPerAnnualEvaModEmpTotDtls(Set<PerAnnualEvaModEmpTotDtl> perAnnualEvaModEmpTotDtls) {
        this.perAnnualEvaModEmpTotDtls = perAnnualEvaModEmpTotDtls;
    }




}


