package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PerAttendanceWrkTypeDetail generated by hbm2java
 */
@Entity
@Table(name="PER_ATTENDANCE_WRK_TYPE_DETAIL"
    ,schema="SHAMS"
)
public class PerAttendanceWrkTypeDetail  implements java.io.Serializable {


     private PerAttendanceWrkTypeDetailId id;
     private PerAttendanceWrkTypeCode perAttendanceWrkTypeCode;
     private String remark;
     private byte workDays;
     private boolean workDaysType;
     private BigDecimal salaryRatio;
     private byte attendanceMin;
     private byte attendanceHour;
     private Byte attendanceDelayMin;
     private Byte attendanceDelayHour;
     private byte dismissMin;
     private byte dismissHour;
     private Byte dismissEarlyMin;
     private Byte dismissEarlyHour;
     private BigDecimal vacationRatio;
     private Set<PerEmpHistory> perEmpHistories = new HashSet<PerEmpHistory>(0);
     private Set<PerEmploymentMasters> perEmploymentMasterses = new HashSet<PerEmploymentMasters>(0);

    public PerAttendanceWrkTypeDetail() {
    }

	
    public PerAttendanceWrkTypeDetail(PerAttendanceWrkTypeDetailId id, PerAttendanceWrkTypeCode perAttendanceWrkTypeCode, byte workDays, boolean workDaysType, byte attendanceMin, byte attendanceHour, byte dismissMin, byte dismissHour) {
        this.id = id;
        this.perAttendanceWrkTypeCode = perAttendanceWrkTypeCode;
        this.workDays = workDays;
        this.workDaysType = workDaysType;
        this.attendanceMin = attendanceMin;
        this.attendanceHour = attendanceHour;
        this.dismissMin = dismissMin;
        this.dismissHour = dismissHour;
    }
    public PerAttendanceWrkTypeDetail(PerAttendanceWrkTypeDetailId id, PerAttendanceWrkTypeCode perAttendanceWrkTypeCode, String remark, byte workDays, boolean workDaysType, BigDecimal salaryRatio, byte attendanceMin, byte attendanceHour, Byte attendanceDelayMin, Byte attendanceDelayHour, byte dismissMin, byte dismissHour, Byte dismissEarlyMin, Byte dismissEarlyHour, BigDecimal vacationRatio, Set<PerEmpHistory> perEmpHistories, Set<PerEmploymentMasters> perEmploymentMasterses) {
       this.id = id;
       this.perAttendanceWrkTypeCode = perAttendanceWrkTypeCode;
       this.remark = remark;
       this.workDays = workDays;
       this.workDaysType = workDaysType;
       this.salaryRatio = salaryRatio;
       this.attendanceMin = attendanceMin;
       this.attendanceHour = attendanceHour;
       this.attendanceDelayMin = attendanceDelayMin;
       this.attendanceDelayHour = attendanceDelayHour;
       this.dismissMin = dismissMin;
       this.dismissHour = dismissHour;
       this.dismissEarlyMin = dismissEarlyMin;
       this.dismissEarlyHour = dismissEarlyHour;
       this.vacationRatio = vacationRatio;
       this.perEmpHistories = perEmpHistories;
       this.perEmploymentMasterses = perEmploymentMasterses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="workTypeCode", column=@Column(name="WORK_TYPE_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="workTypeSeq", column=@Column(name="WORK_TYPE_SEQ", nullable=false, length=3) ) } )
    public PerAttendanceWrkTypeDetailId getId() {
        return this.id;
    }
    
    public void setId(PerAttendanceWrkTypeDetailId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="WORK_TYPE_CODE", nullable=false, insertable=false, updatable=false)
    public PerAttendanceWrkTypeCode getPerAttendanceWrkTypeCode() {
        return this.perAttendanceWrkTypeCode;
    }
    
    public void setPerAttendanceWrkTypeCode(PerAttendanceWrkTypeCode perAttendanceWrkTypeCode) {
        this.perAttendanceWrkTypeCode = perAttendanceWrkTypeCode;
    }

    
    @Column(name="REMARK", length=250)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="WORK_DAYS", nullable=false, precision=2, scale=0)
    public byte getWorkDays() {
        return this.workDays;
    }
    
    public void setWorkDays(byte workDays) {
        this.workDays = workDays;
    }

    
    @Column(name="WORK_DAYS_TYPE", nullable=false, precision=1, scale=0)
    public boolean isWorkDaysType() {
        return this.workDaysType;
    }
    
    public void setWorkDaysType(boolean workDaysType) {
        this.workDaysType = workDaysType;
    }

    
    @Column(name="SALARY_RATIO", precision=5)
    public BigDecimal getSalaryRatio() {
        return this.salaryRatio;
    }
    
    public void setSalaryRatio(BigDecimal salaryRatio) {
        this.salaryRatio = salaryRatio;
    }

    
    @Column(name="ATTENDANCE_MIN", nullable=false, precision=2, scale=0)
    public byte getAttendanceMin() {
        return this.attendanceMin;
    }
    
    public void setAttendanceMin(byte attendanceMin) {
        this.attendanceMin = attendanceMin;
    }

    
    @Column(name="ATTENDANCE_HOUR", nullable=false, precision=2, scale=0)
    public byte getAttendanceHour() {
        return this.attendanceHour;
    }
    
    public void setAttendanceHour(byte attendanceHour) {
        this.attendanceHour = attendanceHour;
    }

    
    @Column(name="ATTENDANCE_DELAY_MIN", precision=2, scale=0)
    public Byte getAttendanceDelayMin() {
        return this.attendanceDelayMin;
    }
    
    public void setAttendanceDelayMin(Byte attendanceDelayMin) {
        this.attendanceDelayMin = attendanceDelayMin;
    }

    
    @Column(name="ATTENDANCE_DELAY_HOUR", precision=2, scale=0)
    public Byte getAttendanceDelayHour() {
        return this.attendanceDelayHour;
    }
    
    public void setAttendanceDelayHour(Byte attendanceDelayHour) {
        this.attendanceDelayHour = attendanceDelayHour;
    }

    
    @Column(name="DISMISS_MIN", nullable=false, precision=2, scale=0)
    public byte getDismissMin() {
        return this.dismissMin;
    }
    
    public void setDismissMin(byte dismissMin) {
        this.dismissMin = dismissMin;
    }

    
    @Column(name="DISMISS_HOUR", nullable=false, precision=2, scale=0)
    public byte getDismissHour() {
        return this.dismissHour;
    }
    
    public void setDismissHour(byte dismissHour) {
        this.dismissHour = dismissHour;
    }

    
    @Column(name="DISMISS_EARLY_MIN", precision=2, scale=0)
    public Byte getDismissEarlyMin() {
        return this.dismissEarlyMin;
    }
    
    public void setDismissEarlyMin(Byte dismissEarlyMin) {
        this.dismissEarlyMin = dismissEarlyMin;
    }

    
    @Column(name="DISMISS_EARLY_HOUR", precision=2, scale=0)
    public Byte getDismissEarlyHour() {
        return this.dismissEarlyHour;
    }
    
    public void setDismissEarlyHour(Byte dismissEarlyHour) {
        this.dismissEarlyHour = dismissEarlyHour;
    }

    
    @Column(name="VACATION_RATIO", precision=5)
    public BigDecimal getVacationRatio() {
        return this.vacationRatio;
    }
    
    public void setVacationRatio(BigDecimal vacationRatio) {
        this.vacationRatio = vacationRatio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perAttendanceWrkTypeDetail")
    public Set<PerEmpHistory> getPerEmpHistories() {
        return this.perEmpHistories;
    }
    
    public void setPerEmpHistories(Set<PerEmpHistory> perEmpHistories) {
        this.perEmpHistories = perEmpHistories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perAttendanceWrkTypeDetail")
    public Set<PerEmploymentMasters> getPerEmploymentMasterses() {
        return this.perEmploymentMasterses;
    }
    
    public void setPerEmploymentMasterses(Set<PerEmploymentMasters> perEmploymentMasterses) {
        this.perEmploymentMasterses = perEmploymentMasterses;
    }




}


