package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerAnnualEvalYear generated by hbm2java
 */
@Entity
@Table(name="PER_ANNUAL_EVAL_YEAR"
    ,schema="SHAMS"
)
public class PerAnnualEvalYear  implements java.io.Serializable {


     private PerAnnualEvalYearId id;
     private BudLocation budLocation;
     private Date annualFromDate;
     private Date annualToDate;
     private Set<PerAnnualEval> perAnnualEvals = new HashSet<PerAnnualEval>(0);
     private Set<PerAnnualEvalModel> perAnnualEvalModels = new HashSet<PerAnnualEvalModel>(0);

    public PerAnnualEvalYear() {
    }

	
    public PerAnnualEvalYear(PerAnnualEvalYearId id, BudLocation budLocation, Date annualFromDate, Date annualToDate) {
        this.id = id;
        this.budLocation = budLocation;
        this.annualFromDate = annualFromDate;
        this.annualToDate = annualToDate;
    }
    public PerAnnualEvalYear(PerAnnualEvalYearId id, BudLocation budLocation, Date annualFromDate, Date annualToDate, Set<PerAnnualEval> perAnnualEvals, Set<PerAnnualEvalModel> perAnnualEvalModels) {
       this.id = id;
       this.budLocation = budLocation;
       this.annualFromDate = annualFromDate;
       this.annualToDate = annualToDate;
       this.perAnnualEvals = perAnnualEvals;
       this.perAnnualEvalModels = perAnnualEvalModels;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="locationCode", column=@Column(name="LOCATION_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="annualId", column=@Column(name="ANNUAL_ID", nullable=false, length=5) ) } )
    public PerAnnualEvalYearId getId() {
        return this.id;
    }
    
    public void setId(PerAnnualEvalYearId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="LOCATION_CODE", nullable=false, insertable=false, updatable=false)
    public BudLocation getBudLocation() {
        return this.budLocation;
    }
    
    public void setBudLocation(BudLocation budLocation) {
        this.budLocation = budLocation;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ANNUAL_FROM_DATE", nullable=false, length=7)
    public Date getAnnualFromDate() {
        return this.annualFromDate;
    }
    
    public void setAnnualFromDate(Date annualFromDate) {
        this.annualFromDate = annualFromDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ANNUAL_TO_DATE", nullable=false, length=7)
    public Date getAnnualToDate() {
        return this.annualToDate;
    }
    
    public void setAnnualToDate(Date annualToDate) {
        this.annualToDate = annualToDate;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perAnnualEvalYear")
    public Set<PerAnnualEval> getPerAnnualEvals() {
        return this.perAnnualEvals;
    }
    
    public void setPerAnnualEvals(Set<PerAnnualEval> perAnnualEvals) {
        this.perAnnualEvals = perAnnualEvals;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perAnnualEvalYear")
    public Set<PerAnnualEvalModel> getPerAnnualEvalModels() {
        return this.perAnnualEvalModels;
    }
    
    public void setPerAnnualEvalModels(Set<PerAnnualEvalModel> perAnnualEvalModels) {
        this.perAnnualEvalModels = perAnnualEvalModels;
    }




}


