package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PerAnnualEvalType generated by hbm2java
 */
@Entity
@Table(name="PER_ANNUAL_EVAL_TYPE"
    ,schema="SHAMS"
)
public class PerAnnualEvalType  implements java.io.Serializable {


     private String evalTypeSerial;
     private String evalTypeName;
     private short evalTypeAmount;
     private Set<PerAnnualEvalModel> perAnnualEvalModels = new HashSet<PerAnnualEvalModel>(0);
     private Set<PerEvalAttribute> perEvalAttributes = new HashSet<PerEvalAttribute>(0);

    public PerAnnualEvalType() {
    }

	
    public PerAnnualEvalType(String evalTypeSerial, String evalTypeName, short evalTypeAmount) {
        this.evalTypeSerial = evalTypeSerial;
        this.evalTypeName = evalTypeName;
        this.evalTypeAmount = evalTypeAmount;
    }
    public PerAnnualEvalType(String evalTypeSerial, String evalTypeName, short evalTypeAmount, Set<PerAnnualEvalModel> perAnnualEvalModels, Set<PerEvalAttribute> perEvalAttributes) {
       this.evalTypeSerial = evalTypeSerial;
       this.evalTypeName = evalTypeName;
       this.evalTypeAmount = evalTypeAmount;
       this.perAnnualEvalModels = perAnnualEvalModels;
       this.perEvalAttributes = perEvalAttributes;
    }
   
     @Id 

    
    @Column(name="EVAL_TYPE_SERIAL", unique=true, nullable=false, length=5)
    public String getEvalTypeSerial() {
        return this.evalTypeSerial;
    }
    
    public void setEvalTypeSerial(String evalTypeSerial) {
        this.evalTypeSerial = evalTypeSerial;
    }

    
    @Column(name="EVAL_TYPE_NAME", nullable=false, length=75)
    public String getEvalTypeName() {
        return this.evalTypeName;
    }
    
    public void setEvalTypeName(String evalTypeName) {
        this.evalTypeName = evalTypeName;
    }

    
    @Column(name="EVAL_TYPE_AMOUNT", nullable=false, precision=3, scale=0)
    public short getEvalTypeAmount() {
        return this.evalTypeAmount;
    }
    
    public void setEvalTypeAmount(short evalTypeAmount) {
        this.evalTypeAmount = evalTypeAmount;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perAnnualEvalType")
    public Set<PerAnnualEvalModel> getPerAnnualEvalModels() {
        return this.perAnnualEvalModels;
    }
    
    public void setPerAnnualEvalModels(Set<PerAnnualEvalModel> perAnnualEvalModels) {
        this.perAnnualEvalModels = perAnnualEvalModels;
    }

@ManyToMany(fetch=FetchType.EAGER)
    @JoinTable(name="PER_EVAL_TYPE_ATTRIBUTE", schema="SHAMS", joinColumns = { 
        @JoinColumn(name="EVAL_TYPE_SERIAL", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="ATTRIBUTE_NO", nullable=false, updatable=false) })
    public Set<PerEvalAttribute> getPerEvalAttributes() {
        return this.perEvalAttributes;
    }
    
    public void setPerEvalAttributes(Set<PerEvalAttribute> perEvalAttributes) {
        this.perEvalAttributes = perEvalAttributes;
    }




}


