package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PerAnnualEvalModEmpTotId generated by hbm2java
 */
@Embeddable
public class PerAnnualEvalModEmpTotId  implements java.io.Serializable {


     private String employeeId;
     private String empSerial;

    public PerAnnualEvalModEmpTotId() {
    }

    public PerAnnualEvalModEmpTotId(String employeeId, String empSerial) {
       this.employeeId = employeeId;
       this.empSerial = empSerial;
    }
   


    @Column(name="EMPLOYEE_ID", nullable=false, length=10)
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }


    @Column(name="EMP_SERIAL", nullable=false, length=5)
    public String getEmpSerial() {
        return this.empSerial;
    }
    
    public void setEmpSerial(String empSerial) {
        this.empSerial = empSerial;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PerAnnualEvalModEmpTotId) ) return false;
		 PerAnnualEvalModEmpTotId castOther = ( PerAnnualEvalModEmpTotId ) other; 
         
		 return ( (this.getEmployeeId()==castOther.getEmployeeId()) || ( this.getEmployeeId()!=null && castOther.getEmployeeId()!=null && this.getEmployeeId().equals(castOther.getEmployeeId()) ) )
 && ( (this.getEmpSerial()==castOther.getEmpSerial()) || ( this.getEmpSerial()!=null && castOther.getEmpSerial()!=null && this.getEmpSerial().equals(castOther.getEmpSerial()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmployeeId() == null ? 0 : this.getEmployeeId().hashCode() );
         result = 37 * result + ( getEmpSerial() == null ? 0 : this.getEmpSerial().hashCode() );
         return result;
   }   


}


