package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PerAttendanceExistZk generated by hbm2java
 */
@Entity
@Table(name="PER_ATTENDANCE_EXIST_ZK"
    ,schema="SHAMS"
    , uniqueConstraints = @UniqueConstraint(columnNames={"ATTENDANCE_DATE", "EMPLOYEE_NO", "TIME_HH", "TIME_MM", "TIME_SS"}) 
)
public class PerAttendanceExistZk  implements java.io.Serializable {


     private PerAttendanceExistZkId id;
     private String empSerial;
     private BigDecimal empSql;

    public PerAttendanceExistZk() {
    }

	
    public PerAttendanceExistZk(PerAttendanceExistZkId id) {
        this.id = id;
    }
    public PerAttendanceExistZk(PerAttendanceExistZkId id, String empSerial, BigDecimal empSql) {
       this.id = id;
       this.empSerial = empSerial;
       this.empSql = empSql;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="attendanceDate", column=@Column(name="ATTENDANCE_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="employeeNo", column=@Column(name="EMPLOYEE_NO", nullable=false, length=10) ), 
        @AttributeOverride(name="timeHh", column=@Column(name="TIME_HH", nullable=false, length=2) ), 
        @AttributeOverride(name="timeMm", column=@Column(name="TIME_MM", nullable=false, length=2) ), 
        @AttributeOverride(name="timeSs", column=@Column(name="TIME_SS", nullable=false, length=2) ), 
        @AttributeOverride(name="transKind", column=@Column(name="TRANS_KIND", nullable=false, precision=1, scale=0) ) } )
    public PerAttendanceExistZkId getId() {
        return this.id;
    }
    
    public void setId(PerAttendanceExistZkId id) {
        this.id = id;
    }

    
    @Column(name="EMP_SERIAL", length=5)
    public String getEmpSerial() {
        return this.empSerial;
    }
    
    public void setEmpSerial(String empSerial) {
        this.empSerial = empSerial;
    }

    
    @Column(name="EMP_SQL", precision=20, scale=0)
    public BigDecimal getEmpSql() {
        return this.empSql;
    }
    
    public void setEmpSql(BigDecimal empSql) {
        this.empSql = empSql;
    }




}


