package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerAttendanceExistZk generated by hbm2java
 */
@Entity
@Table(name="PER_ATTENDANCE_EXIST_ZK"
    ,schema="SHAMS"
)
public class PerAttendanceExistZk  implements java.io.Serializable {


     private PerAttendanceExistZkId id;
     private PerEmploymentMasters perEmploymentMasters;
     private String timeMm;
     private String timeSs;
     private String timeHh;
     private Date postDate;
     private String postTime;
     private String machineNo;
     private String employeeNo;

    public PerAttendanceExistZk() {
    }

	
    public PerAttendanceExistZk(PerAttendanceExistZkId id, PerEmploymentMasters perEmploymentMasters, String timeMm, String timeSs, String timeHh, String employeeNo) {
        this.id = id;
        this.perEmploymentMasters = perEmploymentMasters;
        this.timeMm = timeMm;
        this.timeSs = timeSs;
        this.timeHh = timeHh;
        this.employeeNo = employeeNo;
    }
    public PerAttendanceExistZk(PerAttendanceExistZkId id, PerEmploymentMasters perEmploymentMasters, String timeMm, String timeSs, String timeHh, Date postDate, String postTime, String machineNo, String employeeNo) {
       this.id = id;
       this.perEmploymentMasters = perEmploymentMasters;
       this.timeMm = timeMm;
       this.timeSs = timeSs;
       this.timeHh = timeHh;
       this.postDate = postDate;
       this.postTime = postTime;
       this.machineNo = machineNo;
       this.employeeNo = employeeNo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="attendanceDate", column=@Column(name="ATTENDANCE_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, length=10) ), 
        @AttributeOverride(name="attendanceSp", column=@Column(name="ATTENDANCE_SP", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="transKind", column=@Column(name="TRANS_KIND", nullable=false, precision=2, scale=0) ) } )
    public PerAttendanceExistZkId getId() {
        return this.id;
    }
    
    public void setId(PerAttendanceExistZkId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false)
    public PerEmploymentMasters getPerEmploymentMasters() {
        return this.perEmploymentMasters;
    }
    
    public void setPerEmploymentMasters(PerEmploymentMasters perEmploymentMasters) {
        this.perEmploymentMasters = perEmploymentMasters;
    }

    
    @Column(name="TIME_MM", nullable=false, length=2)
    public String getTimeMm() {
        return this.timeMm;
    }
    
    public void setTimeMm(String timeMm) {
        this.timeMm = timeMm;
    }

    
    @Column(name="TIME_SS", nullable=false, length=2)
    public String getTimeSs() {
        return this.timeSs;
    }
    
    public void setTimeSs(String timeSs) {
        this.timeSs = timeSs;
    }

    
    @Column(name="TIME_HH", nullable=false, length=2)
    public String getTimeHh() {
        return this.timeHh;
    }
    
    public void setTimeHh(String timeHh) {
        this.timeHh = timeHh;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="POST_DATE", length=7)
    public Date getPostDate() {
        return this.postDate;
    }
    
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }

    
    @Column(name="POST_TIME", length=20)
    public String getPostTime() {
        return this.postTime;
    }
    
    public void setPostTime(String postTime) {
        this.postTime = postTime;
    }

    
    @Column(name="MACHINE_NO", length=40)
    public String getMachineNo() {
        return this.machineNo;
    }
    
    public void setMachineNo(String machineNo) {
        this.machineNo = machineNo;
    }

    
    @Column(name="EMPLOYEE_NO", nullable=false, length=10)
    public String getEmployeeNo() {
        return this.employeeNo;
    }
    
    public void setEmployeeNo(String employeeNo) {
        this.employeeNo = employeeNo;
    }




}


