package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PerAttendanceExistZkId generated by hbm2java
 */
@Embeddable
public class PerAttendanceExistZkId  implements java.io.Serializable {


     private Date attendanceDate;
     private String employeeId;
     private long attendanceSp;
     private byte transKind;

    public PerAttendanceExistZkId() {
    }

    public PerAttendanceExistZkId(Date attendanceDate, String employeeId, long attendanceSp, byte transKind) {
       this.attendanceDate = attendanceDate;
       this.employeeId = employeeId;
       this.attendanceSp = attendanceSp;
       this.transKind = transKind;
    }
   


    @Column(name="ATTENDANCE_DATE", nullable=false, length=7)
    public Date getAttendanceDate() {
        return this.attendanceDate;
    }
    
    public void setAttendanceDate(Date attendanceDate) {
        this.attendanceDate = attendanceDate;
    }


    @Column(name="EMPLOYEE_ID", nullable=false, length=10)
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }


    @Column(name="ATTENDANCE_SP", nullable=false, precision=10, scale=0)
    public long getAttendanceSp() {
        return this.attendanceSp;
    }
    
    public void setAttendanceSp(long attendanceSp) {
        this.attendanceSp = attendanceSp;
    }


    @Column(name="TRANS_KIND", nullable=false, precision=2, scale=0)
    public byte getTransKind() {
        return this.transKind;
    }
    
    public void setTransKind(byte transKind) {
        this.transKind = transKind;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PerAttendanceExistZkId) ) return false;
		 PerAttendanceExistZkId castOther = ( PerAttendanceExistZkId ) other; 
         
		 return ( (this.getAttendanceDate()==castOther.getAttendanceDate()) || ( this.getAttendanceDate()!=null && castOther.getAttendanceDate()!=null && this.getAttendanceDate().equals(castOther.getAttendanceDate()) ) )
 && ( (this.getEmployeeId()==castOther.getEmployeeId()) || ( this.getEmployeeId()!=null && castOther.getEmployeeId()!=null && this.getEmployeeId().equals(castOther.getEmployeeId()) ) )
 && (this.getAttendanceSp()==castOther.getAttendanceSp())
 && (this.getTransKind()==castOther.getTransKind());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAttendanceDate() == null ? 0 : this.getAttendanceDate().hashCode() );
         result = 37 * result + ( getEmployeeId() == null ? 0 : this.getEmployeeId().hashCode() );
         result = 37 * result + (int) this.getAttendanceSp();
         result = 37 * result + this.getTransKind();
         return result;
   }   


}


