package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PerComplaintDataId generated by hbm2java
 */
@Embeddable
public class PerComplaintDataId  implements java.io.Serializable {


     private String locationCode;
     private String complaintId;

    public PerComplaintDataId() {
    }

    public PerComplaintDataId(String locationCode, String complaintId) {
       this.locationCode = locationCode;
       this.complaintId = complaintId;
    }
   


    @Column(name="LOCATION_CODE", nullable=false, length=3)
    public String getLocationCode() {
        return this.locationCode;
    }
    
    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode;
    }


    @Column(name="COMPLAINT_ID", nullable=false, length=10)
    public String getComplaintId() {
        return this.complaintId;
    }
    
    public void setComplaintId(String complaintId) {
        this.complaintId = complaintId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PerComplaintDataId) ) return false;
		 PerComplaintDataId castOther = ( PerComplaintDataId ) other; 
         
		 return ( (this.getLocationCode()==castOther.getLocationCode()) || ( this.getLocationCode()!=null && castOther.getLocationCode()!=null && this.getLocationCode().equals(castOther.getLocationCode()) ) )
 && ( (this.getComplaintId()==castOther.getComplaintId()) || ( this.getComplaintId()!=null && castOther.getComplaintId()!=null && this.getComplaintId().equals(castOther.getComplaintId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLocationCode() == null ? 0 : this.getLocationCode().hashCode() );
         result = 37 * result + ( getComplaintId() == null ? 0 : this.getComplaintId().hashCode() );
         return result;
   }   


}


