package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerCommityMaster generated by hbm2java
 */
@Entity
@Table(name="PER_COMMITY_MASTER"
    ,schema="SHAMS"
)
public class PerCommityMaster  implements java.io.Serializable {


     private PerCommityMasterId id;
     private BudLocation budLocation;
     private PerCommTypeCode perCommTypeCode;
     private String decisionNo;
     private Date decisionDate;
     private String commityGoal;
     private String remarks;
     private Set<PerPromotionTrans> perPromotionTranses = new HashSet<PerPromotionTrans>(0);

    public PerCommityMaster() {
    }

	
    public PerCommityMaster(PerCommityMasterId id, BudLocation budLocation, PerCommTypeCode perCommTypeCode) {
        this.id = id;
        this.budLocation = budLocation;
        this.perCommTypeCode = perCommTypeCode;
    }
    public PerCommityMaster(PerCommityMasterId id, BudLocation budLocation, PerCommTypeCode perCommTypeCode, String decisionNo, Date decisionDate, String commityGoal, String remarks, Set<PerPromotionTrans> perPromotionTranses) {
       this.id = id;
       this.budLocation = budLocation;
       this.perCommTypeCode = perCommTypeCode;
       this.decisionNo = decisionNo;
       this.decisionDate = decisionDate;
       this.commityGoal = commityGoal;
       this.remarks = remarks;
       this.perPromotionTranses = perPromotionTranses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="locationCode", column=@Column(name="LOCATION_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="commityNo", column=@Column(name="COMMITY_NO", nullable=false, length=10) ) } )
    public PerCommityMasterId getId() {
        return this.id;
    }
    
    public void setId(PerCommityMasterId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="LOCATION_CODE", nullable=false, insertable=false, updatable=false)
    public BudLocation getBudLocation() {
        return this.budLocation;
    }
    
    public void setBudLocation(BudLocation budLocation) {
        this.budLocation = budLocation;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="COMM_TYPE_CODE", nullable=false)
    public PerCommTypeCode getPerCommTypeCode() {
        return this.perCommTypeCode;
    }
    
    public void setPerCommTypeCode(PerCommTypeCode perCommTypeCode) {
        this.perCommTypeCode = perCommTypeCode;
    }

    
    @Column(name="DECISION_NO", length=10)
    public String getDecisionNo() {
        return this.decisionNo;
    }
    
    public void setDecisionNo(String decisionNo) {
        this.decisionNo = decisionNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DECISION_DATE", length=7)
    public Date getDecisionDate() {
        return this.decisionDate;
    }
    
    public void setDecisionDate(Date decisionDate) {
        this.decisionDate = decisionDate;
    }

    
    @Column(name="COMMITY_GOAL", length=500)
    public String getCommityGoal() {
        return this.commityGoal;
    }
    
    public void setCommityGoal(String commityGoal) {
        this.commityGoal = commityGoal;
    }

    
    @Column(name="REMARKS", length=200)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perCommityMaster")
    public Set<PerPromotionTrans> getPerPromotionTranses() {
        return this.perPromotionTranses;
    }
    
    public void setPerPromotionTranses(Set<PerPromotionTrans> perPromotionTranses) {
        this.perPromotionTranses = perPromotionTranses;
    }




}


