package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerDecisionSheet generated by hbm2java
 */
@Entity
@Table(name="PER_DECISION_SHEET"
    ,schema="SHAMS"
)
public class PerDecisionSheet  implements java.io.Serializable {


     private PerDecisionSheetId id;
     private PerDecisionTypeCode perDecisionTypeCode;
     private PerDesicionSideCode perDesicionSideCode;
     private BudLocation budLocation;
     private String decisionNo;
     private Date decisionDate;
     private String decisionSubject;
     private String decisionSummary;
     private Set<PerEmpDecisionSheet> perEmpDecisionSheets = new HashSet<PerEmpDecisionSheet>(0);
     private Set<PerDecisionSheetImageDtl> perDecisionSheetImageDtls = new HashSet<PerDecisionSheetImageDtl>(0);

    public PerDecisionSheet() {
    }

	
    public PerDecisionSheet(PerDecisionSheetId id, PerDecisionTypeCode perDecisionTypeCode, PerDesicionSideCode perDesicionSideCode, BudLocation budLocation, String decisionNo, Date decisionDate) {
        this.id = id;
        this.perDecisionTypeCode = perDecisionTypeCode;
        this.perDesicionSideCode = perDesicionSideCode;
        this.budLocation = budLocation;
        this.decisionNo = decisionNo;
        this.decisionDate = decisionDate;
    }
    public PerDecisionSheet(PerDecisionSheetId id, PerDecisionTypeCode perDecisionTypeCode, PerDesicionSideCode perDesicionSideCode, BudLocation budLocation, String decisionNo, Date decisionDate, String decisionSubject, String decisionSummary, Set<PerEmpDecisionSheet> perEmpDecisionSheets, Set<PerDecisionSheetImageDtl> perDecisionSheetImageDtls) {
       this.id = id;
       this.perDecisionTypeCode = perDecisionTypeCode;
       this.perDesicionSideCode = perDesicionSideCode;
       this.budLocation = budLocation;
       this.decisionNo = decisionNo;
       this.decisionDate = decisionDate;
       this.decisionSubject = decisionSubject;
       this.decisionSummary = decisionSummary;
       this.perEmpDecisionSheets = perEmpDecisionSheets;
       this.perDecisionSheetImageDtls = perDecisionSheetImageDtls;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="locationCode", column=@Column(name="LOCATION_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="decisionId", column=@Column(name="DECISION_ID", nullable=false, length=10) ) } )
    public PerDecisionSheetId getId() {
        return this.id;
    }
    
    public void setId(PerDecisionSheetId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DECISION_TYPE_CODE", nullable=false)
    public PerDecisionTypeCode getPerDecisionTypeCode() {
        return this.perDecisionTypeCode;
    }
    
    public void setPerDecisionTypeCode(PerDecisionTypeCode perDecisionTypeCode) {
        this.perDecisionTypeCode = perDecisionTypeCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DESICION_SIDE_CODE", nullable=false)
    public PerDesicionSideCode getPerDesicionSideCode() {
        return this.perDesicionSideCode;
    }
    
    public void setPerDesicionSideCode(PerDesicionSideCode perDesicionSideCode) {
        this.perDesicionSideCode = perDesicionSideCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LOCATION_CODE", nullable=false, insertable=false, updatable=false)
    public BudLocation getBudLocation() {
        return this.budLocation;
    }
    
    public void setBudLocation(BudLocation budLocation) {
        this.budLocation = budLocation;
    }

    
    @Column(name="DECISION_NO", nullable=false, length=10)
    public String getDecisionNo() {
        return this.decisionNo;
    }
    
    public void setDecisionNo(String decisionNo) {
        this.decisionNo = decisionNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DECISION_DATE", nullable=false, length=7)
    public Date getDecisionDate() {
        return this.decisionDate;
    }
    
    public void setDecisionDate(Date decisionDate) {
        this.decisionDate = decisionDate;
    }

    
    @Column(name="DECISION_SUBJECT", length=4000)
    public String getDecisionSubject() {
        return this.decisionSubject;
    }
    
    public void setDecisionSubject(String decisionSubject) {
        this.decisionSubject = decisionSubject;
    }

    
    @Column(name="DECISION_SUMMARY", length=2000)
    public String getDecisionSummary() {
        return this.decisionSummary;
    }
    
    public void setDecisionSummary(String decisionSummary) {
        this.decisionSummary = decisionSummary;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perDecisionSheet")
    public Set<PerEmpDecisionSheet> getPerEmpDecisionSheets() {
        return this.perEmpDecisionSheets;
    }
    
    public void setPerEmpDecisionSheets(Set<PerEmpDecisionSheet> perEmpDecisionSheets) {
        this.perEmpDecisionSheets = perEmpDecisionSheets;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perDecisionSheet")
    public Set<PerDecisionSheetImageDtl> getPerDecisionSheetImageDtls() {
        return this.perDecisionSheetImageDtls;
    }
    
    public void setPerDecisionSheetImageDtls(Set<PerDecisionSheetImageDtl> perDecisionSheetImageDtls) {
        this.perDecisionSheetImageDtls = perDecisionSheetImageDtls;
    }




}


