package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PerDecisionSheetImageDtl generated by hbm2java
 */
@Entity
@Table(name="PER_DECISION_SHEET_IMAGE_DTL"
    ,schema="SHAMS"
)
public class PerDecisionSheetImageDtl  implements java.io.Serializable {


     private PerDecisionSheetImageDtlId id;
     private PerDecisionSheet perDecisionSheet;
     private String imageBase64;

    public PerDecisionSheetImageDtl() {
    }

    public PerDecisionSheetImageDtl(PerDecisionSheetImageDtlId id, PerDecisionSheet perDecisionSheet, String imageBase64) {
       this.id = id;
       this.perDecisionSheet = perDecisionSheet;
       this.imageBase64 = imageBase64;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="decisionId", column=@Column(name="DECISION_ID", nullable=false, length=10) ), 
        @AttributeOverride(name="locationCode", column=@Column(name="LOCATION_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="imageSp", column=@Column(name="IMAGE_SP", nullable=false, precision=10, scale=0) ) } )
    public PerDecisionSheetImageDtlId getId() {
        return this.id;
    }
    
    public void setId(PerDecisionSheetImageDtlId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="LOCATION_CODE", referencedColumnName="LOCATION_CODE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="DECISION_ID", referencedColumnName="DECISION_ID", nullable=false, insertable=false, updatable=false) } )
    public PerDecisionSheet getPerDecisionSheet() {
        return this.perDecisionSheet;
    }
    
    public void setPerDecisionSheet(PerDecisionSheet perDecisionSheet) {
        this.perDecisionSheet = perDecisionSheet;
    }

    
    @Column(name="IMAGE_BASE64", nullable=false, length=0)
    public String getImageBase64() {
        return this.imageBase64;
    }
    
    public void setImageBase64(String imageBase64) {
        this.imageBase64 = imageBase64;
    }




}


