package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PerEmpPromotionId generated by hbm2java
 */
@Embeddable
public class PerEmpPromotionId  implements java.io.Serializable {


     private String locationCode;
     private String promotionType;
     private long transId;
     private String employeeId;

    public PerEmpPromotionId() {
    }

    public PerEmpPromotionId(String locationCode, String promotionType, long transId, String employeeId) {
       this.locationCode = locationCode;
       this.promotionType = promotionType;
       this.transId = transId;
       this.employeeId = employeeId;
    }
   


    @Column(name="LOCATION_CODE", nullable=false, length=3)
    public String getLocationCode() {
        return this.locationCode;
    }
    
    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode;
    }


    @Column(name="PROMOTION_TYPE", nullable=false, length=5)
    public String getPromotionType() {
        return this.promotionType;
    }
    
    public void setPromotionType(String promotionType) {
        this.promotionType = promotionType;
    }


    @Column(name="TRANS_ID", nullable=false, precision=10, scale=0)
    public long getTransId() {
        return this.transId;
    }
    
    public void setTransId(long transId) {
        this.transId = transId;
    }


    @Column(name="EMPLOYEE_ID", nullable=false, length=10)
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PerEmpPromotionId) ) return false;
		 PerEmpPromotionId castOther = ( PerEmpPromotionId ) other; 
         
		 return ( (this.getLocationCode()==castOther.getLocationCode()) || ( this.getLocationCode()!=null && castOther.getLocationCode()!=null && this.getLocationCode().equals(castOther.getLocationCode()) ) )
 && ( (this.getPromotionType()==castOther.getPromotionType()) || ( this.getPromotionType()!=null && castOther.getPromotionType()!=null && this.getPromotionType().equals(castOther.getPromotionType()) ) )
 && (this.getTransId()==castOther.getTransId())
 && ( (this.getEmployeeId()==castOther.getEmployeeId()) || ( this.getEmployeeId()!=null && castOther.getEmployeeId()!=null && this.getEmployeeId().equals(castOther.getEmployeeId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLocationCode() == null ? 0 : this.getLocationCode().hashCode() );
         result = 37 * result + ( getPromotionType() == null ? 0 : this.getPromotionType().hashCode() );
         result = 37 * result + (int) this.getTransId();
         result = 37 * result + ( getEmployeeId() == null ? 0 : this.getEmployeeId().hashCode() );
         return result;
   }   


}


