package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerEmpVacationBalance generated by hbm2java
 */
@Entity
@Table(name="PER_EMP_VACATION_BALANCE"
    ,schema="SHAMS"
)
public class PerEmpVacationBalance  implements java.io.Serializable {


     private PerEmpVacationBalanceId id;
     private PerVacationCode perVacationCode;
     private PerEmploymentMasters perEmploymentMasters;
     private Date balEndDate;
     private Date deserveDate;
     private String decisionNo;
     private Date decisionDate;
     private BigDecimal currentBalance;
     private BigDecimal lossBalance;
     private BigDecimal previousYearBalance;
     private Date workStartDate;
     private Date contractDate;

    public PerEmpVacationBalance() {
    }

	
    public PerEmpVacationBalance(PerEmpVacationBalanceId id, PerVacationCode perVacationCode, PerEmploymentMasters perEmploymentMasters, Date balEndDate, Date deserveDate) {
        this.id = id;
        this.perVacationCode = perVacationCode;
        this.perEmploymentMasters = perEmploymentMasters;
        this.balEndDate = balEndDate;
        this.deserveDate = deserveDate;
    }
    public PerEmpVacationBalance(PerEmpVacationBalanceId id, PerVacationCode perVacationCode, PerEmploymentMasters perEmploymentMasters, Date balEndDate, Date deserveDate, String decisionNo, Date decisionDate, BigDecimal currentBalance, BigDecimal lossBalance, BigDecimal previousYearBalance, Date workStartDate, Date contractDate) {
       this.id = id;
       this.perVacationCode = perVacationCode;
       this.perEmploymentMasters = perEmploymentMasters;
       this.balEndDate = balEndDate;
       this.deserveDate = deserveDate;
       this.decisionNo = decisionNo;
       this.decisionDate = decisionDate;
       this.currentBalance = currentBalance;
       this.lossBalance = lossBalance;
       this.previousYearBalance = previousYearBalance;
       this.workStartDate = workStartDate;
       this.contractDate = contractDate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, length=10) ), 
        @AttributeOverride(name="vacationCode", column=@Column(name="VACATION_CODE", nullable=false, length=2) ), 
        @AttributeOverride(name="balStartDate", column=@Column(name="BAL_START_DATE", nullable=false, length=7) ) } )
    public PerEmpVacationBalanceId getId() {
        return this.id;
    }
    
    public void setId(PerEmpVacationBalanceId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VACATION_CODE", nullable=false, insertable=false, updatable=false)
    public PerVacationCode getPerVacationCode() {
        return this.perVacationCode;
    }
    
    public void setPerVacationCode(PerVacationCode perVacationCode) {
        this.perVacationCode = perVacationCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false)
    public PerEmploymentMasters getPerEmploymentMasters() {
        return this.perEmploymentMasters;
    }
    
    public void setPerEmploymentMasters(PerEmploymentMasters perEmploymentMasters) {
        this.perEmploymentMasters = perEmploymentMasters;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="BAL_END_DATE", nullable=false, length=7)
    public Date getBalEndDate() {
        return this.balEndDate;
    }
    
    public void setBalEndDate(Date balEndDate) {
        this.balEndDate = balEndDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DESERVE_DATE", nullable=false, length=7)
    public Date getDeserveDate() {
        return this.deserveDate;
    }
    
    public void setDeserveDate(Date deserveDate) {
        this.deserveDate = deserveDate;
    }

    
    @Column(name="DECISION_NO", length=10)
    public String getDecisionNo() {
        return this.decisionNo;
    }
    
    public void setDecisionNo(String decisionNo) {
        this.decisionNo = decisionNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DECISION_DATE", length=7)
    public Date getDecisionDate() {
        return this.decisionDate;
    }
    
    public void setDecisionDate(Date decisionDate) {
        this.decisionDate = decisionDate;
    }

    
    @Column(name="CURRENT_BALANCE", precision=7)
    public BigDecimal getCurrentBalance() {
        return this.currentBalance;
    }
    
    public void setCurrentBalance(BigDecimal currentBalance) {
        this.currentBalance = currentBalance;
    }

    
    @Column(name="LOSS_BALANCE", precision=7)
    public BigDecimal getLossBalance() {
        return this.lossBalance;
    }
    
    public void setLossBalance(BigDecimal lossBalance) {
        this.lossBalance = lossBalance;
    }

    
    @Column(name="PREVIOUS_YEAR_BALANCE", precision=7)
    public BigDecimal getPreviousYearBalance() {
        return this.previousYearBalance;
    }
    
    public void setPreviousYearBalance(BigDecimal previousYearBalance) {
        this.previousYearBalance = previousYearBalance;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="WORK_START_DATE", length=7)
    public Date getWorkStartDate() {
        return this.workStartDate;
    }
    
    public void setWorkStartDate(Date workStartDate) {
        this.workStartDate = workStartDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CONTRACT_DATE", length=7)
    public Date getContractDate() {
        return this.contractDate;
    }
    
    public void setContractDate(Date contractDate) {
        this.contractDate = contractDate;
    }




}


