package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerElawaTransactionReject generated by hbm2java
 */
@Entity
@Table(name="PER_ELAWA_TRANSACTION_REJECT"
    ,schema="SHAMS"
)
public class PerElawaTransactionReject  implements java.io.Serializable {


     private PerElawaTransactionRejectId id;
     private PerFiscalDegreeCodeNew perFiscalDegreeCodeNew;
     private PerEmploymentMasters perEmploymentMasters;
     private PerFiscalDegreeCode perFiscalDegreeCode;
     private PerGroupTypeCode perGroupTypeCode;
     private PerJobCode perJobCode;
     private String locCode;
     private Date degreeDate;
     private Date jobDate;
     private Boolean elawaCalc;
     private BigDecimal basicSalaryValueB;
     private BigDecimal salaryValueB;
     private BigDecimal elawaValue;
     private BigDecimal basicSalaryValueA;
     private BigDecimal salaryValueA;
     private BigDecimal endSalary;

    public PerElawaTransactionReject() {
    }

	
    public PerElawaTransactionReject(PerElawaTransactionRejectId id, PerEmploymentMasters perEmploymentMasters, PerJobCode perJobCode) {
        this.id = id;
        this.perEmploymentMasters = perEmploymentMasters;
        this.perJobCode = perJobCode;
    }
    public PerElawaTransactionReject(PerElawaTransactionRejectId id, PerFiscalDegreeCodeNew perFiscalDegreeCodeNew, PerEmploymentMasters perEmploymentMasters, PerFiscalDegreeCode perFiscalDegreeCode, PerGroupTypeCode perGroupTypeCode, PerJobCode perJobCode, String locCode, Date degreeDate, Date jobDate, Boolean elawaCalc, BigDecimal basicSalaryValueB, BigDecimal salaryValueB, BigDecimal elawaValue, BigDecimal basicSalaryValueA, BigDecimal salaryValueA, BigDecimal endSalary) {
       this.id = id;
       this.perFiscalDegreeCodeNew = perFiscalDegreeCodeNew;
       this.perEmploymentMasters = perEmploymentMasters;
       this.perFiscalDegreeCode = perFiscalDegreeCode;
       this.perGroupTypeCode = perGroupTypeCode;
       this.perJobCode = perJobCode;
       this.locCode = locCode;
       this.degreeDate = degreeDate;
       this.jobDate = jobDate;
       this.elawaCalc = elawaCalc;
       this.basicSalaryValueB = basicSalaryValueB;
       this.salaryValueB = salaryValueB;
       this.elawaValue = elawaValue;
       this.basicSalaryValueA = basicSalaryValueA;
       this.salaryValueA = salaryValueA;
       this.endSalary = endSalary;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="locationCode", column=@Column(name="LOCATION_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="elawaTypeCode", column=@Column(name="ELAWA_TYPE_CODE", nullable=false, length=2) ), 
        @AttributeOverride(name="elawaDate", column=@Column(name="ELAWA_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, length=10) ) } )
    public PerElawaTransactionRejectId getId() {
        return this.id;
    }
    
    public void setId(PerElawaTransactionRejectId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FISCAL_DEGREE_CODE_NEW")
    public PerFiscalDegreeCodeNew getPerFiscalDegreeCodeNew() {
        return this.perFiscalDegreeCodeNew;
    }
    
    public void setPerFiscalDegreeCodeNew(PerFiscalDegreeCodeNew perFiscalDegreeCodeNew) {
        this.perFiscalDegreeCodeNew = perFiscalDegreeCodeNew;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false)
    public PerEmploymentMasters getPerEmploymentMasters() {
        return this.perEmploymentMasters;
    }
    
    public void setPerEmploymentMasters(PerEmploymentMasters perEmploymentMasters) {
        this.perEmploymentMasters = perEmploymentMasters;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FISCAL_DEGREE_CODE")
    public PerFiscalDegreeCode getPerFiscalDegreeCode() {
        return this.perFiscalDegreeCode;
    }
    
    public void setPerFiscalDegreeCode(PerFiscalDegreeCode perFiscalDegreeCode) {
        this.perFiscalDegreeCode = perFiscalDegreeCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GROUP_TYPE_CODE")
    public PerGroupTypeCode getPerGroupTypeCode() {
        return this.perGroupTypeCode;
    }
    
    public void setPerGroupTypeCode(PerGroupTypeCode perGroupTypeCode) {
        this.perGroupTypeCode = perGroupTypeCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="JOB_CODE", nullable=false)
    public PerJobCode getPerJobCode() {
        return this.perJobCode;
    }
    
    public void setPerJobCode(PerJobCode perJobCode) {
        this.perJobCode = perJobCode;
    }

    
    @Column(name="LOC_CODE", length=3)
    public String getLocCode() {
        return this.locCode;
    }
    
    public void setLocCode(String locCode) {
        this.locCode = locCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DEGREE_DATE", length=7)
    public Date getDegreeDate() {
        return this.degreeDate;
    }
    
    public void setDegreeDate(Date degreeDate) {
        this.degreeDate = degreeDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="JOB_DATE", length=7)
    public Date getJobDate() {
        return this.jobDate;
    }
    
    public void setJobDate(Date jobDate) {
        this.jobDate = jobDate;
    }

    
    @Column(name="ELAWA_CALC", precision=1, scale=0)
    public Boolean getElawaCalc() {
        return this.elawaCalc;
    }
    
    public void setElawaCalc(Boolean elawaCalc) {
        this.elawaCalc = elawaCalc;
    }

    
    @Column(name="BASIC_SALARY_VALUE_B", precision=9)
    public BigDecimal getBasicSalaryValueB() {
        return this.basicSalaryValueB;
    }
    
    public void setBasicSalaryValueB(BigDecimal basicSalaryValueB) {
        this.basicSalaryValueB = basicSalaryValueB;
    }

    
    @Column(name="SALARY_VALUE_B", precision=9)
    public BigDecimal getSalaryValueB() {
        return this.salaryValueB;
    }
    
    public void setSalaryValueB(BigDecimal salaryValueB) {
        this.salaryValueB = salaryValueB;
    }

    
    @Column(name="ELAWA_VALUE", precision=9)
    public BigDecimal getElawaValue() {
        return this.elawaValue;
    }
    
    public void setElawaValue(BigDecimal elawaValue) {
        this.elawaValue = elawaValue;
    }

    
    @Column(name="BASIC_SALARY_VALUE_A", precision=9)
    public BigDecimal getBasicSalaryValueA() {
        return this.basicSalaryValueA;
    }
    
    public void setBasicSalaryValueA(BigDecimal basicSalaryValueA) {
        this.basicSalaryValueA = basicSalaryValueA;
    }

    
    @Column(name="SALARY_VALUE_A", precision=9)
    public BigDecimal getSalaryValueA() {
        return this.salaryValueA;
    }
    
    public void setSalaryValueA(BigDecimal salaryValueA) {
        this.salaryValueA = salaryValueA;
    }

    
    @Column(name="END_SALARY", precision=9)
    public BigDecimal getEndSalary() {
        return this.endSalary;
    }
    
    public void setEndSalary(BigDecimal endSalary) {
        this.endSalary = endSalary;
    }




}


