package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerEmploymentMastersLog generated by hbm2java
 */
@Entity
@Table(name="PER_EMPLOYMENT_MASTERS_LOG"
    ,schema="SHAMS"
)
public class PerEmploymentMastersLog  implements java.io.Serializable {


     private PerEmploymentMastersLogId id;
     private Boolean logActionName;
     private Byte logModifyTimeHh;
     private BigDecimal basicSalaryValue;
     private String generalCode;
     private BigDecimal salaryValue;
     private Date degreeDate;
     private Date workStartDate;
     private Date contractEnddate;
     private Date logModifyDate;
     private String logUserId;
     private String employmentSourceCode;
     private Date jobDate;
     private Date startContractDate;
     private String locationCode;
     private Byte logModifyTimeMm;
     private Boolean logActionStatus;
     private BigDecimal contractValue;
     private String empAname;
     private String locCode;
     private Integer degreePriority;
     private Date degreePriorityDate;
     private Date birthDate;
     private String jobCode;
     private String fiscalDegreeCode;
     private String employeeNo;
     private String logFunctionName;
     private BigDecimal jobSalaryValue;
     private Date contractDate;
     private String groupTypeCode;
     private String logIpAddress;

    public PerEmploymentMastersLog() {
    }

	
    public PerEmploymentMastersLog(PerEmploymentMastersLogId id, String empAname, String employeeNo) {
        this.id = id;
        this.empAname = empAname;
        this.employeeNo = employeeNo;
    }
    public PerEmploymentMastersLog(PerEmploymentMastersLogId id, Boolean logActionName, Byte logModifyTimeHh, BigDecimal basicSalaryValue, String generalCode, BigDecimal salaryValue, Date degreeDate, Date workStartDate, Date contractEnddate, Date logModifyDate, String logUserId, String employmentSourceCode, Date jobDate, Date startContractDate, String locationCode, Byte logModifyTimeMm, Boolean logActionStatus, BigDecimal contractValue, String empAname, String locCode, Integer degreePriority, Date degreePriorityDate, Date birthDate, String jobCode, String fiscalDegreeCode, String employeeNo, String logFunctionName, BigDecimal jobSalaryValue, Date contractDate, String groupTypeCode, String logIpAddress) {
       this.id = id;
       this.logActionName = logActionName;
       this.logModifyTimeHh = logModifyTimeHh;
       this.basicSalaryValue = basicSalaryValue;
       this.generalCode = generalCode;
       this.salaryValue = salaryValue;
       this.degreeDate = degreeDate;
       this.workStartDate = workStartDate;
       this.contractEnddate = contractEnddate;
       this.logModifyDate = logModifyDate;
       this.logUserId = logUserId;
       this.employmentSourceCode = employmentSourceCode;
       this.jobDate = jobDate;
       this.startContractDate = startContractDate;
       this.locationCode = locationCode;
       this.logModifyTimeMm = logModifyTimeMm;
       this.logActionStatus = logActionStatus;
       this.contractValue = contractValue;
       this.empAname = empAname;
       this.locCode = locCode;
       this.degreePriority = degreePriority;
       this.degreePriorityDate = degreePriorityDate;
       this.birthDate = birthDate;
       this.jobCode = jobCode;
       this.fiscalDegreeCode = fiscalDegreeCode;
       this.employeeNo = employeeNo;
       this.logFunctionName = logFunctionName;
       this.jobSalaryValue = jobSalaryValue;
       this.contractDate = contractDate;
       this.groupTypeCode = groupTypeCode;
       this.logIpAddress = logIpAddress;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, length=10) ), 
        @AttributeOverride(name="employeeSeq", column=@Column(name="EMPLOYEE_SEQ", nullable=false, length=5) ) } )
    public PerEmploymentMastersLogId getId() {
        return this.id;
    }
    
    public void setId(PerEmploymentMastersLogId id) {
        this.id = id;
    }

    
    @Column(name="LOG_ACTION_NAME", precision=1, scale=0)
    public Boolean getLogActionName() {
        return this.logActionName;
    }
    
    public void setLogActionName(Boolean logActionName) {
        this.logActionName = logActionName;
    }

    
    @Column(name="LOG_MODIFY_TIME_HH", precision=2, scale=0)
    public Byte getLogModifyTimeHh() {
        return this.logModifyTimeHh;
    }
    
    public void setLogModifyTimeHh(Byte logModifyTimeHh) {
        this.logModifyTimeHh = logModifyTimeHh;
    }

    
    @Column(name="BASIC_SALARY_VALUE", precision=9)
    public BigDecimal getBasicSalaryValue() {
        return this.basicSalaryValue;
    }
    
    public void setBasicSalaryValue(BigDecimal basicSalaryValue) {
        this.basicSalaryValue = basicSalaryValue;
    }

    
    @Column(name="GENERAL_CODE", length=3)
    public String getGeneralCode() {
        return this.generalCode;
    }
    
    public void setGeneralCode(String generalCode) {
        this.generalCode = generalCode;
    }

    
    @Column(name="SALARY_VALUE", precision=9)
    public BigDecimal getSalaryValue() {
        return this.salaryValue;
    }
    
    public void setSalaryValue(BigDecimal salaryValue) {
        this.salaryValue = salaryValue;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DEGREE_DATE", length=7)
    public Date getDegreeDate() {
        return this.degreeDate;
    }
    
    public void setDegreeDate(Date degreeDate) {
        this.degreeDate = degreeDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="WORK_START_DATE", length=7)
    public Date getWorkStartDate() {
        return this.workStartDate;
    }
    
    public void setWorkStartDate(Date workStartDate) {
        this.workStartDate = workStartDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CONTRACT_ENDDATE", length=7)
    public Date getContractEnddate() {
        return this.contractEnddate;
    }
    
    public void setContractEnddate(Date contractEnddate) {
        this.contractEnddate = contractEnddate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="LOG_MODIFY_DATE", length=7)
    public Date getLogModifyDate() {
        return this.logModifyDate;
    }
    
    public void setLogModifyDate(Date logModifyDate) {
        this.logModifyDate = logModifyDate;
    }

    
    @Column(name="LOG_USER_ID", length=15)
    public String getLogUserId() {
        return this.logUserId;
    }
    
    public void setLogUserId(String logUserId) {
        this.logUserId = logUserId;
    }

    
    @Column(name="EMPLOYMENT_SOURCE_CODE", length=3)
    public String getEmploymentSourceCode() {
        return this.employmentSourceCode;
    }
    
    public void setEmploymentSourceCode(String employmentSourceCode) {
        this.employmentSourceCode = employmentSourceCode;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="JOB_DATE", length=7)
    public Date getJobDate() {
        return this.jobDate;
    }
    
    public void setJobDate(Date jobDate) {
        this.jobDate = jobDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="START_CONTRACT_DATE", length=7)
    public Date getStartContractDate() {
        return this.startContractDate;
    }
    
    public void setStartContractDate(Date startContractDate) {
        this.startContractDate = startContractDate;
    }

    
    @Column(name="LOCATION_CODE", length=3)
    public String getLocationCode() {
        return this.locationCode;
    }
    
    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode;
    }

    
    @Column(name="LOG_MODIFY_TIME_MM", precision=2, scale=0)
    public Byte getLogModifyTimeMm() {
        return this.logModifyTimeMm;
    }
    
    public void setLogModifyTimeMm(Byte logModifyTimeMm) {
        this.logModifyTimeMm = logModifyTimeMm;
    }

    
    @Column(name="LOG_ACTION_STATUS", precision=1, scale=0)
    public Boolean getLogActionStatus() {
        return this.logActionStatus;
    }
    
    public void setLogActionStatus(Boolean logActionStatus) {
        this.logActionStatus = logActionStatus;
    }

    
    @Column(name="CONTRACT_VALUE", precision=9)
    public BigDecimal getContractValue() {
        return this.contractValue;
    }
    
    public void setContractValue(BigDecimal contractValue) {
        this.contractValue = contractValue;
    }

    
    @Column(name="EMP_ANAME", nullable=false, length=75)
    public String getEmpAname() {
        return this.empAname;
    }
    
    public void setEmpAname(String empAname) {
        this.empAname = empAname;
    }

    
    @Column(name="LOC_CODE", length=3)
    public String getLocCode() {
        return this.locCode;
    }
    
    public void setLocCode(String locCode) {
        this.locCode = locCode;
    }

    
    @Column(name="DEGREE_PRIORITY", precision=5, scale=0)
    public Integer getDegreePriority() {
        return this.degreePriority;
    }
    
    public void setDegreePriority(Integer degreePriority) {
        this.degreePriority = degreePriority;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DEGREE_PRIORITY_DATE", length=7)
    public Date getDegreePriorityDate() {
        return this.degreePriorityDate;
    }
    
    public void setDegreePriorityDate(Date degreePriorityDate) {
        this.degreePriorityDate = degreePriorityDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="BIRTH_DATE", length=7)
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    
    @Column(name="JOB_CODE", length=5)
    public String getJobCode() {
        return this.jobCode;
    }
    
    public void setJobCode(String jobCode) {
        this.jobCode = jobCode;
    }

    
    @Column(name="FISCAL_DEGREE_CODE", length=3)
    public String getFiscalDegreeCode() {
        return this.fiscalDegreeCode;
    }
    
    public void setFiscalDegreeCode(String fiscalDegreeCode) {
        this.fiscalDegreeCode = fiscalDegreeCode;
    }

    
    @Column(name="EMPLOYEE_NO", nullable=false, length=10)
    public String getEmployeeNo() {
        return this.employeeNo;
    }
    
    public void setEmployeeNo(String employeeNo) {
        this.employeeNo = employeeNo;
    }

    
    @Column(name="LOG_FUNCTION_NAME", length=25)
    public String getLogFunctionName() {
        return this.logFunctionName;
    }
    
    public void setLogFunctionName(String logFunctionName) {
        this.logFunctionName = logFunctionName;
    }

    
    @Column(name="JOB_SALARY_VALUE", precision=9)
    public BigDecimal getJobSalaryValue() {
        return this.jobSalaryValue;
    }
    
    public void setJobSalaryValue(BigDecimal jobSalaryValue) {
        this.jobSalaryValue = jobSalaryValue;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CONTRACT_DATE", length=7)
    public Date getContractDate() {
        return this.contractDate;
    }
    
    public void setContractDate(Date contractDate) {
        this.contractDate = contractDate;
    }

    
    @Column(name="GROUP_TYPE_CODE", length=3)
    public String getGroupTypeCode() {
        return this.groupTypeCode;
    }
    
    public void setGroupTypeCode(String groupTypeCode) {
        this.groupTypeCode = groupTypeCode;
    }

    
    @Column(name="LOG_IP_ADDRESS", length=25)
    public String getLogIpAddress() {
        return this.logIpAddress;
    }
    
    public void setLogIpAddress(String logIpAddress) {
        this.logIpAddress = logIpAddress;
    }




}


