package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerEvalPercentage generated by hbm2java
 */
@Entity
@Table(name="PER_EVAL_PERCENTAGE"
    ,schema="SHAMS"
)
public class PerEvalPercentage  implements java.io.Serializable {


     private String gradeCode;
     private String gradeName;
     private BigDecimal percentageFrom;
     private BigDecimal percentageTo;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private String gradeName81;
     private Set<PerAnnualEvalModelEmp> perAnnualEvalModelEmpsForGradeCodeDirectboss = new HashSet<PerAnnualEvalModelEmp>(0);
     private Set<PerAnnualEvalEmp> perAnnualEvalEmpsForGradeCodeBigboss = new HashSet<PerAnnualEvalEmp>(0);
     private Set<PerAnnualEvalEmpDetail> perAnnualEvalEmpDetailsForGradeCodeComm = new HashSet<PerAnnualEvalEmpDetail>(0);
     private Set<PerAnnualEvalModelEmp> perAnnualEvalModelEmpsForGradeCodeFinal = new HashSet<PerAnnualEvalModelEmp>(0);
     private Set<PerAnnualEvalEmp> perAnnualEvalEmpsForGradeCode = new HashSet<PerAnnualEvalEmp>(0);
     private Set<PerAnnualEvalEmpDetail> perAnnualEvalEmpDetailsForGradeCode = new HashSet<PerAnnualEvalEmpDetail>(0);
     private Set<PerAnnualEvalEmpDetail> perAnnualEvalEmpDetailsForGradeCodeBigboss = new HashSet<PerAnnualEvalEmpDetail>(0);
     private Set<PerPromotionGradeRuleN> perPromotionGradeRuleNs = new HashSet<PerPromotionGradeRuleN>(0);
     private Set<PerAnnualEvalModelEmpDtl> perAnnualEvalModelEmpDtlsForGradeCodeDirectboss = new HashSet<PerAnnualEvalModelEmpDtl>(0);
     private Set<PerAnnualEvalModelEmp> perAnnualEvalModelEmpsForGradeCode = new HashSet<PerAnnualEvalModelEmp>(0);
     private Set<PerAnnualEvalEmp> perAnnualEvalEmpsForGradeCodeFinal = new HashSet<PerAnnualEvalEmp>(0);
     private Set<PerAnnualEvalModelEmpDtl> perAnnualEvalModelEmpDtlsForGradeCodeBigboss = new HashSet<PerAnnualEvalModelEmpDtl>(0);
     private Set<PerAnnualEvalModelEmp> perAnnualEvalModelEmpsForGradeCodeComm = new HashSet<PerAnnualEvalModelEmp>(0);
     private Set<PerElawaGradeRule> perElawaGradeRules = new HashSet<PerElawaGradeRule>(0);
     private Set<PerAnnualEvalEmp> perAnnualEvalEmpsForGradeCodeComm = new HashSet<PerAnnualEvalEmp>(0);
     private Set<PerAnnualEvalModelEmpDtl> perAnnualEvalModelEmpDtlsForGradeCode = new HashSet<PerAnnualEvalModelEmpDtl>(0);

    public PerEvalPercentage() {
    }

	
    public PerEvalPercentage(String gradeCode, String gradeName, BigDecimal percentageFrom, BigDecimal percentageTo) {
        this.gradeCode = gradeCode;
        this.gradeName = gradeName;
        this.percentageFrom = percentageFrom;
        this.percentageTo = percentageTo;
    }
    public PerEvalPercentage(String gradeCode, String gradeName, BigDecimal percentageFrom, BigDecimal percentageTo, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, String gradeName81, Set<PerAnnualEvalModelEmp> perAnnualEvalModelEmpsForGradeCodeDirectboss, Set<PerAnnualEvalEmp> perAnnualEvalEmpsForGradeCodeBigboss, Set<PerAnnualEvalEmpDetail> perAnnualEvalEmpDetailsForGradeCodeComm, Set<PerAnnualEvalModelEmp> perAnnualEvalModelEmpsForGradeCodeFinal, Set<PerAnnualEvalEmp> perAnnualEvalEmpsForGradeCode, Set<PerAnnualEvalEmpDetail> perAnnualEvalEmpDetailsForGradeCode, Set<PerAnnualEvalEmpDetail> perAnnualEvalEmpDetailsForGradeCodeBigboss, Set<PerPromotionGradeRuleN> perPromotionGradeRuleNs, Set<PerAnnualEvalModelEmpDtl> perAnnualEvalModelEmpDtlsForGradeCodeDirectboss, Set<PerAnnualEvalModelEmp> perAnnualEvalModelEmpsForGradeCode, Set<PerAnnualEvalEmp> perAnnualEvalEmpsForGradeCodeFinal, Set<PerAnnualEvalModelEmpDtl> perAnnualEvalModelEmpDtlsForGradeCodeBigboss, Set<PerAnnualEvalModelEmp> perAnnualEvalModelEmpsForGradeCodeComm, Set<PerElawaGradeRule> perElawaGradeRules, Set<PerAnnualEvalEmp> perAnnualEvalEmpsForGradeCodeComm, Set<PerAnnualEvalModelEmpDtl> perAnnualEvalModelEmpDtlsForGradeCode) {
       this.gradeCode = gradeCode;
       this.gradeName = gradeName;
       this.percentageFrom = percentageFrom;
       this.percentageTo = percentageTo;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.gradeName81 = gradeName81;
       this.perAnnualEvalModelEmpsForGradeCodeDirectboss = perAnnualEvalModelEmpsForGradeCodeDirectboss;
       this.perAnnualEvalEmpsForGradeCodeBigboss = perAnnualEvalEmpsForGradeCodeBigboss;
       this.perAnnualEvalEmpDetailsForGradeCodeComm = perAnnualEvalEmpDetailsForGradeCodeComm;
       this.perAnnualEvalModelEmpsForGradeCodeFinal = perAnnualEvalModelEmpsForGradeCodeFinal;
       this.perAnnualEvalEmpsForGradeCode = perAnnualEvalEmpsForGradeCode;
       this.perAnnualEvalEmpDetailsForGradeCode = perAnnualEvalEmpDetailsForGradeCode;
       this.perAnnualEvalEmpDetailsForGradeCodeBigboss = perAnnualEvalEmpDetailsForGradeCodeBigboss;
       this.perPromotionGradeRuleNs = perPromotionGradeRuleNs;
       this.perAnnualEvalModelEmpDtlsForGradeCodeDirectboss = perAnnualEvalModelEmpDtlsForGradeCodeDirectboss;
       this.perAnnualEvalModelEmpsForGradeCode = perAnnualEvalModelEmpsForGradeCode;
       this.perAnnualEvalEmpsForGradeCodeFinal = perAnnualEvalEmpsForGradeCodeFinal;
       this.perAnnualEvalModelEmpDtlsForGradeCodeBigboss = perAnnualEvalModelEmpDtlsForGradeCodeBigboss;
       this.perAnnualEvalModelEmpsForGradeCodeComm = perAnnualEvalModelEmpsForGradeCodeComm;
       this.perElawaGradeRules = perElawaGradeRules;
       this.perAnnualEvalEmpsForGradeCodeComm = perAnnualEvalEmpsForGradeCodeComm;
       this.perAnnualEvalModelEmpDtlsForGradeCode = perAnnualEvalModelEmpDtlsForGradeCode;
    }
   
     @Id 

    
    @Column(name="GRADE_CODE", unique=true, nullable=false, length=2)
    public String getGradeCode() {
        return this.gradeCode;
    }
    
    public void setGradeCode(String gradeCode) {
        this.gradeCode = gradeCode;
    }

    
    @Column(name="GRADE_NAME", nullable=false, length=25)
    public String getGradeName() {
        return this.gradeName;
    }
    
    public void setGradeName(String gradeName) {
        this.gradeName = gradeName;
    }

    
    @Column(name="PERCENTAGE_FROM", nullable=false, precision=5)
    public BigDecimal getPercentageFrom() {
        return this.percentageFrom;
    }
    
    public void setPercentageFrom(BigDecimal percentageFrom) {
        this.percentageFrom = percentageFrom;
    }

    
    @Column(name="PERCENTAGE_TO", nullable=false, precision=5)
    public BigDecimal getPercentageTo() {
        return this.percentageTo;
    }
    
    public void setPercentageTo(BigDecimal percentageTo) {
        this.percentageTo = percentageTo;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

    
    @Column(name="GRADE_NAME_81", length=25)
    public String getGradeName81() {
        return this.gradeName81;
    }
    
    public void setGradeName81(String gradeName81) {
        this.gradeName81 = gradeName81;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEvalPercentageByGradeCodeDirectboss")
    public Set<PerAnnualEvalModelEmp> getPerAnnualEvalModelEmpsForGradeCodeDirectboss() {
        return this.perAnnualEvalModelEmpsForGradeCodeDirectboss;
    }
    
    public void setPerAnnualEvalModelEmpsForGradeCodeDirectboss(Set<PerAnnualEvalModelEmp> perAnnualEvalModelEmpsForGradeCodeDirectboss) {
        this.perAnnualEvalModelEmpsForGradeCodeDirectboss = perAnnualEvalModelEmpsForGradeCodeDirectboss;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEvalPercentageByGradeCodeBigboss")
    public Set<PerAnnualEvalEmp> getPerAnnualEvalEmpsForGradeCodeBigboss() {
        return this.perAnnualEvalEmpsForGradeCodeBigboss;
    }
    
    public void setPerAnnualEvalEmpsForGradeCodeBigboss(Set<PerAnnualEvalEmp> perAnnualEvalEmpsForGradeCodeBigboss) {
        this.perAnnualEvalEmpsForGradeCodeBigboss = perAnnualEvalEmpsForGradeCodeBigboss;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEvalPercentageByGradeCodeComm")
    public Set<PerAnnualEvalEmpDetail> getPerAnnualEvalEmpDetailsForGradeCodeComm() {
        return this.perAnnualEvalEmpDetailsForGradeCodeComm;
    }
    
    public void setPerAnnualEvalEmpDetailsForGradeCodeComm(Set<PerAnnualEvalEmpDetail> perAnnualEvalEmpDetailsForGradeCodeComm) {
        this.perAnnualEvalEmpDetailsForGradeCodeComm = perAnnualEvalEmpDetailsForGradeCodeComm;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEvalPercentageByGradeCodeFinal")
    public Set<PerAnnualEvalModelEmp> getPerAnnualEvalModelEmpsForGradeCodeFinal() {
        return this.perAnnualEvalModelEmpsForGradeCodeFinal;
    }
    
    public void setPerAnnualEvalModelEmpsForGradeCodeFinal(Set<PerAnnualEvalModelEmp> perAnnualEvalModelEmpsForGradeCodeFinal) {
        this.perAnnualEvalModelEmpsForGradeCodeFinal = perAnnualEvalModelEmpsForGradeCodeFinal;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEvalPercentageByGradeCode")
    public Set<PerAnnualEvalEmp> getPerAnnualEvalEmpsForGradeCode() {
        return this.perAnnualEvalEmpsForGradeCode;
    }
    
    public void setPerAnnualEvalEmpsForGradeCode(Set<PerAnnualEvalEmp> perAnnualEvalEmpsForGradeCode) {
        this.perAnnualEvalEmpsForGradeCode = perAnnualEvalEmpsForGradeCode;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEvalPercentageByGradeCode")
    public Set<PerAnnualEvalEmpDetail> getPerAnnualEvalEmpDetailsForGradeCode() {
        return this.perAnnualEvalEmpDetailsForGradeCode;
    }
    
    public void setPerAnnualEvalEmpDetailsForGradeCode(Set<PerAnnualEvalEmpDetail> perAnnualEvalEmpDetailsForGradeCode) {
        this.perAnnualEvalEmpDetailsForGradeCode = perAnnualEvalEmpDetailsForGradeCode;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEvalPercentageByGradeCodeBigboss")
    public Set<PerAnnualEvalEmpDetail> getPerAnnualEvalEmpDetailsForGradeCodeBigboss() {
        return this.perAnnualEvalEmpDetailsForGradeCodeBigboss;
    }
    
    public void setPerAnnualEvalEmpDetailsForGradeCodeBigboss(Set<PerAnnualEvalEmpDetail> perAnnualEvalEmpDetailsForGradeCodeBigboss) {
        this.perAnnualEvalEmpDetailsForGradeCodeBigboss = perAnnualEvalEmpDetailsForGradeCodeBigboss;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEvalPercentage")
    public Set<PerPromotionGradeRuleN> getPerPromotionGradeRuleNs() {
        return this.perPromotionGradeRuleNs;
    }
    
    public void setPerPromotionGradeRuleNs(Set<PerPromotionGradeRuleN> perPromotionGradeRuleNs) {
        this.perPromotionGradeRuleNs = perPromotionGradeRuleNs;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEvalPercentageByGradeCodeDirectboss")
    public Set<PerAnnualEvalModelEmpDtl> getPerAnnualEvalModelEmpDtlsForGradeCodeDirectboss() {
        return this.perAnnualEvalModelEmpDtlsForGradeCodeDirectboss;
    }
    
    public void setPerAnnualEvalModelEmpDtlsForGradeCodeDirectboss(Set<PerAnnualEvalModelEmpDtl> perAnnualEvalModelEmpDtlsForGradeCodeDirectboss) {
        this.perAnnualEvalModelEmpDtlsForGradeCodeDirectboss = perAnnualEvalModelEmpDtlsForGradeCodeDirectboss;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEvalPercentageByGradeCode")
    public Set<PerAnnualEvalModelEmp> getPerAnnualEvalModelEmpsForGradeCode() {
        return this.perAnnualEvalModelEmpsForGradeCode;
    }
    
    public void setPerAnnualEvalModelEmpsForGradeCode(Set<PerAnnualEvalModelEmp> perAnnualEvalModelEmpsForGradeCode) {
        this.perAnnualEvalModelEmpsForGradeCode = perAnnualEvalModelEmpsForGradeCode;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEvalPercentageByGradeCodeFinal")
    public Set<PerAnnualEvalEmp> getPerAnnualEvalEmpsForGradeCodeFinal() {
        return this.perAnnualEvalEmpsForGradeCodeFinal;
    }
    
    public void setPerAnnualEvalEmpsForGradeCodeFinal(Set<PerAnnualEvalEmp> perAnnualEvalEmpsForGradeCodeFinal) {
        this.perAnnualEvalEmpsForGradeCodeFinal = perAnnualEvalEmpsForGradeCodeFinal;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEvalPercentageByGradeCodeBigboss")
    public Set<PerAnnualEvalModelEmpDtl> getPerAnnualEvalModelEmpDtlsForGradeCodeBigboss() {
        return this.perAnnualEvalModelEmpDtlsForGradeCodeBigboss;
    }
    
    public void setPerAnnualEvalModelEmpDtlsForGradeCodeBigboss(Set<PerAnnualEvalModelEmpDtl> perAnnualEvalModelEmpDtlsForGradeCodeBigboss) {
        this.perAnnualEvalModelEmpDtlsForGradeCodeBigboss = perAnnualEvalModelEmpDtlsForGradeCodeBigboss;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEvalPercentageByGradeCodeComm")
    public Set<PerAnnualEvalModelEmp> getPerAnnualEvalModelEmpsForGradeCodeComm() {
        return this.perAnnualEvalModelEmpsForGradeCodeComm;
    }
    
    public void setPerAnnualEvalModelEmpsForGradeCodeComm(Set<PerAnnualEvalModelEmp> perAnnualEvalModelEmpsForGradeCodeComm) {
        this.perAnnualEvalModelEmpsForGradeCodeComm = perAnnualEvalModelEmpsForGradeCodeComm;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEvalPercentage")
    public Set<PerElawaGradeRule> getPerElawaGradeRules() {
        return this.perElawaGradeRules;
    }
    
    public void setPerElawaGradeRules(Set<PerElawaGradeRule> perElawaGradeRules) {
        this.perElawaGradeRules = perElawaGradeRules;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEvalPercentageByGradeCodeComm")
    public Set<PerAnnualEvalEmp> getPerAnnualEvalEmpsForGradeCodeComm() {
        return this.perAnnualEvalEmpsForGradeCodeComm;
    }
    
    public void setPerAnnualEvalEmpsForGradeCodeComm(Set<PerAnnualEvalEmp> perAnnualEvalEmpsForGradeCodeComm) {
        this.perAnnualEvalEmpsForGradeCodeComm = perAnnualEvalEmpsForGradeCodeComm;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEvalPercentageByGradeCode")
    public Set<PerAnnualEvalModelEmpDtl> getPerAnnualEvalModelEmpDtlsForGradeCode() {
        return this.perAnnualEvalModelEmpDtlsForGradeCode;
    }
    
    public void setPerAnnualEvalModelEmpDtlsForGradeCode(Set<PerAnnualEvalModelEmpDtl> perAnnualEvalModelEmpDtlsForGradeCode) {
        this.perAnnualEvalModelEmpDtlsForGradeCode = perAnnualEvalModelEmpDtlsForGradeCode;
    }




}


