package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PerEmpFile generated by hbm2java
 */
@Entity
@Table(name="PER_EMP_FILE"
    ,schema="SHAMS"
)
public class PerEmpFile  implements java.io.Serializable {


     private PerEmpFileId id;
     private PerFileDocType perFileDocType;
     private PerFileType perFileType;
     private PerEmploymentMasters perEmploymentMasters;
     private Set<PerEmpFileDoc> perEmpFileDocs = new HashSet<PerEmpFileDoc>(0);

    public PerEmpFile() {
    }

	
    public PerEmpFile(PerEmpFileId id, PerFileDocType perFileDocType, PerFileType perFileType, PerEmploymentMasters perEmploymentMasters) {
        this.id = id;
        this.perFileDocType = perFileDocType;
        this.perFileType = perFileType;
        this.perEmploymentMasters = perEmploymentMasters;
    }
    public PerEmpFile(PerEmpFileId id, PerFileDocType perFileDocType, PerFileType perFileType, PerEmploymentMasters perEmploymentMasters, Set<PerEmpFileDoc> perEmpFileDocs) {
       this.id = id;
       this.perFileDocType = perFileDocType;
       this.perFileType = perFileType;
       this.perEmploymentMasters = perEmploymentMasters;
       this.perEmpFileDocs = perEmpFileDocs;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, length=10) ), 
        @AttributeOverride(name="fileSerial", column=@Column(name="FILE_SERIAL", nullable=false, length=2) ) } )
    public PerEmpFileId getId() {
        return this.id;
    }
    
    public void setId(PerEmpFileId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="DOC_TYPE_CODE", nullable=false)
    public PerFileDocType getPerFileDocType() {
        return this.perFileDocType;
    }
    
    public void setPerFileDocType(PerFileDocType perFileDocType) {
        this.perFileDocType = perFileDocType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="FILE_TYPE_CODE", nullable=false)
    public PerFileType getPerFileType() {
        return this.perFileType;
    }
    
    public void setPerFileType(PerFileType perFileType) {
        this.perFileType = perFileType;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false)
    public PerEmploymentMasters getPerEmploymentMasters() {
        return this.perEmploymentMasters;
    }
    
    public void setPerEmploymentMasters(PerEmploymentMasters perEmploymentMasters) {
        this.perEmploymentMasters = perEmploymentMasters;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmpFile")
    public Set<PerEmpFileDoc> getPerEmpFileDocs() {
        return this.perEmpFileDocs;
    }
    
    public void setPerEmpFileDocs(Set<PerEmpFileDoc> perEmpFileDocs) {
        this.perEmpFileDocs = perEmpFileDocs;
    }




}


