package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerEmpPromotionRejectNew generated by hbm2java
 */
@Entity
@Table(name="PER_EMP_PROMOTION_REJECT_NEW"
    ,schema="SHAMS"
)
public class PerEmpPromotionRejectNew  implements java.io.Serializable {


     private PerEmpPromotionRejectNewId id;
     private PerFiscalDegreeCodeNew perFiscalDegreeCodeNew;
     private PerGroupTypeCode perGroupTypeCode;
     private PerJobCode perJobCode;
     private PerPromotionTransNew perPromotionTransNew;
     private PerEmploymentMasters perEmploymentMasters;
     private String rejectReason;
     private Date jobDate;
     private Date degreePriorityDate;
     private Date degreeDate;

    public PerEmpPromotionRejectNew() {
    }

	
    public PerEmpPromotionRejectNew(PerEmpPromotionRejectNewId id, PerFiscalDegreeCodeNew perFiscalDegreeCodeNew, PerJobCode perJobCode, PerPromotionTransNew perPromotionTransNew, PerEmploymentMasters perEmploymentMasters) {
        this.id = id;
        this.perFiscalDegreeCodeNew = perFiscalDegreeCodeNew;
        this.perJobCode = perJobCode;
        this.perPromotionTransNew = perPromotionTransNew;
        this.perEmploymentMasters = perEmploymentMasters;
    }
    public PerEmpPromotionRejectNew(PerEmpPromotionRejectNewId id, PerFiscalDegreeCodeNew perFiscalDegreeCodeNew, PerGroupTypeCode perGroupTypeCode, PerJobCode perJobCode, PerPromotionTransNew perPromotionTransNew, PerEmploymentMasters perEmploymentMasters, String rejectReason, Date jobDate, Date degreePriorityDate, Date degreeDate) {
       this.id = id;
       this.perFiscalDegreeCodeNew = perFiscalDegreeCodeNew;
       this.perGroupTypeCode = perGroupTypeCode;
       this.perJobCode = perJobCode;
       this.perPromotionTransNew = perPromotionTransNew;
       this.perEmploymentMasters = perEmploymentMasters;
       this.rejectReason = rejectReason;
       this.jobDate = jobDate;
       this.degreePriorityDate = degreePriorityDate;
       this.degreeDate = degreeDate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="transId", column=@Column(name="TRANS_ID", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="locationCode", column=@Column(name="LOCATION_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="promotionType", column=@Column(name="PROMOTION_TYPE", nullable=false, length=5) ), 
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, length=10) ) } )
    public PerEmpPromotionRejectNewId getId() {
        return this.id;
    }
    
    public void setId(PerEmpPromotionRejectNewId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="FISCAL_DEGREE_CODE_NEW", nullable=false)
    public PerFiscalDegreeCodeNew getPerFiscalDegreeCodeNew() {
        return this.perFiscalDegreeCodeNew;
    }
    
    public void setPerFiscalDegreeCodeNew(PerFiscalDegreeCodeNew perFiscalDegreeCodeNew) {
        this.perFiscalDegreeCodeNew = perFiscalDegreeCodeNew;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="GROUP_TYPE_CODE")
    public PerGroupTypeCode getPerGroupTypeCode() {
        return this.perGroupTypeCode;
    }
    
    public void setPerGroupTypeCode(PerGroupTypeCode perGroupTypeCode) {
        this.perGroupTypeCode = perGroupTypeCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="JOB_CODE", nullable=false)
    public PerJobCode getPerJobCode() {
        return this.perJobCode;
    }
    
    public void setPerJobCode(PerJobCode perJobCode) {
        this.perJobCode = perJobCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="LOCATION_CODE", referencedColumnName="LOCATION_CODE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="PROMOTION_TYPE", referencedColumnName="PROMOTION_TYPE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="TRANS_ID", referencedColumnName="TRANS_ID", nullable=false, insertable=false, updatable=false) } )
    public PerPromotionTransNew getPerPromotionTransNew() {
        return this.perPromotionTransNew;
    }
    
    public void setPerPromotionTransNew(PerPromotionTransNew perPromotionTransNew) {
        this.perPromotionTransNew = perPromotionTransNew;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false)
    public PerEmploymentMasters getPerEmploymentMasters() {
        return this.perEmploymentMasters;
    }
    
    public void setPerEmploymentMasters(PerEmploymentMasters perEmploymentMasters) {
        this.perEmploymentMasters = perEmploymentMasters;
    }

    
    @Column(name="REJECT_REASON", length=250)
    public String getRejectReason() {
        return this.rejectReason;
    }
    
    public void setRejectReason(String rejectReason) {
        this.rejectReason = rejectReason;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="JOB_DATE", length=7)
    public Date getJobDate() {
        return this.jobDate;
    }
    
    public void setJobDate(Date jobDate) {
        this.jobDate = jobDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DEGREE_PRIORITY_DATE", length=7)
    public Date getDegreePriorityDate() {
        return this.degreePriorityDate;
    }
    
    public void setDegreePriorityDate(Date degreePriorityDate) {
        this.degreePriorityDate = degreePriorityDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DEGREE_DATE", length=7)
    public Date getDegreeDate() {
        return this.degreeDate;
    }
    
    public void setDegreeDate(Date degreeDate) {
        this.degreeDate = degreeDate;
    }




}


