package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerEmpVacationTrans generated by hbm2java
 */
@Entity
@Table(name="PER_EMP_VACATION_TRANS"
    ,schema="SHAMS"
)
public class PerEmpVacationTrans  implements java.io.Serializable {


     private PerEmpVacationTransId id;
     private PerVacationCode perVacationCode;
     private PerEmploymentMasters perEmploymentMasters;
     private Date vacStartDate;
     private Date vacEndDate;
     private Date vacEndDateActual;
     private Boolean directBossAprove;
     private Boolean bigBossAprove;
     private Byte spcPeriodDay;
     private Byte spcPeriodMn;
     private Byte spcPeriodYr;
     private Boolean vacBalType;
     private String decisionNo;
     private Date decisionDate;
     private String decisionNotes;
     private Date returnDate;
     private Date postDate;
     private String vacNote;
     private BigDecimal period;
     private BigDecimal balBeforeVac;
     private BigDecimal balRemaining;
     private Boolean vacPunType;
     private String militaryCardNo;
     private Boolean fridayFlg;
     private Boolean saturdayFlg;
     private Boolean sundayFlg;
     private Boolean mondayFlg;
     private Boolean tuesdayFlg;
     private Boolean wednesdayFlg;
     private Boolean thursdayFlg;
     private String remarks;
     private String bigBossReason;
     private Date bigBossDate;
     private String bigBossNo;
     private String directBossReason;
     private Date directBossDate;
     private String directBossNo;
     private Set<PerEmpVacationAdjstmnt> perEmpVacationAdjstmnts = new HashSet<PerEmpVacationAdjstmnt>(0);

    public PerEmpVacationTrans() {
    }

	
    public PerEmpVacationTrans(PerEmpVacationTransId id, PerVacationCode perVacationCode, PerEmploymentMasters perEmploymentMasters) {
        this.id = id;
        this.perVacationCode = perVacationCode;
        this.perEmploymentMasters = perEmploymentMasters;
    }
    public PerEmpVacationTrans(PerEmpVacationTransId id, PerVacationCode perVacationCode, PerEmploymentMasters perEmploymentMasters, Date vacStartDate, Date vacEndDate, Date vacEndDateActual, Boolean directBossAprove, Boolean bigBossAprove, Byte spcPeriodDay, Byte spcPeriodMn, Byte spcPeriodYr, Boolean vacBalType, String decisionNo, Date decisionDate, String decisionNotes, Date returnDate, Date postDate, String vacNote, BigDecimal period, BigDecimal balBeforeVac, BigDecimal balRemaining, Boolean vacPunType, String militaryCardNo, Boolean fridayFlg, Boolean saturdayFlg, Boolean sundayFlg, Boolean mondayFlg, Boolean tuesdayFlg, Boolean wednesdayFlg, Boolean thursdayFlg, String remarks, String bigBossReason, Date bigBossDate, String bigBossNo, String directBossReason, Date directBossDate, String directBossNo, Set<PerEmpVacationAdjstmnt> perEmpVacationAdjstmnts) {
       this.id = id;
       this.perVacationCode = perVacationCode;
       this.perEmploymentMasters = perEmploymentMasters;
       this.vacStartDate = vacStartDate;
       this.vacEndDate = vacEndDate;
       this.vacEndDateActual = vacEndDateActual;
       this.directBossAprove = directBossAprove;
       this.bigBossAprove = bigBossAprove;
       this.spcPeriodDay = spcPeriodDay;
       this.spcPeriodMn = spcPeriodMn;
       this.spcPeriodYr = spcPeriodYr;
       this.vacBalType = vacBalType;
       this.decisionNo = decisionNo;
       this.decisionDate = decisionDate;
       this.decisionNotes = decisionNotes;
       this.returnDate = returnDate;
       this.postDate = postDate;
       this.vacNote = vacNote;
       this.period = period;
       this.balBeforeVac = balBeforeVac;
       this.balRemaining = balRemaining;
       this.vacPunType = vacPunType;
       this.militaryCardNo = militaryCardNo;
       this.fridayFlg = fridayFlg;
       this.saturdayFlg = saturdayFlg;
       this.sundayFlg = sundayFlg;
       this.mondayFlg = mondayFlg;
       this.tuesdayFlg = tuesdayFlg;
       this.wednesdayFlg = wednesdayFlg;
       this.thursdayFlg = thursdayFlg;
       this.remarks = remarks;
       this.bigBossReason = bigBossReason;
       this.bigBossDate = bigBossDate;
       this.bigBossNo = bigBossNo;
       this.directBossReason = directBossReason;
       this.directBossDate = directBossDate;
       this.directBossNo = directBossNo;
       this.perEmpVacationAdjstmnts = perEmpVacationAdjstmnts;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, length=10) ), 
        @AttributeOverride(name="vacationCode", column=@Column(name="VACATION_CODE", nullable=false, length=2) ), 
        @AttributeOverride(name="transSerialNo", column=@Column(name="TRANS_SERIAL_NO", nullable=false, length=5) ) } )
    public PerEmpVacationTransId getId() {
        return this.id;
    }
    
    public void setId(PerEmpVacationTransId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VACATION_CODE", nullable=false, insertable=false, updatable=false)
    public PerVacationCode getPerVacationCode() {
        return this.perVacationCode;
    }
    
    public void setPerVacationCode(PerVacationCode perVacationCode) {
        this.perVacationCode = perVacationCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false)
    public PerEmploymentMasters getPerEmploymentMasters() {
        return this.perEmploymentMasters;
    }
    
    public void setPerEmploymentMasters(PerEmploymentMasters perEmploymentMasters) {
        this.perEmploymentMasters = perEmploymentMasters;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VAC_START_DATE", length=7)
    public Date getVacStartDate() {
        return this.vacStartDate;
    }
    
    public void setVacStartDate(Date vacStartDate) {
        this.vacStartDate = vacStartDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VAC_END_DATE", length=7)
    public Date getVacEndDate() {
        return this.vacEndDate;
    }
    
    public void setVacEndDate(Date vacEndDate) {
        this.vacEndDate = vacEndDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VAC_END_DATE_ACTUAL", length=7)
    public Date getVacEndDateActual() {
        return this.vacEndDateActual;
    }
    
    public void setVacEndDateActual(Date vacEndDateActual) {
        this.vacEndDateActual = vacEndDateActual;
    }

    
    @Column(name="DIRECT_BOSS_APROVE", precision=1, scale=0)
    public Boolean getDirectBossAprove() {
        return this.directBossAprove;
    }
    
    public void setDirectBossAprove(Boolean directBossAprove) {
        this.directBossAprove = directBossAprove;
    }

    
    @Column(name="BIG_BOSS_APROVE", precision=1, scale=0)
    public Boolean getBigBossAprove() {
        return this.bigBossAprove;
    }
    
    public void setBigBossAprove(Boolean bigBossAprove) {
        this.bigBossAprove = bigBossAprove;
    }

    
    @Column(name="SPC_PERIOD_DAY", precision=2, scale=0)
    public Byte getSpcPeriodDay() {
        return this.spcPeriodDay;
    }
    
    public void setSpcPeriodDay(Byte spcPeriodDay) {
        this.spcPeriodDay = spcPeriodDay;
    }

    
    @Column(name="SPC_PERIOD_MN", precision=2, scale=0)
    public Byte getSpcPeriodMn() {
        return this.spcPeriodMn;
    }
    
    public void setSpcPeriodMn(Byte spcPeriodMn) {
        this.spcPeriodMn = spcPeriodMn;
    }

    
    @Column(name="SPC_PERIOD_YR", precision=2, scale=0)
    public Byte getSpcPeriodYr() {
        return this.spcPeriodYr;
    }
    
    public void setSpcPeriodYr(Byte spcPeriodYr) {
        this.spcPeriodYr = spcPeriodYr;
    }

    
    @Column(name="VAC_BAL_TYPE", precision=1, scale=0)
    public Boolean getVacBalType() {
        return this.vacBalType;
    }
    
    public void setVacBalType(Boolean vacBalType) {
        this.vacBalType = vacBalType;
    }

    
    @Column(name="DECISION_NO", length=10)
    public String getDecisionNo() {
        return this.decisionNo;
    }
    
    public void setDecisionNo(String decisionNo) {
        this.decisionNo = decisionNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DECISION_DATE", length=7)
    public Date getDecisionDate() {
        return this.decisionDate;
    }
    
    public void setDecisionDate(Date decisionDate) {
        this.decisionDate = decisionDate;
    }

    
    @Column(name="DECISION_NOTES", length=500)
    public String getDecisionNotes() {
        return this.decisionNotes;
    }
    
    public void setDecisionNotes(String decisionNotes) {
        this.decisionNotes = decisionNotes;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RETURN_DATE", length=7)
    public Date getReturnDate() {
        return this.returnDate;
    }
    
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="POST_DATE", length=7)
    public Date getPostDate() {
        return this.postDate;
    }
    
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }

    
    @Column(name="VAC_NOTE", length=250)
    public String getVacNote() {
        return this.vacNote;
    }
    
    public void setVacNote(String vacNote) {
        this.vacNote = vacNote;
    }

    
    @Column(name="PERIOD", precision=7)
    public BigDecimal getPeriod() {
        return this.period;
    }
    
    public void setPeriod(BigDecimal period) {
        this.period = period;
    }

    
    @Column(name="BAL_BEFORE_VAC", precision=5)
    public BigDecimal getBalBeforeVac() {
        return this.balBeforeVac;
    }
    
    public void setBalBeforeVac(BigDecimal balBeforeVac) {
        this.balBeforeVac = balBeforeVac;
    }

    
    @Column(name="BAL_REMAINING", precision=5)
    public BigDecimal getBalRemaining() {
        return this.balRemaining;
    }
    
    public void setBalRemaining(BigDecimal balRemaining) {
        this.balRemaining = balRemaining;
    }

    
    @Column(name="VAC_PUN_TYPE", precision=1, scale=0)
    public Boolean getVacPunType() {
        return this.vacPunType;
    }
    
    public void setVacPunType(Boolean vacPunType) {
        this.vacPunType = vacPunType;
    }

    
    @Column(name="MILITARY_CARD_NO", length=30)
    public String getMilitaryCardNo() {
        return this.militaryCardNo;
    }
    
    public void setMilitaryCardNo(String militaryCardNo) {
        this.militaryCardNo = militaryCardNo;
    }

    
    @Column(name="FRIDAY_FLG", precision=1, scale=0)
    public Boolean getFridayFlg() {
        return this.fridayFlg;
    }
    
    public void setFridayFlg(Boolean fridayFlg) {
        this.fridayFlg = fridayFlg;
    }

    
    @Column(name="SATURDAY_FLG", precision=1, scale=0)
    public Boolean getSaturdayFlg() {
        return this.saturdayFlg;
    }
    
    public void setSaturdayFlg(Boolean saturdayFlg) {
        this.saturdayFlg = saturdayFlg;
    }

    
    @Column(name="SUNDAY_FLG", precision=1, scale=0)
    public Boolean getSundayFlg() {
        return this.sundayFlg;
    }
    
    public void setSundayFlg(Boolean sundayFlg) {
        this.sundayFlg = sundayFlg;
    }

    
    @Column(name="MONDAY_FLG", precision=1, scale=0)
    public Boolean getMondayFlg() {
        return this.mondayFlg;
    }
    
    public void setMondayFlg(Boolean mondayFlg) {
        this.mondayFlg = mondayFlg;
    }

    
    @Column(name="TUESDAY_FLG", precision=1, scale=0)
    public Boolean getTuesdayFlg() {
        return this.tuesdayFlg;
    }
    
    public void setTuesdayFlg(Boolean tuesdayFlg) {
        this.tuesdayFlg = tuesdayFlg;
    }

    
    @Column(name="WEDNESDAY_FLG", precision=1, scale=0)
    public Boolean getWednesdayFlg() {
        return this.wednesdayFlg;
    }
    
    public void setWednesdayFlg(Boolean wednesdayFlg) {
        this.wednesdayFlg = wednesdayFlg;
    }

    
    @Column(name="THURSDAY_FLG", precision=1, scale=0)
    public Boolean getThursdayFlg() {
        return this.thursdayFlg;
    }
    
    public void setThursdayFlg(Boolean thursdayFlg) {
        this.thursdayFlg = thursdayFlg;
    }

    
    @Column(name="REMARKS", length=500)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    
    @Column(name="BIG_BOSS_REASON", length=50)
    public String getBigBossReason() {
        return this.bigBossReason;
    }
    
    public void setBigBossReason(String bigBossReason) {
        this.bigBossReason = bigBossReason;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="BIG_BOSS_DATE", length=7)
    public Date getBigBossDate() {
        return this.bigBossDate;
    }
    
    public void setBigBossDate(Date bigBossDate) {
        this.bigBossDate = bigBossDate;
    }

    
    @Column(name="BIG_BOSS_NO", length=10)
    public String getBigBossNo() {
        return this.bigBossNo;
    }
    
    public void setBigBossNo(String bigBossNo) {
        this.bigBossNo = bigBossNo;
    }

    
    @Column(name="DIRECT_BOSS_REASON", length=50)
    public String getDirectBossReason() {
        return this.directBossReason;
    }
    
    public void setDirectBossReason(String directBossReason) {
        this.directBossReason = directBossReason;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DIRECT_BOSS_DATE", length=7)
    public Date getDirectBossDate() {
        return this.directBossDate;
    }
    
    public void setDirectBossDate(Date directBossDate) {
        this.directBossDate = directBossDate;
    }

    
    @Column(name="DIRECT_BOSS_NO", length=10)
    public String getDirectBossNo() {
        return this.directBossNo;
    }
    
    public void setDirectBossNo(String directBossNo) {
        this.directBossNo = directBossNo;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmpVacationTrans")
    public Set<PerEmpVacationAdjstmnt> getPerEmpVacationAdjstmnts() {
        return this.perEmpVacationAdjstmnts;
    }
    
    public void setPerEmpVacationAdjstmnts(Set<PerEmpVacationAdjstmnt> perEmpVacationAdjstmnts) {
        this.perEmpVacationAdjstmnts = perEmpVacationAdjstmnts;
    }




}


