package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerElawaVacationRule generated by hbm2java
 */
@Entity
@Table(name="PER_ELAWA_VACATION_RULE"
    ,schema="SHAMS"
)
public class PerElawaVacationRule  implements java.io.Serializable {


     private PerElawaVacationRuleId id;
     private PerVacationCode perVacationCode;
     private int lossBalance;
     private Date vacFromdate;
     private Date vacTodate;

    public PerElawaVacationRule() {
    }

    public PerElawaVacationRule(PerElawaVacationRuleId id, PerVacationCode perVacationCode, int lossBalance, Date vacFromdate, Date vacTodate) {
       this.id = id;
       this.perVacationCode = perVacationCode;
       this.lossBalance = lossBalance;
       this.vacFromdate = vacFromdate;
       this.vacTodate = vacTodate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="locationCode", column=@Column(name="LOCATION_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="elawaDate", column=@Column(name="ELAWA_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="elawaTypeCode", column=@Column(name="ELAWA_TYPE_CODE", nullable=false, length=2) ), 
        @AttributeOverride(name="vacationCode", column=@Column(name="VACATION_CODE", nullable=false, length=2) ) } )
    public PerElawaVacationRuleId getId() {
        return this.id;
    }
    
    public void setId(PerElawaVacationRuleId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="VACATION_CODE", nullable=false, insertable=false, updatable=false)
    public PerVacationCode getPerVacationCode() {
        return this.perVacationCode;
    }
    
    public void setPerVacationCode(PerVacationCode perVacationCode) {
        this.perVacationCode = perVacationCode;
    }

    
    @Column(name="LOSS_BALANCE", nullable=false, precision=5, scale=0)
    public int getLossBalance() {
        return this.lossBalance;
    }
    
    public void setLossBalance(int lossBalance) {
        this.lossBalance = lossBalance;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VAC_FROMDATE", nullable=false, length=7)
    public Date getVacFromdate() {
        return this.vacFromdate;
    }
    
    public void setVacFromdate(Date vacFromdate) {
        this.vacFromdate = vacFromdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VAC_TODATE", nullable=false, length=7)
    public Date getVacTodate() {
        return this.vacTodate;
    }
    
    public void setVacTodate(Date vacTodate) {
        this.vacTodate = vacTodate;
    }




}


