package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerEmploymentParameter generated by hbm2java
 */
@Entity
@Table(name="PER_EMPLOYMENT_PARAMETER"
    ,schema="SHAMS"
)
public class PerEmploymentParameter  implements java.io.Serializable {


     private String employmentSourceCode;
     private String employmentSourceDesc;
     private String employmentInterval;
     private String equpyFinancedDegree;
     private short testPeriod;
     private Short employmentYearsNo;
     private Byte pensionAge;
     private Byte hireAge;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private Set<PerElawaHireRule> perElawaHireRules = new HashSet<PerElawaHireRule>(0);
     private Set<PerEmploymentMasters> perEmploymentMasterses = new HashSet<PerEmploymentMasters>(0);
     private Set<PerVacationRuleEmp> perVacationRuleEmps = new HashSet<PerVacationRuleEmp>(0);
     private Set<PerEmpHistory> perEmpHistories = new HashSet<PerEmpHistory>(0);
     private Set<PayExecutionSpecificEmp> payExecutionSpecificEmps = new HashSet<PayExecutionSpecificEmp>(0);

    public PerEmploymentParameter() {
    }

	
    public PerEmploymentParameter(String employmentSourceCode, String employmentSourceDesc, String employmentInterval, String equpyFinancedDegree, short testPeriod) {
        this.employmentSourceCode = employmentSourceCode;
        this.employmentSourceDesc = employmentSourceDesc;
        this.employmentInterval = employmentInterval;
        this.equpyFinancedDegree = equpyFinancedDegree;
        this.testPeriod = testPeriod;
    }
    public PerEmploymentParameter(String employmentSourceCode, String employmentSourceDesc, String employmentInterval, String equpyFinancedDegree, short testPeriod, Short employmentYearsNo, Byte pensionAge, Byte hireAge, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, Set<PerElawaHireRule> perElawaHireRules, Set<PerEmploymentMasters> perEmploymentMasterses, Set<PerVacationRuleEmp> perVacationRuleEmps, Set<PerEmpHistory> perEmpHistories, Set<PayExecutionSpecificEmp> payExecutionSpecificEmps) {
       this.employmentSourceCode = employmentSourceCode;
       this.employmentSourceDesc = employmentSourceDesc;
       this.employmentInterval = employmentInterval;
       this.equpyFinancedDegree = equpyFinancedDegree;
       this.testPeriod = testPeriod;
       this.employmentYearsNo = employmentYearsNo;
       this.pensionAge = pensionAge;
       this.hireAge = hireAge;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.perElawaHireRules = perElawaHireRules;
       this.perEmploymentMasterses = perEmploymentMasterses;
       this.perVacationRuleEmps = perVacationRuleEmps;
       this.perEmpHistories = perEmpHistories;
       this.payExecutionSpecificEmps = payExecutionSpecificEmps;
    }
   
     @Id 

    
    @Column(name="EMPLOYMENT_SOURCE_CODE", unique=true, nullable=false, length=5)
    public String getEmploymentSourceCode() {
        return this.employmentSourceCode;
    }
    
    public void setEmploymentSourceCode(String employmentSourceCode) {
        this.employmentSourceCode = employmentSourceCode;
    }

    
    @Column(name="EMPLOYMENT_SOURCE_DESC", nullable=false, length=50)
    public String getEmploymentSourceDesc() {
        return this.employmentSourceDesc;
    }
    
    public void setEmploymentSourceDesc(String employmentSourceDesc) {
        this.employmentSourceDesc = employmentSourceDesc;
    }

    
    @Column(name="EMPLOYMENT_INTERVAL", nullable=false, length=1)
    public String getEmploymentInterval() {
        return this.employmentInterval;
    }
    
    public void setEmploymentInterval(String employmentInterval) {
        this.employmentInterval = employmentInterval;
    }

    
    @Column(name="EQUPY_FINANCED_DEGREE", nullable=false, length=1)
    public String getEqupyFinancedDegree() {
        return this.equpyFinancedDegree;
    }
    
    public void setEqupyFinancedDegree(String equpyFinancedDegree) {
        this.equpyFinancedDegree = equpyFinancedDegree;
    }

    
    @Column(name="TEST_PERIOD", nullable=false, precision=3, scale=0)
    public short getTestPeriod() {
        return this.testPeriod;
    }
    
    public void setTestPeriod(short testPeriod) {
        this.testPeriod = testPeriod;
    }

    
    @Column(name="EMPLOYMENT_YEARS_NO", precision=3, scale=0)
    public Short getEmploymentYearsNo() {
        return this.employmentYearsNo;
    }
    
    public void setEmploymentYearsNo(Short employmentYearsNo) {
        this.employmentYearsNo = employmentYearsNo;
    }

    
    @Column(name="PENSION_AGE", precision=2, scale=0)
    public Byte getPensionAge() {
        return this.pensionAge;
    }
    
    public void setPensionAge(Byte pensionAge) {
        this.pensionAge = pensionAge;
    }

    
    @Column(name="HIRE_AGE", precision=2, scale=0)
    public Byte getHireAge() {
        return this.hireAge;
    }
    
    public void setHireAge(Byte hireAge) {
        this.hireAge = hireAge;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentParameter")
    public Set<PerElawaHireRule> getPerElawaHireRules() {
        return this.perElawaHireRules;
    }
    
    public void setPerElawaHireRules(Set<PerElawaHireRule> perElawaHireRules) {
        this.perElawaHireRules = perElawaHireRules;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentParameter")
    public Set<PerEmploymentMasters> getPerEmploymentMasterses() {
        return this.perEmploymentMasterses;
    }
    
    public void setPerEmploymentMasterses(Set<PerEmploymentMasters> perEmploymentMasterses) {
        this.perEmploymentMasterses = perEmploymentMasterses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentParameter")
    public Set<PerVacationRuleEmp> getPerVacationRuleEmps() {
        return this.perVacationRuleEmps;
    }
    
    public void setPerVacationRuleEmps(Set<PerVacationRuleEmp> perVacationRuleEmps) {
        this.perVacationRuleEmps = perVacationRuleEmps;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentParameter")
    public Set<PerEmpHistory> getPerEmpHistories() {
        return this.perEmpHistories;
    }
    
    public void setPerEmpHistories(Set<PerEmpHistory> perEmpHistories) {
        this.perEmpHistories = perEmpHistories;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEmploymentParameter")
    public Set<PayExecutionSpecificEmp> getPayExecutionSpecificEmps() {
        return this.payExecutionSpecificEmps;
    }
    
    public void setPayExecutionSpecificEmps(Set<PayExecutionSpecificEmp> payExecutionSpecificEmps) {
        this.payExecutionSpecificEmps = payExecutionSpecificEmps;
    }




}


