package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PerElawaGradeRule generated by hbm2java
 */
@Entity
@Table(name="PER_ELAWA_GRADE_RULE"
    ,schema="SHAMS"
)
public class PerElawaGradeRule  implements java.io.Serializable {


     private PerElawaGradeRuleId id;
     private PerEvalPercentage perEvalPercentage;
     private Boolean elawaCalc;
     private BigDecimal elawaValue;

    public PerElawaGradeRule() {
    }

	
    public PerElawaGradeRule(PerElawaGradeRuleId id, PerEvalPercentage perEvalPercentage) {
        this.id = id;
        this.perEvalPercentage = perEvalPercentage;
    }
    public PerElawaGradeRule(PerElawaGradeRuleId id, PerEvalPercentage perEvalPercentage, Boolean elawaCalc, BigDecimal elawaValue) {
       this.id = id;
       this.perEvalPercentage = perEvalPercentage;
       this.elawaCalc = elawaCalc;
       this.elawaValue = elawaValue;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="elawaTypeCode", column=@Column(name="ELAWA_TYPE_CODE", nullable=false, length=2) ), 
        @AttributeOverride(name="locationCode", column=@Column(name="LOCATION_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="elawaDate", column=@Column(name="ELAWA_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="annualId1", column=@Column(name="ANNUAL_ID_1", nullable=false, length=5) ), 
        @AttributeOverride(name="gradeCode", column=@Column(name="GRADE_CODE", nullable=false, length=2) ) } )
    public PerElawaGradeRuleId getId() {
        return this.id;
    }
    
    public void setId(PerElawaGradeRuleId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="GRADE_CODE", nullable=false, insertable=false, updatable=false)
    public PerEvalPercentage getPerEvalPercentage() {
        return this.perEvalPercentage;
    }
    
    public void setPerEvalPercentage(PerEvalPercentage perEvalPercentage) {
        this.perEvalPercentage = perEvalPercentage;
    }

    
    @Column(name="ELAWA_CALC", precision=1, scale=0)
    public Boolean getElawaCalc() {
        return this.elawaCalc;
    }
    
    public void setElawaCalc(Boolean elawaCalc) {
        this.elawaCalc = elawaCalc;
    }

    
    @Column(name="ELAWA_VALUE", precision=9)
    public BigDecimal getElawaValue() {
        return this.elawaValue;
    }
    
    public void setElawaValue(BigDecimal elawaValue) {
        this.elawaValue = elawaValue;
    }




}


