package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerEvalMainAttribute generated by hbm2java
 */
@Entity
@Table(name="PER_EVAL_MAIN_ATTRIBUTE"
    ,schema="SHAMS"
)
public class PerEvalMainAttribute  implements java.io.Serializable {


     private String mainAttributeNo;
     private String mainAttributeName;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private Set<PerEvalAttribute> perEvalAttributes = new HashSet<PerEvalAttribute>(0);

    public PerEvalMainAttribute() {
    }

	
    public PerEvalMainAttribute(String mainAttributeNo, String mainAttributeName) {
        this.mainAttributeNo = mainAttributeNo;
        this.mainAttributeName = mainAttributeName;
    }
    public PerEvalMainAttribute(String mainAttributeNo, String mainAttributeName, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, Set<PerEvalAttribute> perEvalAttributes) {
       this.mainAttributeNo = mainAttributeNo;
       this.mainAttributeName = mainAttributeName;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.perEvalAttributes = perEvalAttributes;
    }
   
     @Id 

    
    @Column(name="MAIN_ATTRIBUTE_NO", unique=true, nullable=false, length=2)
    public String getMainAttributeNo() {
        return this.mainAttributeNo;
    }
    
    public void setMainAttributeNo(String mainAttributeNo) {
        this.mainAttributeNo = mainAttributeNo;
    }

    
    @Column(name="MAIN_ATTRIBUTE_NAME", nullable=false, length=50)
    public String getMainAttributeName() {
        return this.mainAttributeName;
    }
    
    public void setMainAttributeName(String mainAttributeName) {
        this.mainAttributeName = mainAttributeName;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEvalMainAttribute")
    public Set<PerEvalAttribute> getPerEvalAttributes() {
        return this.perEvalAttributes;
    }
    
    public void setPerEvalAttributes(Set<PerEvalAttribute> perEvalAttributes) {
        this.perEvalAttributes = perEvalAttributes;
    }




}


