package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PerEvalAttributeDetail generated by hbm2java
 */
@Entity
@Table(name="PER_EVAL_ATTRIBUTE_DETAIL"
    ,schema="SHAMS"
)
public class PerEvalAttributeDetail  implements java.io.Serializable {


     private String serialNo;
     private PerFiscalDegreeCode perFiscalDegreeCode;
     private PerFiscalDegreeCodeNew perFiscalDegreeCodeNew;
     private PerGroupTypeCode perGroupTypeCode;
     private PerJobTypeCode perJobTypeCode;
     private PerEvalAttribute perEvalAttribute;
     private int evalDegree;
     private Set<PerAnnualEvalEmpDetail> perAnnualEvalEmpDetails = new HashSet<PerAnnualEvalEmpDetail>(0);

    public PerEvalAttributeDetail() {
    }

	
    public PerEvalAttributeDetail(String serialNo, PerEvalAttribute perEvalAttribute, int evalDegree) {
        this.serialNo = serialNo;
        this.perEvalAttribute = perEvalAttribute;
        this.evalDegree = evalDegree;
    }
    public PerEvalAttributeDetail(String serialNo, PerFiscalDegreeCode perFiscalDegreeCode, PerFiscalDegreeCodeNew perFiscalDegreeCodeNew, PerGroupTypeCode perGroupTypeCode, PerJobTypeCode perJobTypeCode, PerEvalAttribute perEvalAttribute, int evalDegree, Set<PerAnnualEvalEmpDetail> perAnnualEvalEmpDetails) {
       this.serialNo = serialNo;
       this.perFiscalDegreeCode = perFiscalDegreeCode;
       this.perFiscalDegreeCodeNew = perFiscalDegreeCodeNew;
       this.perGroupTypeCode = perGroupTypeCode;
       this.perJobTypeCode = perJobTypeCode;
       this.perEvalAttribute = perEvalAttribute;
       this.evalDegree = evalDegree;
       this.perAnnualEvalEmpDetails = perAnnualEvalEmpDetails;
    }
   
     @Id 

    
    @Column(name="SERIAL_NO", unique=true, nullable=false, length=5)
    public String getSerialNo() {
        return this.serialNo;
    }
    
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="FISCAL_DEGREE_CODE")
    public PerFiscalDegreeCode getPerFiscalDegreeCode() {
        return this.perFiscalDegreeCode;
    }
    
    public void setPerFiscalDegreeCode(PerFiscalDegreeCode perFiscalDegreeCode) {
        this.perFiscalDegreeCode = perFiscalDegreeCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="FISCAL_DEGREE_CODE_NEW")
    public PerFiscalDegreeCodeNew getPerFiscalDegreeCodeNew() {
        return this.perFiscalDegreeCodeNew;
    }
    
    public void setPerFiscalDegreeCodeNew(PerFiscalDegreeCodeNew perFiscalDegreeCodeNew) {
        this.perFiscalDegreeCodeNew = perFiscalDegreeCodeNew;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="GROUP_TYPE_CODE")
    public PerGroupTypeCode getPerGroupTypeCode() {
        return this.perGroupTypeCode;
    }
    
    public void setPerGroupTypeCode(PerGroupTypeCode perGroupTypeCode) {
        this.perGroupTypeCode = perGroupTypeCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="JOB_TYPE_CODE")
    public PerJobTypeCode getPerJobTypeCode() {
        return this.perJobTypeCode;
    }
    
    public void setPerJobTypeCode(PerJobTypeCode perJobTypeCode) {
        this.perJobTypeCode = perJobTypeCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ATTRIBUTE_NO", nullable=false)
    public PerEvalAttribute getPerEvalAttribute() {
        return this.perEvalAttribute;
    }
    
    public void setPerEvalAttribute(PerEvalAttribute perEvalAttribute) {
        this.perEvalAttribute = perEvalAttribute;
    }

    
    @Column(name="EVAL_DEGREE", nullable=false, precision=5, scale=0)
    public int getEvalDegree() {
        return this.evalDegree;
    }
    
    public void setEvalDegree(int evalDegree) {
        this.evalDegree = evalDegree;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perEvalAttributeDetail")
    public Set<PerAnnualEvalEmpDetail> getPerAnnualEvalEmpDetails() {
        return this.perAnnualEvalEmpDetails;
    }
    
    public void setPerAnnualEvalEmpDetails(Set<PerAnnualEvalEmpDetail> perAnnualEvalEmpDetails) {
        this.perAnnualEvalEmpDetails = perAnnualEvalEmpDetails;
    }




}


