package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerEvalAttribute generated by hbm2java
 */
@Entity
@Table(name="PER_EVAL_ATTRIBUTE"
    ,schema="SHAMS"
)
public class PerEvalAttribute  implements java.io.Serializable {


     private String attributeNo;
     private PerEvalMainAttribute perEvalMainAttribute;
     private String attributeName;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private Set<PerAnnualEvalType> perAnnualEvalTypes = new HashSet<PerAnnualEvalType>(0);
     private Set<PerEvalAttributeSpecialDtl> perEvalAttributeSpecialDtls = new HashSet<PerEvalAttributeSpecialDtl>(0);
     private Set<PerEvalAttributeDetail> perEvalAttributeDetails = new HashSet<PerEvalAttributeDetail>(0);

    public PerEvalAttribute() {
    }

	
    public PerEvalAttribute(String attributeNo, PerEvalMainAttribute perEvalMainAttribute, String attributeName) {
        this.attributeNo = attributeNo;
        this.perEvalMainAttribute = perEvalMainAttribute;
        this.attributeName = attributeName;
    }
    public PerEvalAttribute(String attributeNo, PerEvalMainAttribute perEvalMainAttribute, String attributeName, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, Set<PerAnnualEvalType> perAnnualEvalTypes, Set<PerEvalAttributeSpecialDtl> perEvalAttributeSpecialDtls, Set<PerEvalAttributeDetail> perEvalAttributeDetails) {
       this.attributeNo = attributeNo;
       this.perEvalMainAttribute = perEvalMainAttribute;
       this.attributeName = attributeName;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.perAnnualEvalTypes = perAnnualEvalTypes;
       this.perEvalAttributeSpecialDtls = perEvalAttributeSpecialDtls;
       this.perEvalAttributeDetails = perEvalAttributeDetails;
    }
   
     @Id 

    
    @Column(name="ATTRIBUTE_NO", unique=true, nullable=false, length=5)
    public String getAttributeNo() {
        return this.attributeNo;
    }
    
    public void setAttributeNo(String attributeNo) {
        this.attributeNo = attributeNo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MAIN_ATTRIBUTE_NO", nullable=false)
    public PerEvalMainAttribute getPerEvalMainAttribute() {
        return this.perEvalMainAttribute;
    }
    
    public void setPerEvalMainAttribute(PerEvalMainAttribute perEvalMainAttribute) {
        this.perEvalMainAttribute = perEvalMainAttribute;
    }

    
    @Column(name="ATTRIBUTE_NAME", nullable=false, length=75)
    public String getAttributeName() {
        return this.attributeName;
    }
    
    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="perEvalAttributes")
    public Set<PerAnnualEvalType> getPerAnnualEvalTypes() {
        return this.perAnnualEvalTypes;
    }
    
    public void setPerAnnualEvalTypes(Set<PerAnnualEvalType> perAnnualEvalTypes) {
        this.perAnnualEvalTypes = perAnnualEvalTypes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perEvalAttribute")
    public Set<PerEvalAttributeSpecialDtl> getPerEvalAttributeSpecialDtls() {
        return this.perEvalAttributeSpecialDtls;
    }
    
    public void setPerEvalAttributeSpecialDtls(Set<PerEvalAttributeSpecialDtl> perEvalAttributeSpecialDtls) {
        this.perEvalAttributeSpecialDtls = perEvalAttributeSpecialDtls;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perEvalAttribute")
    public Set<PerEvalAttributeDetail> getPerEvalAttributeDetails() {
        return this.perEvalAttributeDetails;
    }
    
    public void setPerEvalAttributeDetails(Set<PerEvalAttributeDetail> perEvalAttributeDetails) {
        this.perEvalAttributeDetails = perEvalAttributeDetails;
    }




}


