package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.sql.Blob;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerEmpFileDoc generated by hbm2java
 */
@Entity
@Table(name="PER_EMP_FILE_DOC"
    ,schema="SHAMS"
)
public class PerEmpFileDoc  implements java.io.Serializable {


     private PerEmpFileDocId id;
     private PerEmpFile perEmpFile;
     private String docTitle;
     private Blob docImage;
     private Date docSaveDt;

    public PerEmpFileDoc() {
    }

	
    public PerEmpFileDoc(PerEmpFileDocId id, PerEmpFile perEmpFile) {
        this.id = id;
        this.perEmpFile = perEmpFile;
    }
    public PerEmpFileDoc(PerEmpFileDocId id, PerEmpFile perEmpFile, String docTitle, Blob docImage, Date docSaveDt) {
       this.id = id;
       this.perEmpFile = perEmpFile;
       this.docTitle = docTitle;
       this.docImage = docImage;
       this.docSaveDt = docSaveDt;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="employeeId", column=@Column(name="EMPLOYEE_ID", nullable=false, length=10) ), 
        @AttributeOverride(name="fileSerial", column=@Column(name="FILE_SERIAL", nullable=false, length=2) ), 
        @AttributeOverride(name="fileDocSerial", column=@Column(name="FILE_DOC_SERIAL", nullable=false, length=5) ) } )
    public PerEmpFileDocId getId() {
        return this.id;
    }
    
    public void setId(PerEmpFileDocId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="EMPLOYEE_ID", referencedColumnName="EMPLOYEE_ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="FILE_SERIAL", referencedColumnName="FILE_SERIAL", nullable=false, insertable=false, updatable=false) } )
    public PerEmpFile getPerEmpFile() {
        return this.perEmpFile;
    }
    
    public void setPerEmpFile(PerEmpFile perEmpFile) {
        this.perEmpFile = perEmpFile;
    }

    
    @Column(name="DOC_TITLE", length=150)
    public String getDocTitle() {
        return this.docTitle;
    }
    
    public void setDocTitle(String docTitle) {
        this.docTitle = docTitle;
    }

    
    @Column(name="DOC_IMAGE")
    public Blob getDocImage() {
        return this.docImage;
    }
    
    public void setDocImage(Blob docImage) {
        this.docImage = docImage;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DOC_SAVE_DT", length=7)
    public Date getDocSaveDt() {
        return this.docSaveDt;
    }
    
    public void setDocSaveDt(Date docSaveDt) {
        this.docSaveDt = docSaveDt;
    }




}


