package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerElawaType generated by hbm2java
 */
@Entity
@Table(name="PER_ELAWA_TYPE"
    ,schema="SHAMS"
)
public class PerElawaType  implements java.io.Serializable {


     private String elawaTypeCode;
     private PerGeneralCode perGeneralCode;
     private String elawaTypeName;
     private boolean elawaSal;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;

    public PerElawaType() {
    }

	
    public PerElawaType(String elawaTypeCode, PerGeneralCode perGeneralCode, String elawaTypeName, boolean elawaSal) {
        this.elawaTypeCode = elawaTypeCode;
        this.perGeneralCode = perGeneralCode;
        this.elawaTypeName = elawaTypeName;
        this.elawaSal = elawaSal;
    }
    public PerElawaType(String elawaTypeCode, PerGeneralCode perGeneralCode, String elawaTypeName, boolean elawaSal, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate) {
       this.elawaTypeCode = elawaTypeCode;
       this.perGeneralCode = perGeneralCode;
       this.elawaTypeName = elawaTypeName;
       this.elawaSal = elawaSal;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
    }
   
     @Id 

    
    @Column(name="ELAWA_TYPE_CODE", unique=true, nullable=false, length=2)
    public String getElawaTypeCode() {
        return this.elawaTypeCode;
    }
    
    public void setElawaTypeCode(String elawaTypeCode) {
        this.elawaTypeCode = elawaTypeCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="GENERAL_CODE", nullable=false)
    public PerGeneralCode getPerGeneralCode() {
        return this.perGeneralCode;
    }
    
    public void setPerGeneralCode(PerGeneralCode perGeneralCode) {
        this.perGeneralCode = perGeneralCode;
    }

    
    @Column(name="ELAWA_TYPE_NAME", nullable=false, length=25)
    public String getElawaTypeName() {
        return this.elawaTypeName;
    }
    
    public void setElawaTypeName(String elawaTypeName) {
        this.elawaTypeName = elawaTypeName;
    }

    
    @Column(name="ELAWA_SAL", nullable=false, precision=1, scale=0)
    public boolean isElawaSal() {
        return this.elawaSal;
    }
    
    public void setElawaSal(boolean elawaSal) {
        this.elawaSal = elawaSal;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }




}


