package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerElawaPunishRule generated by hbm2java
 */
@Entity
@Table(name="PER_ELAWA_PUNISH_RULE"
    ,schema="SHAMS"
)
public class PerElawaPunishRule  implements java.io.Serializable {


     private PerElawaPunishRuleId id;
     private PerPunishmentCode perPunishmentCode;
     private boolean elawaCalc;
     private BigDecimal elawaValue;
     private Date punishFromdate;
     private Date punishTodate;

    public PerElawaPunishRule() {
    }

	
    public PerElawaPunishRule(PerElawaPunishRuleId id, PerPunishmentCode perPunishmentCode, boolean elawaCalc, BigDecimal elawaValue) {
        this.id = id;
        this.perPunishmentCode = perPunishmentCode;
        this.elawaCalc = elawaCalc;
        this.elawaValue = elawaValue;
    }
    public PerElawaPunishRule(PerElawaPunishRuleId id, PerPunishmentCode perPunishmentCode, boolean elawaCalc, BigDecimal elawaValue, Date punishFromdate, Date punishTodate) {
       this.id = id;
       this.perPunishmentCode = perPunishmentCode;
       this.elawaCalc = elawaCalc;
       this.elawaValue = elawaValue;
       this.punishFromdate = punishFromdate;
       this.punishTodate = punishTodate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="locationCode", column=@Column(name="LOCATION_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="elawaDate", column=@Column(name="ELAWA_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="elawaTypeCode", column=@Column(name="ELAWA_TYPE_CODE", nullable=false, length=2) ), 
        @AttributeOverride(name="punishCode", column=@Column(name="PUNISH_CODE", nullable=false, length=3) ) } )
    public PerElawaPunishRuleId getId() {
        return this.id;
    }
    
    public void setId(PerElawaPunishRuleId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="PUNISH_CODE", nullable=false, insertable=false, updatable=false)
    public PerPunishmentCode getPerPunishmentCode() {
        return this.perPunishmentCode;
    }
    
    public void setPerPunishmentCode(PerPunishmentCode perPunishmentCode) {
        this.perPunishmentCode = perPunishmentCode;
    }

    
    @Column(name="ELAWA_CALC", nullable=false, precision=1, scale=0)
    public boolean isElawaCalc() {
        return this.elawaCalc;
    }
    
    public void setElawaCalc(boolean elawaCalc) {
        this.elawaCalc = elawaCalc;
    }

    
    @Column(name="ELAWA_VALUE", nullable=false, precision=9)
    public BigDecimal getElawaValue() {
        return this.elawaValue;
    }
    
    public void setElawaValue(BigDecimal elawaValue) {
        this.elawaValue = elawaValue;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PUNISH_FROMDATE", length=7)
    public Date getPunishFromdate() {
        return this.punishFromdate;
    }
    
    public void setPunishFromdate(Date punishFromdate) {
        this.punishFromdate = punishFromdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PUNISH_TODATE", length=7)
    public Date getPunishTodate() {
        return this.punishTodate;
    }
    
    public void setPunishTodate(Date punishTodate) {
        this.punishTodate = punishTodate;
    }




}


