package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PerElawaHireRule generated by hbm2java
 */
@Entity
@Table(name="PER_ELAWA_HIRE_RULE"
    ,schema="SHAMS"
)
public class PerElawaHireRule  implements java.io.Serializable {


     private PerElawaHireRuleId id;
     private PerEmploymentParameter perEmploymentParameter;

    public PerElawaHireRule() {
    }

    public PerElawaHireRule(PerElawaHireRuleId id, PerEmploymentParameter perEmploymentParameter) {
       this.id = id;
       this.perEmploymentParameter = perEmploymentParameter;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="locationCode", column=@Column(name="LOCATION_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="elawaDate", column=@Column(name="ELAWA_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="elawaTypeCode", column=@Column(name="ELAWA_TYPE_CODE", nullable=false, length=2) ), 
        @AttributeOverride(name="employmentSourceCode", column=@Column(name="EMPLOYMENT_SOURCE_CODE", nullable=false, length=5) ) } )
    public PerElawaHireRuleId getId() {
        return this.id;
    }
    
    public void setId(PerElawaHireRuleId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EMPLOYMENT_SOURCE_CODE", nullable=false, insertable=false, updatable=false)
    public PerEmploymentParameter getPerEmploymentParameter() {
        return this.perEmploymentParameter;
    }
    
    public void setPerEmploymentParameter(PerEmploymentParameter perEmploymentParameter) {
        this.perEmploymentParameter = perEmploymentParameter;
    }




}


