package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PerElawaLocCodeRule generated by hbm2java
 */
@Entity
@Table(name="PER_ELAWA_LOC_CODE_RULE"
    ,schema="SHAMS"
)
public class PerElawaLocCodeRule  implements java.io.Serializable {


     private PerElawaLocCodeRuleId id;

    public PerElawaLocCodeRule() {
    }

    public PerElawaLocCodeRule(PerElawaLocCodeRuleId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="locationCode", column=@Column(name="LOCATION_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="elawaTypeCode", column=@Column(name="ELAWA_TYPE_CODE", nullable=false, length=2) ), 
        @AttributeOverride(name="elawaDate", column=@Column(name="ELAWA_DATE", nullable=false, length=7) ), 
        @AttributeOverride(name="locCode", column=@Column(name="LOC_CODE", nullable=false, length=3) ) } )
    public PerElawaLocCodeRuleId getId() {
        return this.id;
    }
    
    public void setId(PerElawaLocCodeRuleId id) {
        this.id = id;
    }




}


