package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerFiscalDegreeCode generated by hbm2java
 */
@Entity
@Table(name="PER_FISCAL_DEGREE_CODE"
    ,schema="SHAMS"
)
public class PerFiscalDegreeCode  implements java.io.Serializable {


     private String fiscalDegreeCode;
     private PerCadreDegreeCode perCadreDegreeCode;
     private String fiscalDegreeName;
     private byte fiscalDegreeOrder;
     private boolean financeFlag;
     private boolean tempFlag;
     private boolean absentFg;
     private boolean delayFg;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private Boolean financeRule;
     private String lawSeq;
     private Set<PerFiscalDegreePromotion> perFiscalDegreePromotionsForHighDegreeCode = new HashSet<PerFiscalDegreePromotion>(0);
     private Set<PerEmploymentMasters> perEmploymentMasterses = new HashSet<PerEmploymentMasters>(0);
     private Set<PerEmpPromotion> perEmpPromotionsForFiscalDegreeCode = new HashSet<PerEmpPromotion>(0);
     private Set<PerPromotionTrans> perPromotionTransesForFiscalDegreeCodeEndSalary = new HashSet<PerPromotionTrans>(0);
     private Set<PerElawaTransaction> perElawaTransactions = new HashSet<PerElawaTransaction>(0);
     private Set<PerEmpPromotion> perEmpPromotionsForFiscalDegreeCodeNew = new HashSet<PerEmpPromotion>(0);
     private Set<PerElawaTransactionReject> perElawaTransactionRejects = new HashSet<PerElawaTransactionReject>(0);
     private PerFiscalDegreeDetail perFiscalDegreeDetailByFiscalDegreeCode;
     private Set<PerFiscalDegreeDetail> perFiscalDegreeDetailsForDegreePeriodicElawa = new HashSet<PerFiscalDegreeDetail>(0);
     private Set<PerGroupDegree> perGroupDegrees = new HashSet<PerGroupDegree>(0);
     private Set<PerFiscalDegreeDetail> perFiscalDegreeDetailsForDegreeEncouragElawa = new HashSet<PerFiscalDegreeDetail>(0);
     private Set<PerFiscalDegreeCodeNew> perFiscalDegreeCodeNews = new HashSet<PerFiscalDegreeCodeNew>(0);
     private Set<PerEmpHistory> perEmpHistories = new HashSet<PerEmpHistory>(0);
     private Set<PayExecutionSpecificEmp> payExecutionSpecificEmps = new HashSet<PayExecutionSpecificEmp>(0);
     private Set<PerEasementTrans> perEasementTranses = new HashSet<PerEasementTrans>(0);
     private Set<PerElawaFiscalDegreeRule> perElawaFiscalDegreeRules = new HashSet<PerElawaFiscalDegreeRule>(0);
     private Set<PerFiscalDegreePromotion> perFiscalDegreePromotionsForFiscalDegreeCode = new HashSet<PerFiscalDegreePromotion>(0);
     private Set<PerJobCode> perJobCodes = new HashSet<PerJobCode>(0);
     private Set<PerPromotionTrans> perPromotionTransesForFiscalDegreeCodeNew = new HashSet<PerPromotionTrans>(0);
     private Set<PerEvalAttributeDetail> perEvalAttributeDetails = new HashSet<PerEvalAttributeDetail>(0);

    public PerFiscalDegreeCode() {
    }

	
    public PerFiscalDegreeCode(String fiscalDegreeCode, PerCadreDegreeCode perCadreDegreeCode, String fiscalDegreeName, byte fiscalDegreeOrder, boolean financeFlag, boolean tempFlag, boolean absentFg, boolean delayFg) {
        this.fiscalDegreeCode = fiscalDegreeCode;
        this.perCadreDegreeCode = perCadreDegreeCode;
        this.fiscalDegreeName = fiscalDegreeName;
        this.fiscalDegreeOrder = fiscalDegreeOrder;
        this.financeFlag = financeFlag;
        this.tempFlag = tempFlag;
        this.absentFg = absentFg;
        this.delayFg = delayFg;
    }
    public PerFiscalDegreeCode(String fiscalDegreeCode, PerCadreDegreeCode perCadreDegreeCode, String fiscalDegreeName, byte fiscalDegreeOrder, boolean financeFlag, boolean tempFlag, boolean absentFg, boolean delayFg, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, Boolean financeRule, String lawSeq, Set<PerFiscalDegreePromotion> perFiscalDegreePromotionsForHighDegreeCode, Set<PerEmploymentMasters> perEmploymentMasterses, Set<PerEmpPromotion> perEmpPromotionsForFiscalDegreeCode, Set<PerPromotionTrans> perPromotionTransesForFiscalDegreeCodeEndSalary, Set<PerElawaTransaction> perElawaTransactions, Set<PerEmpPromotion> perEmpPromotionsForFiscalDegreeCodeNew, Set<PerElawaTransactionReject> perElawaTransactionRejects, PerFiscalDegreeDetail perFiscalDegreeDetailByFiscalDegreeCode, Set<PerFiscalDegreeDetail> perFiscalDegreeDetailsForDegreePeriodicElawa, Set<PerGroupDegree> perGroupDegrees, Set<PerFiscalDegreeDetail> perFiscalDegreeDetailsForDegreeEncouragElawa, Set<PerFiscalDegreeCodeNew> perFiscalDegreeCodeNews, Set<PerEmpHistory> perEmpHistories, Set<PayExecutionSpecificEmp> payExecutionSpecificEmps, Set<PerEasementTrans> perEasementTranses, Set<PerElawaFiscalDegreeRule> perElawaFiscalDegreeRules, Set<PerFiscalDegreePromotion> perFiscalDegreePromotionsForFiscalDegreeCode, Set<PerJobCode> perJobCodes, Set<PerPromotionTrans> perPromotionTransesForFiscalDegreeCodeNew, Set<PerEvalAttributeDetail> perEvalAttributeDetails) {
       this.fiscalDegreeCode = fiscalDegreeCode;
       this.perCadreDegreeCode = perCadreDegreeCode;
       this.fiscalDegreeName = fiscalDegreeName;
       this.fiscalDegreeOrder = fiscalDegreeOrder;
       this.financeFlag = financeFlag;
       this.tempFlag = tempFlag;
       this.absentFg = absentFg;
       this.delayFg = delayFg;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.financeRule = financeRule;
       this.lawSeq = lawSeq;
       this.perFiscalDegreePromotionsForHighDegreeCode = perFiscalDegreePromotionsForHighDegreeCode;
       this.perEmploymentMasterses = perEmploymentMasterses;
       this.perEmpPromotionsForFiscalDegreeCode = perEmpPromotionsForFiscalDegreeCode;
       this.perPromotionTransesForFiscalDegreeCodeEndSalary = perPromotionTransesForFiscalDegreeCodeEndSalary;
       this.perElawaTransactions = perElawaTransactions;
       this.perEmpPromotionsForFiscalDegreeCodeNew = perEmpPromotionsForFiscalDegreeCodeNew;
       this.perElawaTransactionRejects = perElawaTransactionRejects;
       this.perFiscalDegreeDetailByFiscalDegreeCode = perFiscalDegreeDetailByFiscalDegreeCode;
       this.perFiscalDegreeDetailsForDegreePeriodicElawa = perFiscalDegreeDetailsForDegreePeriodicElawa;
       this.perGroupDegrees = perGroupDegrees;
       this.perFiscalDegreeDetailsForDegreeEncouragElawa = perFiscalDegreeDetailsForDegreeEncouragElawa;
       this.perFiscalDegreeCodeNews = perFiscalDegreeCodeNews;
       this.perEmpHistories = perEmpHistories;
       this.payExecutionSpecificEmps = payExecutionSpecificEmps;
       this.perEasementTranses = perEasementTranses;
       this.perElawaFiscalDegreeRules = perElawaFiscalDegreeRules;
       this.perFiscalDegreePromotionsForFiscalDegreeCode = perFiscalDegreePromotionsForFiscalDegreeCode;
       this.perJobCodes = perJobCodes;
       this.perPromotionTransesForFiscalDegreeCodeNew = perPromotionTransesForFiscalDegreeCodeNew;
       this.perEvalAttributeDetails = perEvalAttributeDetails;
    }
   
     @Id 

    
    @Column(name="FISCAL_DEGREE_CODE", unique=true, nullable=false, length=3)
    public String getFiscalDegreeCode() {
        return this.fiscalDegreeCode;
    }
    
    public void setFiscalDegreeCode(String fiscalDegreeCode) {
        this.fiscalDegreeCode = fiscalDegreeCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="CADRE_DEGREE_CODE", nullable=false)
    public PerCadreDegreeCode getPerCadreDegreeCode() {
        return this.perCadreDegreeCode;
    }
    
    public void setPerCadreDegreeCode(PerCadreDegreeCode perCadreDegreeCode) {
        this.perCadreDegreeCode = perCadreDegreeCode;
    }

    
    @Column(name="FISCAL_DEGREE_NAME", nullable=false, length=50)
    public String getFiscalDegreeName() {
        return this.fiscalDegreeName;
    }
    
    public void setFiscalDegreeName(String fiscalDegreeName) {
        this.fiscalDegreeName = fiscalDegreeName;
    }

    
    @Column(name="FISCAL_DEGREE_ORDER", nullable=false, precision=2, scale=0)
    public byte getFiscalDegreeOrder() {
        return this.fiscalDegreeOrder;
    }
    
    public void setFiscalDegreeOrder(byte fiscalDegreeOrder) {
        this.fiscalDegreeOrder = fiscalDegreeOrder;
    }

    
    @Column(name="FINANCE_FLAG", nullable=false, precision=1, scale=0)
    public boolean isFinanceFlag() {
        return this.financeFlag;
    }
    
    public void setFinanceFlag(boolean financeFlag) {
        this.financeFlag = financeFlag;
    }

    
    @Column(name="TEMP_FLAG", nullable=false, precision=1, scale=0)
    public boolean isTempFlag() {
        return this.tempFlag;
    }
    
    public void setTempFlag(boolean tempFlag) {
        this.tempFlag = tempFlag;
    }

    
    @Column(name="ABSENT_FG", nullable=false, precision=1, scale=0)
    public boolean isAbsentFg() {
        return this.absentFg;
    }
    
    public void setAbsentFg(boolean absentFg) {
        this.absentFg = absentFg;
    }

    
    @Column(name="DELAY_FG", nullable=false, precision=1, scale=0)
    public boolean isDelayFg() {
        return this.delayFg;
    }
    
    public void setDelayFg(boolean delayFg) {
        this.delayFg = delayFg;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

    
    @Column(name="FINANCE_RULE", precision=1, scale=0)
    public Boolean getFinanceRule() {
        return this.financeRule;
    }
    
    public void setFinanceRule(Boolean financeRule) {
        this.financeRule = financeRule;
    }

    
    @Column(name="LAW_SEQ", length=3)
    public String getLawSeq() {
        return this.lawSeq;
    }
    
    public void setLawSeq(String lawSeq) {
        this.lawSeq = lawSeq;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeByHighDegreeCode")
    public Set<PerFiscalDegreePromotion> getPerFiscalDegreePromotionsForHighDegreeCode() {
        return this.perFiscalDegreePromotionsForHighDegreeCode;
    }
    
    public void setPerFiscalDegreePromotionsForHighDegreeCode(Set<PerFiscalDegreePromotion> perFiscalDegreePromotionsForHighDegreeCode) {
        this.perFiscalDegreePromotionsForHighDegreeCode = perFiscalDegreePromotionsForHighDegreeCode;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCode")
    public Set<PerEmploymentMasters> getPerEmploymentMasterses() {
        return this.perEmploymentMasterses;
    }
    
    public void setPerEmploymentMasterses(Set<PerEmploymentMasters> perEmploymentMasterses) {
        this.perEmploymentMasterses = perEmploymentMasterses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeByFiscalDegreeCode")
    public Set<PerEmpPromotion> getPerEmpPromotionsForFiscalDegreeCode() {
        return this.perEmpPromotionsForFiscalDegreeCode;
    }
    
    public void setPerEmpPromotionsForFiscalDegreeCode(Set<PerEmpPromotion> perEmpPromotionsForFiscalDegreeCode) {
        this.perEmpPromotionsForFiscalDegreeCode = perEmpPromotionsForFiscalDegreeCode;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeByFiscalDegreeCodeEndSalary")
    public Set<PerPromotionTrans> getPerPromotionTransesForFiscalDegreeCodeEndSalary() {
        return this.perPromotionTransesForFiscalDegreeCodeEndSalary;
    }
    
    public void setPerPromotionTransesForFiscalDegreeCodeEndSalary(Set<PerPromotionTrans> perPromotionTransesForFiscalDegreeCodeEndSalary) {
        this.perPromotionTransesForFiscalDegreeCodeEndSalary = perPromotionTransesForFiscalDegreeCodeEndSalary;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCode")
    public Set<PerElawaTransaction> getPerElawaTransactions() {
        return this.perElawaTransactions;
    }
    
    public void setPerElawaTransactions(Set<PerElawaTransaction> perElawaTransactions) {
        this.perElawaTransactions = perElawaTransactions;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeByFiscalDegreeCodeNew")
    public Set<PerEmpPromotion> getPerEmpPromotionsForFiscalDegreeCodeNew() {
        return this.perEmpPromotionsForFiscalDegreeCodeNew;
    }
    
    public void setPerEmpPromotionsForFiscalDegreeCodeNew(Set<PerEmpPromotion> perEmpPromotionsForFiscalDegreeCodeNew) {
        this.perEmpPromotionsForFiscalDegreeCodeNew = perEmpPromotionsForFiscalDegreeCodeNew;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCode")
    public Set<PerElawaTransactionReject> getPerElawaTransactionRejects() {
        return this.perElawaTransactionRejects;
    }
    
    public void setPerElawaTransactionRejects(Set<PerElawaTransactionReject> perElawaTransactionRejects) {
        this.perElawaTransactionRejects = perElawaTransactionRejects;
    }

@OneToOne(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeByFiscalDegreeCode")
    public PerFiscalDegreeDetail getPerFiscalDegreeDetailByFiscalDegreeCode() {
        return this.perFiscalDegreeDetailByFiscalDegreeCode;
    }
    
    public void setPerFiscalDegreeDetailByFiscalDegreeCode(PerFiscalDegreeDetail perFiscalDegreeDetailByFiscalDegreeCode) {
        this.perFiscalDegreeDetailByFiscalDegreeCode = perFiscalDegreeDetailByFiscalDegreeCode;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeByDegreePeriodicElawa")
    public Set<PerFiscalDegreeDetail> getPerFiscalDegreeDetailsForDegreePeriodicElawa() {
        return this.perFiscalDegreeDetailsForDegreePeriodicElawa;
    }
    
    public void setPerFiscalDegreeDetailsForDegreePeriodicElawa(Set<PerFiscalDegreeDetail> perFiscalDegreeDetailsForDegreePeriodicElawa) {
        this.perFiscalDegreeDetailsForDegreePeriodicElawa = perFiscalDegreeDetailsForDegreePeriodicElawa;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCode")
    public Set<PerGroupDegree> getPerGroupDegrees() {
        return this.perGroupDegrees;
    }
    
    public void setPerGroupDegrees(Set<PerGroupDegree> perGroupDegrees) {
        this.perGroupDegrees = perGroupDegrees;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeByDegreeEncouragElawa")
    public Set<PerFiscalDegreeDetail> getPerFiscalDegreeDetailsForDegreeEncouragElawa() {
        return this.perFiscalDegreeDetailsForDegreeEncouragElawa;
    }
    
    public void setPerFiscalDegreeDetailsForDegreeEncouragElawa(Set<PerFiscalDegreeDetail> perFiscalDegreeDetailsForDegreeEncouragElawa) {
        this.perFiscalDegreeDetailsForDegreeEncouragElawa = perFiscalDegreeDetailsForDegreeEncouragElawa;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCode")
    public Set<PerFiscalDegreeCodeNew> getPerFiscalDegreeCodeNews() {
        return this.perFiscalDegreeCodeNews;
    }
    
    public void setPerFiscalDegreeCodeNews(Set<PerFiscalDegreeCodeNew> perFiscalDegreeCodeNews) {
        this.perFiscalDegreeCodeNews = perFiscalDegreeCodeNews;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCode")
    public Set<PerEmpHistory> getPerEmpHistories() {
        return this.perEmpHistories;
    }
    
    public void setPerEmpHistories(Set<PerEmpHistory> perEmpHistories) {
        this.perEmpHistories = perEmpHistories;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCode")
    public Set<PayExecutionSpecificEmp> getPayExecutionSpecificEmps() {
        return this.payExecutionSpecificEmps;
    }
    
    public void setPayExecutionSpecificEmps(Set<PayExecutionSpecificEmp> payExecutionSpecificEmps) {
        this.payExecutionSpecificEmps = payExecutionSpecificEmps;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCode")
    public Set<PerEasementTrans> getPerEasementTranses() {
        return this.perEasementTranses;
    }
    
    public void setPerEasementTranses(Set<PerEasementTrans> perEasementTranses) {
        this.perEasementTranses = perEasementTranses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCode")
    public Set<PerElawaFiscalDegreeRule> getPerElawaFiscalDegreeRules() {
        return this.perElawaFiscalDegreeRules;
    }
    
    public void setPerElawaFiscalDegreeRules(Set<PerElawaFiscalDegreeRule> perElawaFiscalDegreeRules) {
        this.perElawaFiscalDegreeRules = perElawaFiscalDegreeRules;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeByFiscalDegreeCode")
    public Set<PerFiscalDegreePromotion> getPerFiscalDegreePromotionsForFiscalDegreeCode() {
        return this.perFiscalDegreePromotionsForFiscalDegreeCode;
    }
    
    public void setPerFiscalDegreePromotionsForFiscalDegreeCode(Set<PerFiscalDegreePromotion> perFiscalDegreePromotionsForFiscalDegreeCode) {
        this.perFiscalDegreePromotionsForFiscalDegreeCode = perFiscalDegreePromotionsForFiscalDegreeCode;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCode")
    public Set<PerJobCode> getPerJobCodes() {
        return this.perJobCodes;
    }
    
    public void setPerJobCodes(Set<PerJobCode> perJobCodes) {
        this.perJobCodes = perJobCodes;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeByFiscalDegreeCodeNew")
    public Set<PerPromotionTrans> getPerPromotionTransesForFiscalDegreeCodeNew() {
        return this.perPromotionTransesForFiscalDegreeCodeNew;
    }
    
    public void setPerPromotionTransesForFiscalDegreeCodeNew(Set<PerPromotionTrans> perPromotionTransesForFiscalDegreeCodeNew) {
        this.perPromotionTransesForFiscalDegreeCodeNew = perPromotionTransesForFiscalDegreeCodeNew;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCode")
    public Set<PerEvalAttributeDetail> getPerEvalAttributeDetails() {
        return this.perEvalAttributeDetails;
    }
    
    public void setPerEvalAttributeDetails(Set<PerEvalAttributeDetail> perEvalAttributeDetails) {
        this.perEvalAttributeDetails = perEvalAttributeDetails;
    }




}


