package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerFiscalDegreeCodeNew generated by hbm2java
 */
@Entity
@Table(name="PER_FISCAL_DEGREE_CODE_NEW"
    ,schema="SHAMS"
)
public class PerFiscalDegreeCodeNew  implements java.io.Serializable {


     private String fiscalDegreeCodeNew;
     private PerFiscalDegreeCode perFiscalDegreeCode;
     private PerJobLaw perJobLaw;
     private PerCadreDegreeCode perCadreDegreeCode;
     private String fiscalDegreeNameNew;
     private byte fiscalDegreeOrder;
     private boolean financeFlag;
     private boolean tempFlag;
     private boolean absentFg;
     private boolean delayFg;
     private Boolean financeRule;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private Set<PerEmploymentMasters> perEmploymentMasterses = new HashSet<PerEmploymentMasters>(0);
     private Set<PerPromotionTransNew> perPromotionTransNewsForFiscalDegreeCodeNew = new HashSet<PerPromotionTransNew>(0);
     private Set<PerElawaTransactionReject> perElawaTransactionRejects = new HashSet<PerElawaTransactionReject>(0);
     private Set<PerEmpPromotionRejectNew> perEmpPromotionRejectNews = new HashSet<PerEmpPromotionRejectNew>(0);
     private Set<PerElawaTransaction> perElawaTransactions = new HashSet<PerElawaTransaction>(0);
     private Set<PerEmpPromotionNew> perEmpPromotionNewsForFiscalDegreeCodeNew = new HashSet<PerEmpPromotionNew>(0);
     private Set<PerPromotionTransNew> perPromotionTransNewsForFiscalDegreeCodeNewNew = new HashSet<PerPromotionTransNew>(0);
     private Set<PerEasementTrans> perEasementTranses = new HashSet<PerEasementTrans>(0);
     private Set<PerFiscalDegreePromotionN> perFiscalDegreePromotionNs = new HashSet<PerFiscalDegreePromotionN>(0);
     private Set<PerEmpPromotionNew> perEmpPromotionNewsForFiscalDegreeCodeNewNew = new HashSet<PerEmpPromotionNew>(0);
     private Set<PerEvalAttributeDetail> perEvalAttributeDetails = new HashSet<PerEvalAttributeDetail>(0);
     private Set<PerPromotionTransNew> perPromotionTransNewsForFiscalDegreeCodeNewEndsal = new HashSet<PerPromotionTransNew>(0);
     private Set<PerPromotionGradeRuleN> perPromotionGradeRuleNs = new HashSet<PerPromotionGradeRuleN>(0);
     private Set<PerElawaFiscalDegreeRuleN> perElawaFiscalDegreeRuleNs = new HashSet<PerElawaFiscalDegreeRuleN>(0);
     private Set<PerEmpHistory> perEmpHistories = new HashSet<PerEmpHistory>(0);
     private Set<PerGroupDegreeNew> perGroupDegreeNews = new HashSet<PerGroupDegreeNew>(0);
     private PerFiscalDegreeDetailNew perFiscalDegreeDetailNew;
     private Set<PerJobCode> perJobCodes = new HashSet<PerJobCode>(0);

    public PerFiscalDegreeCodeNew() {
    }

	
    public PerFiscalDegreeCodeNew(String fiscalDegreeCodeNew, PerCadreDegreeCode perCadreDegreeCode, String fiscalDegreeNameNew, byte fiscalDegreeOrder, boolean financeFlag, boolean tempFlag, boolean absentFg, boolean delayFg) {
        this.fiscalDegreeCodeNew = fiscalDegreeCodeNew;
        this.perCadreDegreeCode = perCadreDegreeCode;
        this.fiscalDegreeNameNew = fiscalDegreeNameNew;
        this.fiscalDegreeOrder = fiscalDegreeOrder;
        this.financeFlag = financeFlag;
        this.tempFlag = tempFlag;
        this.absentFg = absentFg;
        this.delayFg = delayFg;
    }
    public PerFiscalDegreeCodeNew(String fiscalDegreeCodeNew, PerFiscalDegreeCode perFiscalDegreeCode, PerJobLaw perJobLaw, PerCadreDegreeCode perCadreDegreeCode, String fiscalDegreeNameNew, byte fiscalDegreeOrder, boolean financeFlag, boolean tempFlag, boolean absentFg, boolean delayFg, Boolean financeRule, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, Set<PerEmploymentMasters> perEmploymentMasterses, Set<PerPromotionTransNew> perPromotionTransNewsForFiscalDegreeCodeNew, Set<PerElawaTransactionReject> perElawaTransactionRejects, Set<PerEmpPromotionRejectNew> perEmpPromotionRejectNews, Set<PerElawaTransaction> perElawaTransactions, Set<PerEmpPromotionNew> perEmpPromotionNewsForFiscalDegreeCodeNew, Set<PerPromotionTransNew> perPromotionTransNewsForFiscalDegreeCodeNewNew, Set<PerEasementTrans> perEasementTranses, Set<PerFiscalDegreePromotionN> perFiscalDegreePromotionNs, Set<PerEmpPromotionNew> perEmpPromotionNewsForFiscalDegreeCodeNewNew, Set<PerEvalAttributeDetail> perEvalAttributeDetails, Set<PerPromotionTransNew> perPromotionTransNewsForFiscalDegreeCodeNewEndsal, Set<PerPromotionGradeRuleN> perPromotionGradeRuleNs, Set<PerElawaFiscalDegreeRuleN> perElawaFiscalDegreeRuleNs, Set<PerEmpHistory> perEmpHistories, Set<PerGroupDegreeNew> perGroupDegreeNews, PerFiscalDegreeDetailNew perFiscalDegreeDetailNew, Set<PerJobCode> perJobCodes) {
       this.fiscalDegreeCodeNew = fiscalDegreeCodeNew;
       this.perFiscalDegreeCode = perFiscalDegreeCode;
       this.perJobLaw = perJobLaw;
       this.perCadreDegreeCode = perCadreDegreeCode;
       this.fiscalDegreeNameNew = fiscalDegreeNameNew;
       this.fiscalDegreeOrder = fiscalDegreeOrder;
       this.financeFlag = financeFlag;
       this.tempFlag = tempFlag;
       this.absentFg = absentFg;
       this.delayFg = delayFg;
       this.financeRule = financeRule;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.perEmploymentMasterses = perEmploymentMasterses;
       this.perPromotionTransNewsForFiscalDegreeCodeNew = perPromotionTransNewsForFiscalDegreeCodeNew;
       this.perElawaTransactionRejects = perElawaTransactionRejects;
       this.perEmpPromotionRejectNews = perEmpPromotionRejectNews;
       this.perElawaTransactions = perElawaTransactions;
       this.perEmpPromotionNewsForFiscalDegreeCodeNew = perEmpPromotionNewsForFiscalDegreeCodeNew;
       this.perPromotionTransNewsForFiscalDegreeCodeNewNew = perPromotionTransNewsForFiscalDegreeCodeNewNew;
       this.perEasementTranses = perEasementTranses;
       this.perFiscalDegreePromotionNs = perFiscalDegreePromotionNs;
       this.perEmpPromotionNewsForFiscalDegreeCodeNewNew = perEmpPromotionNewsForFiscalDegreeCodeNewNew;
       this.perEvalAttributeDetails = perEvalAttributeDetails;
       this.perPromotionTransNewsForFiscalDegreeCodeNewEndsal = perPromotionTransNewsForFiscalDegreeCodeNewEndsal;
       this.perPromotionGradeRuleNs = perPromotionGradeRuleNs;
       this.perElawaFiscalDegreeRuleNs = perElawaFiscalDegreeRuleNs;
       this.perEmpHistories = perEmpHistories;
       this.perGroupDegreeNews = perGroupDegreeNews;
       this.perFiscalDegreeDetailNew = perFiscalDegreeDetailNew;
       this.perJobCodes = perJobCodes;
    }
   
     @Id 

    
    @Column(name="FISCAL_DEGREE_CODE_NEW", unique=true, nullable=false, length=3)
    public String getFiscalDegreeCodeNew() {
        return this.fiscalDegreeCodeNew;
    }
    
    public void setFiscalDegreeCodeNew(String fiscalDegreeCodeNew) {
        this.fiscalDegreeCodeNew = fiscalDegreeCodeNew;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="FISCAL_DEGREE_CODE")
    public PerFiscalDegreeCode getPerFiscalDegreeCode() {
        return this.perFiscalDegreeCode;
    }
    
    public void setPerFiscalDegreeCode(PerFiscalDegreeCode perFiscalDegreeCode) {
        this.perFiscalDegreeCode = perFiscalDegreeCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="LAW_SEQ")
    public PerJobLaw getPerJobLaw() {
        return this.perJobLaw;
    }
    
    public void setPerJobLaw(PerJobLaw perJobLaw) {
        this.perJobLaw = perJobLaw;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="CADRE_DEGREE_CODE", nullable=false)
    public PerCadreDegreeCode getPerCadreDegreeCode() {
        return this.perCadreDegreeCode;
    }
    
    public void setPerCadreDegreeCode(PerCadreDegreeCode perCadreDegreeCode) {
        this.perCadreDegreeCode = perCadreDegreeCode;
    }

    
    @Column(name="FISCAL_DEGREE_NAME_NEW", nullable=false, length=50)
    public String getFiscalDegreeNameNew() {
        return this.fiscalDegreeNameNew;
    }
    
    public void setFiscalDegreeNameNew(String fiscalDegreeNameNew) {
        this.fiscalDegreeNameNew = fiscalDegreeNameNew;
    }

    
    @Column(name="FISCAL_DEGREE_ORDER", nullable=false, precision=2, scale=0)
    public byte getFiscalDegreeOrder() {
        return this.fiscalDegreeOrder;
    }
    
    public void setFiscalDegreeOrder(byte fiscalDegreeOrder) {
        this.fiscalDegreeOrder = fiscalDegreeOrder;
    }

    
    @Column(name="FINANCE_FLAG", nullable=false, precision=1, scale=0)
    public boolean isFinanceFlag() {
        return this.financeFlag;
    }
    
    public void setFinanceFlag(boolean financeFlag) {
        this.financeFlag = financeFlag;
    }

    
    @Column(name="TEMP_FLAG", nullable=false, precision=1, scale=0)
    public boolean isTempFlag() {
        return this.tempFlag;
    }
    
    public void setTempFlag(boolean tempFlag) {
        this.tempFlag = tempFlag;
    }

    
    @Column(name="ABSENT_FG", nullable=false, precision=1, scale=0)
    public boolean isAbsentFg() {
        return this.absentFg;
    }
    
    public void setAbsentFg(boolean absentFg) {
        this.absentFg = absentFg;
    }

    
    @Column(name="DELAY_FG", nullable=false, precision=1, scale=0)
    public boolean isDelayFg() {
        return this.delayFg;
    }
    
    public void setDelayFg(boolean delayFg) {
        this.delayFg = delayFg;
    }

    
    @Column(name="FINANCE_RULE", precision=1, scale=0)
    public Boolean getFinanceRule() {
        return this.financeRule;
    }
    
    public void setFinanceRule(Boolean financeRule) {
        this.financeRule = financeRule;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeNew")
    public Set<PerEmploymentMasters> getPerEmploymentMasterses() {
        return this.perEmploymentMasterses;
    }
    
    public void setPerEmploymentMasterses(Set<PerEmploymentMasters> perEmploymentMasterses) {
        this.perEmploymentMasterses = perEmploymentMasterses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeNewByFiscalDegreeCodeNew")
    public Set<PerPromotionTransNew> getPerPromotionTransNewsForFiscalDegreeCodeNew() {
        return this.perPromotionTransNewsForFiscalDegreeCodeNew;
    }
    
    public void setPerPromotionTransNewsForFiscalDegreeCodeNew(Set<PerPromotionTransNew> perPromotionTransNewsForFiscalDegreeCodeNew) {
        this.perPromotionTransNewsForFiscalDegreeCodeNew = perPromotionTransNewsForFiscalDegreeCodeNew;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeNew")
    public Set<PerElawaTransactionReject> getPerElawaTransactionRejects() {
        return this.perElawaTransactionRejects;
    }
    
    public void setPerElawaTransactionRejects(Set<PerElawaTransactionReject> perElawaTransactionRejects) {
        this.perElawaTransactionRejects = perElawaTransactionRejects;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeNew")
    public Set<PerEmpPromotionRejectNew> getPerEmpPromotionRejectNews() {
        return this.perEmpPromotionRejectNews;
    }
    
    public void setPerEmpPromotionRejectNews(Set<PerEmpPromotionRejectNew> perEmpPromotionRejectNews) {
        this.perEmpPromotionRejectNews = perEmpPromotionRejectNews;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeNew")
    public Set<PerElawaTransaction> getPerElawaTransactions() {
        return this.perElawaTransactions;
    }
    
    public void setPerElawaTransactions(Set<PerElawaTransaction> perElawaTransactions) {
        this.perElawaTransactions = perElawaTransactions;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeNewByFiscalDegreeCodeNew")
    public Set<PerEmpPromotionNew> getPerEmpPromotionNewsForFiscalDegreeCodeNew() {
        return this.perEmpPromotionNewsForFiscalDegreeCodeNew;
    }
    
    public void setPerEmpPromotionNewsForFiscalDegreeCodeNew(Set<PerEmpPromotionNew> perEmpPromotionNewsForFiscalDegreeCodeNew) {
        this.perEmpPromotionNewsForFiscalDegreeCodeNew = perEmpPromotionNewsForFiscalDegreeCodeNew;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeNewByFiscalDegreeCodeNewNew")
    public Set<PerPromotionTransNew> getPerPromotionTransNewsForFiscalDegreeCodeNewNew() {
        return this.perPromotionTransNewsForFiscalDegreeCodeNewNew;
    }
    
    public void setPerPromotionTransNewsForFiscalDegreeCodeNewNew(Set<PerPromotionTransNew> perPromotionTransNewsForFiscalDegreeCodeNewNew) {
        this.perPromotionTransNewsForFiscalDegreeCodeNewNew = perPromotionTransNewsForFiscalDegreeCodeNewNew;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeNew")
    public Set<PerEasementTrans> getPerEasementTranses() {
        return this.perEasementTranses;
    }
    
    public void setPerEasementTranses(Set<PerEasementTrans> perEasementTranses) {
        this.perEasementTranses = perEasementTranses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeNew")
    public Set<PerFiscalDegreePromotionN> getPerFiscalDegreePromotionNs() {
        return this.perFiscalDegreePromotionNs;
    }
    
    public void setPerFiscalDegreePromotionNs(Set<PerFiscalDegreePromotionN> perFiscalDegreePromotionNs) {
        this.perFiscalDegreePromotionNs = perFiscalDegreePromotionNs;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeNewByFiscalDegreeCodeNewNew")
    public Set<PerEmpPromotionNew> getPerEmpPromotionNewsForFiscalDegreeCodeNewNew() {
        return this.perEmpPromotionNewsForFiscalDegreeCodeNewNew;
    }
    
    public void setPerEmpPromotionNewsForFiscalDegreeCodeNewNew(Set<PerEmpPromotionNew> perEmpPromotionNewsForFiscalDegreeCodeNewNew) {
        this.perEmpPromotionNewsForFiscalDegreeCodeNewNew = perEmpPromotionNewsForFiscalDegreeCodeNewNew;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeNew")
    public Set<PerEvalAttributeDetail> getPerEvalAttributeDetails() {
        return this.perEvalAttributeDetails;
    }
    
    public void setPerEvalAttributeDetails(Set<PerEvalAttributeDetail> perEvalAttributeDetails) {
        this.perEvalAttributeDetails = perEvalAttributeDetails;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeNewByFiscalDegreeCodeNewEndsal")
    public Set<PerPromotionTransNew> getPerPromotionTransNewsForFiscalDegreeCodeNewEndsal() {
        return this.perPromotionTransNewsForFiscalDegreeCodeNewEndsal;
    }
    
    public void setPerPromotionTransNewsForFiscalDegreeCodeNewEndsal(Set<PerPromotionTransNew> perPromotionTransNewsForFiscalDegreeCodeNewEndsal) {
        this.perPromotionTransNewsForFiscalDegreeCodeNewEndsal = perPromotionTransNewsForFiscalDegreeCodeNewEndsal;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeNew")
    public Set<PerPromotionGradeRuleN> getPerPromotionGradeRuleNs() {
        return this.perPromotionGradeRuleNs;
    }
    
    public void setPerPromotionGradeRuleNs(Set<PerPromotionGradeRuleN> perPromotionGradeRuleNs) {
        this.perPromotionGradeRuleNs = perPromotionGradeRuleNs;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeNew")
    public Set<PerElawaFiscalDegreeRuleN> getPerElawaFiscalDegreeRuleNs() {
        return this.perElawaFiscalDegreeRuleNs;
    }
    
    public void setPerElawaFiscalDegreeRuleNs(Set<PerElawaFiscalDegreeRuleN> perElawaFiscalDegreeRuleNs) {
        this.perElawaFiscalDegreeRuleNs = perElawaFiscalDegreeRuleNs;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeNew")
    public Set<PerEmpHistory> getPerEmpHistories() {
        return this.perEmpHistories;
    }
    
    public void setPerEmpHistories(Set<PerEmpHistory> perEmpHistories) {
        this.perEmpHistories = perEmpHistories;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeNew")
    public Set<PerGroupDegreeNew> getPerGroupDegreeNews() {
        return this.perGroupDegreeNews;
    }
    
    public void setPerGroupDegreeNews(Set<PerGroupDegreeNew> perGroupDegreeNews) {
        this.perGroupDegreeNews = perGroupDegreeNews;
    }

@OneToOne(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeNew")
    public PerFiscalDegreeDetailNew getPerFiscalDegreeDetailNew() {
        return this.perFiscalDegreeDetailNew;
    }
    
    public void setPerFiscalDegreeDetailNew(PerFiscalDegreeDetailNew perFiscalDegreeDetailNew) {
        this.perFiscalDegreeDetailNew = perFiscalDegreeDetailNew;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perFiscalDegreeCodeNew")
    public Set<PerJobCode> getPerJobCodes() {
        return this.perJobCodes;
    }
    
    public void setPerJobCodes(Set<PerJobCode> perJobCodes) {
        this.perJobCodes = perJobCodes;
    }




}


