package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PerFiscalDegreePromotionNId generated by hbm2java
 */
@Embeddable
public class PerFiscalDegreePromotionNId  implements java.io.Serializable {


     private String fiscalDegreeCodeNew;
     private String highDegreeCode;

    public PerFiscalDegreePromotionNId() {
    }

    public PerFiscalDegreePromotionNId(String fiscalDegreeCodeNew, String highDegreeCode) {
       this.fiscalDegreeCodeNew = fiscalDegreeCodeNew;
       this.highDegreeCode = highDegreeCode;
    }
   


    @Column(name="FISCAL_DEGREE_CODE_NEW", nullable=false, length=3)
    public String getFiscalDegreeCodeNew() {
        return this.fiscalDegreeCodeNew;
    }
    
    public void setFiscalDegreeCodeNew(String fiscalDegreeCodeNew) {
        this.fiscalDegreeCodeNew = fiscalDegreeCodeNew;
    }


    @Column(name="HIGH_DEGREE_CODE", nullable=false, length=3)
    public String getHighDegreeCode() {
        return this.highDegreeCode;
    }
    
    public void setHighDegreeCode(String highDegreeCode) {
        this.highDegreeCode = highDegreeCode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PerFiscalDegreePromotionNId) ) return false;
		 PerFiscalDegreePromotionNId castOther = ( PerFiscalDegreePromotionNId ) other; 
         
		 return ( (this.getFiscalDegreeCodeNew()==castOther.getFiscalDegreeCodeNew()) || ( this.getFiscalDegreeCodeNew()!=null && castOther.getFiscalDegreeCodeNew()!=null && this.getFiscalDegreeCodeNew().equals(castOther.getFiscalDegreeCodeNew()) ) )
 && ( (this.getHighDegreeCode()==castOther.getHighDegreeCode()) || ( this.getHighDegreeCode()!=null && castOther.getHighDegreeCode()!=null && this.getHighDegreeCode().equals(castOther.getHighDegreeCode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFiscalDegreeCodeNew() == null ? 0 : this.getFiscalDegreeCodeNew().hashCode() );
         result = 37 * result + ( getHighDegreeCode() == null ? 0 : this.getHighDegreeCode().hashCode() );
         return result;
   }   


}


