package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerFiscalDegreePromotionN generated by hbm2java
 */
@Entity
@Table(name="PER_FISCAL_DEGREE_PROMOTION_N"
    ,schema="SHAMS"
)
public class PerFiscalDegreePromotionN  implements java.io.Serializable {


     private PerFiscalDegreePromotionNId id;
     private PerFiscalDegreeCodeNew perFiscalDegreeCodeNew;
     private byte promotionRate;
     private Date recordUpdateDate;
     private String recordUpdateUser;
     private String notes;
     private Date recordCreateDate;
     private BigDecimal promotionPercent;
     private String recordCreateUser;

    public PerFiscalDegreePromotionN() {
    }

	
    public PerFiscalDegreePromotionN(PerFiscalDegreePromotionNId id, PerFiscalDegreeCodeNew perFiscalDegreeCodeNew, byte promotionRate) {
        this.id = id;
        this.perFiscalDegreeCodeNew = perFiscalDegreeCodeNew;
        this.promotionRate = promotionRate;
    }
    public PerFiscalDegreePromotionN(PerFiscalDegreePromotionNId id, PerFiscalDegreeCodeNew perFiscalDegreeCodeNew, byte promotionRate, Date recordUpdateDate, String recordUpdateUser, String notes, Date recordCreateDate, BigDecimal promotionPercent, String recordCreateUser) {
       this.id = id;
       this.perFiscalDegreeCodeNew = perFiscalDegreeCodeNew;
       this.promotionRate = promotionRate;
       this.recordUpdateDate = recordUpdateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.notes = notes;
       this.recordCreateDate = recordCreateDate;
       this.promotionPercent = promotionPercent;
       this.recordCreateUser = recordCreateUser;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fiscalDegreeCodeNew", column=@Column(name="FISCAL_DEGREE_CODE_NEW", nullable=false, length=3) ), 
        @AttributeOverride(name="highDegreeCode", column=@Column(name="HIGH_DEGREE_CODE", nullable=false, length=3) ) } )
    public PerFiscalDegreePromotionNId getId() {
        return this.id;
    }
    
    public void setId(PerFiscalDegreePromotionNId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="FISCAL_DEGREE_CODE_NEW", nullable=false, insertable=false, updatable=false)
    public PerFiscalDegreeCodeNew getPerFiscalDegreeCodeNew() {
        return this.perFiscalDegreeCodeNew;
    }
    
    public void setPerFiscalDegreeCodeNew(PerFiscalDegreeCodeNew perFiscalDegreeCodeNew) {
        this.perFiscalDegreeCodeNew = perFiscalDegreeCodeNew;
    }

    
    @Column(name="PROMOTION_RATE", nullable=false, precision=2, scale=0)
    public byte getPromotionRate() {
        return this.promotionRate;
    }
    
    public void setPromotionRate(byte promotionRate) {
        this.promotionRate = promotionRate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    
    @Column(name="NOTES", length=100)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="PROMOTION_PERCENT", precision=5)
    public BigDecimal getPromotionPercent() {
        return this.promotionPercent;
    }
    
    public void setPromotionPercent(BigDecimal promotionPercent) {
        this.promotionPercent = promotionPercent;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }




}


