package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerFiscalDegreePromotion generated by hbm2java
 */
@Entity
@Table(name="PER_FISCAL_DEGREE_PROMOTION"
    ,schema="SHAMS"
)
public class PerFiscalDegreePromotion  implements java.io.Serializable {


     private PerFiscalDegreePromotionId id;
     private PerFiscalDegreeCode perFiscalDegreeCodeByHighDegreeCode;
     private PerFiscalDegreeCode perFiscalDegreeCodeByFiscalDegreeCode;
     private byte promotionRate;
     private BigDecimal promotionPercent;
     private String notes;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;

    public PerFiscalDegreePromotion() {
    }

	
    public PerFiscalDegreePromotion(PerFiscalDegreePromotionId id, PerFiscalDegreeCode perFiscalDegreeCodeByHighDegreeCode, PerFiscalDegreeCode perFiscalDegreeCodeByFiscalDegreeCode, byte promotionRate) {
        this.id = id;
        this.perFiscalDegreeCodeByHighDegreeCode = perFiscalDegreeCodeByHighDegreeCode;
        this.perFiscalDegreeCodeByFiscalDegreeCode = perFiscalDegreeCodeByFiscalDegreeCode;
        this.promotionRate = promotionRate;
    }
    public PerFiscalDegreePromotion(PerFiscalDegreePromotionId id, PerFiscalDegreeCode perFiscalDegreeCodeByHighDegreeCode, PerFiscalDegreeCode perFiscalDegreeCodeByFiscalDegreeCode, byte promotionRate, BigDecimal promotionPercent, String notes, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate) {
       this.id = id;
       this.perFiscalDegreeCodeByHighDegreeCode = perFiscalDegreeCodeByHighDegreeCode;
       this.perFiscalDegreeCodeByFiscalDegreeCode = perFiscalDegreeCodeByFiscalDegreeCode;
       this.promotionRate = promotionRate;
       this.promotionPercent = promotionPercent;
       this.notes = notes;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="fiscalDegreeCode", column=@Column(name="FISCAL_DEGREE_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="highDegreeCode", column=@Column(name="HIGH_DEGREE_CODE", nullable=false, length=3) ) } )
    public PerFiscalDegreePromotionId getId() {
        return this.id;
    }
    
    public void setId(PerFiscalDegreePromotionId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="HIGH_DEGREE_CODE", nullable=false, insertable=false, updatable=false)
    public PerFiscalDegreeCode getPerFiscalDegreeCodeByHighDegreeCode() {
        return this.perFiscalDegreeCodeByHighDegreeCode;
    }
    
    public void setPerFiscalDegreeCodeByHighDegreeCode(PerFiscalDegreeCode perFiscalDegreeCodeByHighDegreeCode) {
        this.perFiscalDegreeCodeByHighDegreeCode = perFiscalDegreeCodeByHighDegreeCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="FISCAL_DEGREE_CODE", nullable=false, insertable=false, updatable=false)
    public PerFiscalDegreeCode getPerFiscalDegreeCodeByFiscalDegreeCode() {
        return this.perFiscalDegreeCodeByFiscalDegreeCode;
    }
    
    public void setPerFiscalDegreeCodeByFiscalDegreeCode(PerFiscalDegreeCode perFiscalDegreeCodeByFiscalDegreeCode) {
        this.perFiscalDegreeCodeByFiscalDegreeCode = perFiscalDegreeCodeByFiscalDegreeCode;
    }

    
    @Column(name="PROMOTION_RATE", nullable=false, precision=2, scale=0)
    public byte getPromotionRate() {
        return this.promotionRate;
    }
    
    public void setPromotionRate(byte promotionRate) {
        this.promotionRate = promotionRate;
    }

    
    @Column(name="PROMOTION_PERCENT", precision=5)
    public BigDecimal getPromotionPercent() {
        return this.promotionPercent;
    }
    
    public void setPromotionPercent(BigDecimal promotionPercent) {
        this.promotionPercent = promotionPercent;
    }

    
    @Column(name="NOTES", length=100)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }




}


