package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerFileJava generated by hbm2java
 */
@Entity
@Table(name="PER_FILE_JAVA"
    ,schema="SHAMS"
)
public class PerFileJava  implements java.io.Serializable {


     private long fileSp;
     private Date fileDate;
     private Blob docImage;
     private String fileTitle;

    public PerFileJava() {
    }

	
    public PerFileJava(long fileSp) {
        this.fileSp = fileSp;
    }
    public PerFileJava(long fileSp, Date fileDate, Blob docImage, String fileTitle) {
       this.fileSp = fileSp;
       this.fileDate = fileDate;
       this.docImage = docImage;
       this.fileTitle = fileTitle;
    }
   
     @Id 

    
    @Column(name="FILE_SP", unique=true, nullable=false, precision=16, scale=0)
    public long getFileSp() {
        return this.fileSp;
    }
    
    public void setFileSp(long fileSp) {
        this.fileSp = fileSp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FILE_DATE", length=7)
    public Date getFileDate() {
        return this.fileDate;
    }
    
    public void setFileDate(Date fileDate) {
        this.fileDate = fileDate;
    }

    
    @Column(name="DOC_IMAGE")
    public Blob getDocImage() {
        return this.docImage;
    }
    
    public void setDocImage(Blob docImage) {
        this.docImage = docImage;
    }

    
    @Column(name="FILE_TITLE", length=200)
    public String getFileTitle() {
        return this.fileTitle;
    }
    
    public void setFileTitle(String fileTitle) {
        this.fileTitle = fileTitle;
    }




}


