package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerGovernorateCode generated by hbm2java
 */
@Entity
@Table(name="PER_GOVERNORATE_CODE"
    ,schema="SHAMS"
)
public class PerGovernorateCode  implements java.io.Serializable {


     private PerGovernorateCodeId id;
     private PerCountryCode perCountryCode;
     private String AGovName;
     private String EGovName;
     private String telCode;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private Set<PerInsuranceSideCode> perInsuranceSideCodes = new HashSet<PerInsuranceSideCode>(0);
     private Set<PerCityCode> perCityCodes = new HashSet<PerCityCode>(0);
     private Set<PerLocationCodes> perLocationCodeses = new HashSet<PerLocationCodes>(0);

    public PerGovernorateCode() {
    }

	
    public PerGovernorateCode(PerGovernorateCodeId id, PerCountryCode perCountryCode, String AGovName) {
        this.id = id;
        this.perCountryCode = perCountryCode;
        this.AGovName = AGovName;
    }
    public PerGovernorateCode(PerGovernorateCodeId id, PerCountryCode perCountryCode, String AGovName, String EGovName, String telCode, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, Set<PerInsuranceSideCode> perInsuranceSideCodes, Set<PerCityCode> perCityCodes, Set<PerLocationCodes> perLocationCodeses) {
       this.id = id;
       this.perCountryCode = perCountryCode;
       this.AGovName = AGovName;
       this.EGovName = EGovName;
       this.telCode = telCode;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.perInsuranceSideCodes = perInsuranceSideCodes;
       this.perCityCodes = perCityCodes;
       this.perLocationCodeses = perLocationCodeses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="countryCode", column=@Column(name="COUNTRY_CODE", nullable=false, length=5) ), 
        @AttributeOverride(name="govCode", column=@Column(name="GOV_CODE", nullable=false, length=5) ) } )
    public PerGovernorateCodeId getId() {
        return this.id;
    }
    
    public void setId(PerGovernorateCodeId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COUNTRY_CODE", nullable=false, insertable=false, updatable=false)
    public PerCountryCode getPerCountryCode() {
        return this.perCountryCode;
    }
    
    public void setPerCountryCode(PerCountryCode perCountryCode) {
        this.perCountryCode = perCountryCode;
    }

    
    @Column(name="A_GOV_NAME", nullable=false, length=50)
    public String getAGovName() {
        return this.AGovName;
    }
    
    public void setAGovName(String AGovName) {
        this.AGovName = AGovName;
    }

    
    @Column(name="E_GOV_NAME", length=50)
    public String getEGovName() {
        return this.EGovName;
    }
    
    public void setEGovName(String EGovName) {
        this.EGovName = EGovName;
    }

    
    @Column(name="TEL_CODE", length=3)
    public String getTelCode() {
        return this.telCode;
    }
    
    public void setTelCode(String telCode) {
        this.telCode = telCode;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perGovernorateCode")
    public Set<PerInsuranceSideCode> getPerInsuranceSideCodes() {
        return this.perInsuranceSideCodes;
    }
    
    public void setPerInsuranceSideCodes(Set<PerInsuranceSideCode> perInsuranceSideCodes) {
        this.perInsuranceSideCodes = perInsuranceSideCodes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perGovernorateCode")
    public Set<PerCityCode> getPerCityCodes() {
        return this.perCityCodes;
    }
    
    public void setPerCityCodes(Set<PerCityCode> perCityCodes) {
        this.perCityCodes = perCityCodes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perGovernorateCode")
    public Set<PerLocationCodes> getPerLocationCodeses() {
        return this.perLocationCodeses;
    }
    
    public void setPerLocationCodeses(Set<PerLocationCodes> perLocationCodeses) {
        this.perLocationCodeses = perLocationCodeses;
    }




}


