package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerGradePercentage generated by hbm2java
 */
@Entity
@Table(name="PER_GRADE_PERCENTAGE"
    ,schema="SHAMS"
)
public class PerGradePercentage  implements java.io.Serializable {


     private String gradeCode;
     private String gradeName;
     private BigDecimal percentageFrom;
     private BigDecimal percentageTo;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;

    public PerGradePercentage() {
    }

	
    public PerGradePercentage(String gradeCode, String gradeName, BigDecimal percentageFrom, BigDecimal percentageTo) {
        this.gradeCode = gradeCode;
        this.gradeName = gradeName;
        this.percentageFrom = percentageFrom;
        this.percentageTo = percentageTo;
    }
    public PerGradePercentage(String gradeCode, String gradeName, BigDecimal percentageFrom, BigDecimal percentageTo, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate) {
       this.gradeCode = gradeCode;
       this.gradeName = gradeName;
       this.percentageFrom = percentageFrom;
       this.percentageTo = percentageTo;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
    }
   
     @Id 

    
    @Column(name="GRADE_CODE", unique=true, nullable=false, length=2)
    public String getGradeCode() {
        return this.gradeCode;
    }
    
    public void setGradeCode(String gradeCode) {
        this.gradeCode = gradeCode;
    }

    
    @Column(name="GRADE_NAME", nullable=false, length=25)
    public String getGradeName() {
        return this.gradeName;
    }
    
    public void setGradeName(String gradeName) {
        this.gradeName = gradeName;
    }

    
    @Column(name="PERCENTAGE_FROM", nullable=false, precision=5)
    public BigDecimal getPercentageFrom() {
        return this.percentageFrom;
    }
    
    public void setPercentageFrom(BigDecimal percentageFrom) {
        this.percentageFrom = percentageFrom;
    }

    
    @Column(name="PERCENTAGE_TO", nullable=false, precision=5)
    public BigDecimal getPercentageTo() {
        return this.percentageTo;
    }
    
    public void setPercentageTo(BigDecimal percentageTo) {
        this.percentageTo = percentageTo;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }




}


