package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerGeneralCode generated by hbm2java
 */
@Entity
@Table(name="PER_GENERAL_CODE"
    ,schema="SHAMS"
)
public class PerGeneralCode  implements java.io.Serializable {


     private String generalCode;
     private String generalName;
     private byte generalType;
     private boolean salaryFlag;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private Boolean gehaKind;
     private Set<PerElawaGeneralRule> perElawaGeneralRules = new HashSet<PerElawaGeneralRule>(0);
     private Set<PerEmpHistory> perEmpHistories = new HashSet<PerEmpHistory>(0);
     private Set<PerPromotionRule> perPromotionRules = new HashSet<PerPromotionRule>(0);
     private Set<PerEasementTrans> perEasementTranses = new HashSet<PerEasementTrans>(0);
     private Set<PerElawaType> perElawaTypes = new HashSet<PerElawaType>(0);
     private Set<PerVacationCode> perVacationCodes = new HashSet<PerVacationCode>(0);
     private Set<PerEmploymentMasters> perEmploymentMastersesForGeneralCodeFirst = new HashSet<PerEmploymentMasters>(0);
     private Set<PerEmploymentMasters> perEmploymentMastersesForGeneralCode = new HashSet<PerEmploymentMasters>(0);

    public PerGeneralCode() {
    }

	
    public PerGeneralCode(String generalCode, String generalName, byte generalType, boolean salaryFlag) {
        this.generalCode = generalCode;
        this.generalName = generalName;
        this.generalType = generalType;
        this.salaryFlag = salaryFlag;
    }
    public PerGeneralCode(String generalCode, String generalName, byte generalType, boolean salaryFlag, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, Boolean gehaKind, Set<PerElawaGeneralRule> perElawaGeneralRules, Set<PerEmpHistory> perEmpHistories, Set<PerPromotionRule> perPromotionRules, Set<PerEasementTrans> perEasementTranses, Set<PerElawaType> perElawaTypes, Set<PerVacationCode> perVacationCodes, Set<PerEmploymentMasters> perEmploymentMastersesForGeneralCodeFirst, Set<PerEmploymentMasters> perEmploymentMastersesForGeneralCode) {
       this.generalCode = generalCode;
       this.generalName = generalName;
       this.generalType = generalType;
       this.salaryFlag = salaryFlag;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.gehaKind = gehaKind;
       this.perElawaGeneralRules = perElawaGeneralRules;
       this.perEmpHistories = perEmpHistories;
       this.perPromotionRules = perPromotionRules;
       this.perEasementTranses = perEasementTranses;
       this.perElawaTypes = perElawaTypes;
       this.perVacationCodes = perVacationCodes;
       this.perEmploymentMastersesForGeneralCodeFirst = perEmploymentMastersesForGeneralCodeFirst;
       this.perEmploymentMastersesForGeneralCode = perEmploymentMastersesForGeneralCode;
    }
   
     @Id 

    
    @Column(name="GENERAL_CODE", unique=true, nullable=false, length=3)
    public String getGeneralCode() {
        return this.generalCode;
    }
    
    public void setGeneralCode(String generalCode) {
        this.generalCode = generalCode;
    }

    
    @Column(name="GENERAL_NAME", nullable=false, length=50)
    public String getGeneralName() {
        return this.generalName;
    }
    
    public void setGeneralName(String generalName) {
        this.generalName = generalName;
    }

    
    @Column(name="GENERAL_TYPE", nullable=false, precision=2, scale=0)
    public byte getGeneralType() {
        return this.generalType;
    }
    
    public void setGeneralType(byte generalType) {
        this.generalType = generalType;
    }

    
    @Column(name="SALARY_FLAG", nullable=false, precision=1, scale=0)
    public boolean isSalaryFlag() {
        return this.salaryFlag;
    }
    
    public void setSalaryFlag(boolean salaryFlag) {
        this.salaryFlag = salaryFlag;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

    
    @Column(name="GEHA_KIND", precision=1, scale=0)
    public Boolean getGehaKind() {
        return this.gehaKind;
    }
    
    public void setGehaKind(Boolean gehaKind) {
        this.gehaKind = gehaKind;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perGeneralCode")
    public Set<PerElawaGeneralRule> getPerElawaGeneralRules() {
        return this.perElawaGeneralRules;
    }
    
    public void setPerElawaGeneralRules(Set<PerElawaGeneralRule> perElawaGeneralRules) {
        this.perElawaGeneralRules = perElawaGeneralRules;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perGeneralCode")
    public Set<PerEmpHistory> getPerEmpHistories() {
        return this.perEmpHistories;
    }
    
    public void setPerEmpHistories(Set<PerEmpHistory> perEmpHistories) {
        this.perEmpHistories = perEmpHistories;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perGeneralCode")
    public Set<PerPromotionRule> getPerPromotionRules() {
        return this.perPromotionRules;
    }
    
    public void setPerPromotionRules(Set<PerPromotionRule> perPromotionRules) {
        this.perPromotionRules = perPromotionRules;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perGeneralCode")
    public Set<PerEasementTrans> getPerEasementTranses() {
        return this.perEasementTranses;
    }
    
    public void setPerEasementTranses(Set<PerEasementTrans> perEasementTranses) {
        this.perEasementTranses = perEasementTranses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perGeneralCode")
    public Set<PerElawaType> getPerElawaTypes() {
        return this.perElawaTypes;
    }
    
    public void setPerElawaTypes(Set<PerElawaType> perElawaTypes) {
        this.perElawaTypes = perElawaTypes;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perGeneralCode")
    public Set<PerVacationCode> getPerVacationCodes() {
        return this.perVacationCodes;
    }
    
    public void setPerVacationCodes(Set<PerVacationCode> perVacationCodes) {
        this.perVacationCodes = perVacationCodes;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perGeneralCodeByGeneralCodeFirst")
    public Set<PerEmploymentMasters> getPerEmploymentMastersesForGeneralCodeFirst() {
        return this.perEmploymentMastersesForGeneralCodeFirst;
    }
    
    public void setPerEmploymentMastersesForGeneralCodeFirst(Set<PerEmploymentMasters> perEmploymentMastersesForGeneralCodeFirst) {
        this.perEmploymentMastersesForGeneralCodeFirst = perEmploymentMastersesForGeneralCodeFirst;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perGeneralCodeByGeneralCode")
    public Set<PerEmploymentMasters> getPerEmploymentMastersesForGeneralCode() {
        return this.perEmploymentMastersesForGeneralCode;
    }
    
    public void setPerEmploymentMastersesForGeneralCode(Set<PerEmploymentMasters> perEmploymentMastersesForGeneralCode) {
        this.perEmploymentMastersesForGeneralCode = perEmploymentMastersesForGeneralCode;
    }




}


