package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PerHumanActivityId generated by hbm2java
 */
@Embeddable
public class PerHumanActivityId  implements java.io.Serializable {


     private String locationCode;
     private String humanBalId;
     private String orgId;
     private String actSerialNo;

    public PerHumanActivityId() {
    }

    public PerHumanActivityId(String locationCode, String humanBalId, String orgId, String actSerialNo) {
       this.locationCode = locationCode;
       this.humanBalId = humanBalId;
       this.orgId = orgId;
       this.actSerialNo = actSerialNo;
    }
   


    @Column(name="LOCATION_CODE", nullable=false, length=3)
    public String getLocationCode() {
        return this.locationCode;
    }
    
    public void setLocationCode(String locationCode) {
        this.locationCode = locationCode;
    }


    @Column(name="HUMAN_BAL_ID", nullable=false, length=5)
    public String getHumanBalId() {
        return this.humanBalId;
    }
    
    public void setHumanBalId(String humanBalId) {
        this.humanBalId = humanBalId;
    }


    @Column(name="ORG_ID", nullable=false, length=5)
    public String getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }


    @Column(name="ACT_SERIAL_NO", nullable=false, length=3)
    public String getActSerialNo() {
        return this.actSerialNo;
    }
    
    public void setActSerialNo(String actSerialNo) {
        this.actSerialNo = actSerialNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PerHumanActivityId) ) return false;
		 PerHumanActivityId castOther = ( PerHumanActivityId ) other; 
         
		 return ( (this.getLocationCode()==castOther.getLocationCode()) || ( this.getLocationCode()!=null && castOther.getLocationCode()!=null && this.getLocationCode().equals(castOther.getLocationCode()) ) )
 && ( (this.getHumanBalId()==castOther.getHumanBalId()) || ( this.getHumanBalId()!=null && castOther.getHumanBalId()!=null && this.getHumanBalId().equals(castOther.getHumanBalId()) ) )
 && ( (this.getOrgId()==castOther.getOrgId()) || ( this.getOrgId()!=null && castOther.getOrgId()!=null && this.getOrgId().equals(castOther.getOrgId()) ) )
 && ( (this.getActSerialNo()==castOther.getActSerialNo()) || ( this.getActSerialNo()!=null && castOther.getActSerialNo()!=null && this.getActSerialNo().equals(castOther.getActSerialNo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLocationCode() == null ? 0 : this.getLocationCode().hashCode() );
         result = 37 * result + ( getHumanBalId() == null ? 0 : this.getHumanBalId().hashCode() );
         result = 37 * result + ( getOrgId() == null ? 0 : this.getOrgId().hashCode() );
         result = 37 * result + ( getActSerialNo() == null ? 0 : this.getActSerialNo().hashCode() );
         return result;
   }   


}


