package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerHumanActivityFollow generated by hbm2java
 */
@Entity
@Table(name="PER_HUMAN_ACTIVITY_FOLLOW"
    ,schema="SHAMS"
)
public class PerHumanActivityFollow  implements java.io.Serializable {


     private PerHumanActivityFollowId id;
     private PerHumanActivity perHumanActivity;
     private Date followDate;
     private String followStatusCode;
     private BigDecimal evalRatio;
     private String followNote;

    public PerHumanActivityFollow() {
    }

	
    public PerHumanActivityFollow(PerHumanActivityFollowId id, PerHumanActivity perHumanActivity, Date followDate, String followStatusCode) {
        this.id = id;
        this.perHumanActivity = perHumanActivity;
        this.followDate = followDate;
        this.followStatusCode = followStatusCode;
    }
    public PerHumanActivityFollow(PerHumanActivityFollowId id, PerHumanActivity perHumanActivity, Date followDate, String followStatusCode, BigDecimal evalRatio, String followNote) {
       this.id = id;
       this.perHumanActivity = perHumanActivity;
       this.followDate = followDate;
       this.followStatusCode = followStatusCode;
       this.evalRatio = evalRatio;
       this.followNote = followNote;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="locationCode", column=@Column(name="LOCATION_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="humanBalId", column=@Column(name="HUMAN_BAL_ID", nullable=false, length=5) ), 
        @AttributeOverride(name="orgId", column=@Column(name="ORG_ID", nullable=false, length=5) ), 
        @AttributeOverride(name="actSerialNo", column=@Column(name="ACT_SERIAL_NO", nullable=false, length=3) ), 
        @AttributeOverride(name="followNo", column=@Column(name="FOLLOW_NO", nullable=false, length=3) ) } )
    public PerHumanActivityFollowId getId() {
        return this.id;
    }
    
    public void setId(PerHumanActivityFollowId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="LOCATION_CODE", referencedColumnName="LOCATION_CODE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="HUMAN_BAL_ID", referencedColumnName="HUMAN_BAL_ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="ORG_ID", referencedColumnName="ORG_ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="ACT_SERIAL_NO", referencedColumnName="ACT_SERIAL_NO", nullable=false, insertable=false, updatable=false) } )
    public PerHumanActivity getPerHumanActivity() {
        return this.perHumanActivity;
    }
    
    public void setPerHumanActivity(PerHumanActivity perHumanActivity) {
        this.perHumanActivity = perHumanActivity;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FOLLOW_DATE", nullable=false, length=7)
    public Date getFollowDate() {
        return this.followDate;
    }
    
    public void setFollowDate(Date followDate) {
        this.followDate = followDate;
    }

    
    @Column(name="FOLLOW_STATUS_CODE", nullable=false, length=5)
    public String getFollowStatusCode() {
        return this.followStatusCode;
    }
    
    public void setFollowStatusCode(String followStatusCode) {
        this.followStatusCode = followStatusCode;
    }

    
    @Column(name="EVAL_RATIO", precision=5)
    public BigDecimal getEvalRatio() {
        return this.evalRatio;
    }
    
    public void setEvalRatio(BigDecimal evalRatio) {
        this.evalRatio = evalRatio;
    }

    
    @Column(name="FOLLOW_NOTE", length=100)
    public String getFollowNote() {
        return this.followNote;
    }
    
    public void setFollowNote(String followNote) {
        this.followNote = followNote;
    }




}


