package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerHumanBalYear generated by hbm2java
 */
@Entity
@Table(name="PER_HUMAN_BAL_YEAR"
    ,schema="SHAMS"
)
public class PerHumanBalYear  implements java.io.Serializable {


     private PerHumanBalYearId id;
     private BudLocation budLocation;
     private Date balFromDate;
     private Date balToDate;
     private Date aprvdateCenter;
     private Date aprvdateMalia;
     private Set<PerHumanPlan> perHumanPlans = new HashSet<PerHumanPlan>(0);
     private Set<PerHumanBalJob> perHumanBalJobs = new HashSet<PerHumanBalJob>(0);
     private Set<PerHumanBalJobNew> perHumanBalJobNews = new HashSet<PerHumanBalJobNew>(0);
     private Set<PerEasementTrans> perEasementTranses = new HashSet<PerEasementTrans>(0);
     private Set<PerHumanBalJobDistributeN> perHumanBalJobDistributeNs = new HashSet<PerHumanBalJobDistributeN>(0);
     private Set<PerHumanBalJobDistribute> perHumanBalJobDistributes = new HashSet<PerHumanBalJobDistribute>(0);

    public PerHumanBalYear() {
    }

	
    public PerHumanBalYear(PerHumanBalYearId id, BudLocation budLocation, Date balFromDate, Date balToDate) {
        this.id = id;
        this.budLocation = budLocation;
        this.balFromDate = balFromDate;
        this.balToDate = balToDate;
    }
    public PerHumanBalYear(PerHumanBalYearId id, BudLocation budLocation, Date balFromDate, Date balToDate, Date aprvdateCenter, Date aprvdateMalia, Set<PerHumanPlan> perHumanPlans, Set<PerHumanBalJob> perHumanBalJobs, Set<PerHumanBalJobNew> perHumanBalJobNews, Set<PerEasementTrans> perEasementTranses, Set<PerHumanBalJobDistributeN> perHumanBalJobDistributeNs, Set<PerHumanBalJobDistribute> perHumanBalJobDistributes) {
       this.id = id;
       this.budLocation = budLocation;
       this.balFromDate = balFromDate;
       this.balToDate = balToDate;
       this.aprvdateCenter = aprvdateCenter;
       this.aprvdateMalia = aprvdateMalia;
       this.perHumanPlans = perHumanPlans;
       this.perHumanBalJobs = perHumanBalJobs;
       this.perHumanBalJobNews = perHumanBalJobNews;
       this.perEasementTranses = perEasementTranses;
       this.perHumanBalJobDistributeNs = perHumanBalJobDistributeNs;
       this.perHumanBalJobDistributes = perHumanBalJobDistributes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="humanBalId", column=@Column(name="HUMAN_BAL_ID", nullable=false, length=5) ), 
        @AttributeOverride(name="locationCode", column=@Column(name="LOCATION_CODE", nullable=false, length=3) ) } )
    public PerHumanBalYearId getId() {
        return this.id;
    }
    
    public void setId(PerHumanBalYearId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="LOCATION_CODE", nullable=false, insertable=false, updatable=false)
    public BudLocation getBudLocation() {
        return this.budLocation;
    }
    
    public void setBudLocation(BudLocation budLocation) {
        this.budLocation = budLocation;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="BAL_FROM_DATE", nullable=false, length=7)
    public Date getBalFromDate() {
        return this.balFromDate;
    }
    
    public void setBalFromDate(Date balFromDate) {
        this.balFromDate = balFromDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="BAL_TO_DATE", nullable=false, length=7)
    public Date getBalToDate() {
        return this.balToDate;
    }
    
    public void setBalToDate(Date balToDate) {
        this.balToDate = balToDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="APRVDATE_CENTER", length=7)
    public Date getAprvdateCenter() {
        return this.aprvdateCenter;
    }
    
    public void setAprvdateCenter(Date aprvdateCenter) {
        this.aprvdateCenter = aprvdateCenter;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="APRVDATE_MALIA", length=7)
    public Date getAprvdateMalia() {
        return this.aprvdateMalia;
    }
    
    public void setAprvdateMalia(Date aprvdateMalia) {
        this.aprvdateMalia = aprvdateMalia;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perHumanBalYear")
    public Set<PerHumanPlan> getPerHumanPlans() {
        return this.perHumanPlans;
    }
    
    public void setPerHumanPlans(Set<PerHumanPlan> perHumanPlans) {
        this.perHumanPlans = perHumanPlans;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perHumanBalYear")
    public Set<PerHumanBalJob> getPerHumanBalJobs() {
        return this.perHumanBalJobs;
    }
    
    public void setPerHumanBalJobs(Set<PerHumanBalJob> perHumanBalJobs) {
        this.perHumanBalJobs = perHumanBalJobs;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perHumanBalYear")
    public Set<PerHumanBalJobNew> getPerHumanBalJobNews() {
        return this.perHumanBalJobNews;
    }
    
    public void setPerHumanBalJobNews(Set<PerHumanBalJobNew> perHumanBalJobNews) {
        this.perHumanBalJobNews = perHumanBalJobNews;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perHumanBalYear")
    public Set<PerEasementTrans> getPerEasementTranses() {
        return this.perEasementTranses;
    }
    
    public void setPerEasementTranses(Set<PerEasementTrans> perEasementTranses) {
        this.perEasementTranses = perEasementTranses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perHumanBalYear")
    public Set<PerHumanBalJobDistributeN> getPerHumanBalJobDistributeNs() {
        return this.perHumanBalJobDistributeNs;
    }
    
    public void setPerHumanBalJobDistributeNs(Set<PerHumanBalJobDistributeN> perHumanBalJobDistributeNs) {
        this.perHumanBalJobDistributeNs = perHumanBalJobDistributeNs;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perHumanBalYear")
    public Set<PerHumanBalJobDistribute> getPerHumanBalJobDistributes() {
        return this.perHumanBalJobDistributes;
    }
    
    public void setPerHumanBalJobDistributes(Set<PerHumanBalJobDistribute> perHumanBalJobDistributes) {
        this.perHumanBalJobDistributes = perHumanBalJobDistributes;
    }




}


