package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PerHumanPlan generated by hbm2java
 */
@Entity
@Table(name="PER_HUMAN_PLAN"
    ,schema="SHAMS"
)
public class PerHumanPlan  implements java.io.Serializable {


     private PerHumanPlanId id;
     private PerHumanBalYear perHumanBalYear;
     private PerOrganizationStructure perOrganizationStructure;
     private PerOrgunitCode perOrgunitCode;
     private String targetDesc;
     private String targetNotes;
     private Set<PerHumanActivity> perHumanActivities = new HashSet<PerHumanActivity>(0);

    public PerHumanPlan() {
    }

	
    public PerHumanPlan(PerHumanPlanId id, PerHumanBalYear perHumanBalYear, PerOrganizationStructure perOrganizationStructure, PerOrgunitCode perOrgunitCode) {
        this.id = id;
        this.perHumanBalYear = perHumanBalYear;
        this.perOrganizationStructure = perOrganizationStructure;
        this.perOrgunitCode = perOrgunitCode;
    }
    public PerHumanPlan(PerHumanPlanId id, PerHumanBalYear perHumanBalYear, PerOrganizationStructure perOrganizationStructure, PerOrgunitCode perOrgunitCode, String targetDesc, String targetNotes, Set<PerHumanActivity> perHumanActivities) {
       this.id = id;
       this.perHumanBalYear = perHumanBalYear;
       this.perOrganizationStructure = perOrganizationStructure;
       this.perOrgunitCode = perOrgunitCode;
       this.targetDesc = targetDesc;
       this.targetNotes = targetNotes;
       this.perHumanActivities = perHumanActivities;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="locationCode", column=@Column(name="LOCATION_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="humanBalId", column=@Column(name="HUMAN_BAL_ID", nullable=false, length=5) ), 
        @AttributeOverride(name="orgId", column=@Column(name="ORG_ID", nullable=false, length=5) ) } )
    public PerHumanPlanId getId() {
        return this.id;
    }
    
    public void setId(PerHumanPlanId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="HUMAN_BAL_ID", referencedColumnName="HUMAN_BAL_ID", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="LOCATION_CODE", referencedColumnName="LOCATION_CODE", nullable=false, insertable=false, updatable=false) } )
    public PerHumanBalYear getPerHumanBalYear() {
        return this.perHumanBalYear;
    }
    
    public void setPerHumanBalYear(PerHumanBalYear perHumanBalYear) {
        this.perHumanBalYear = perHumanBalYear;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ORG_ID", nullable=false, insertable=false, updatable=false)
    public PerOrganizationStructure getPerOrganizationStructure() {
        return this.perOrganizationStructure;
    }
    
    public void setPerOrganizationStructure(PerOrganizationStructure perOrganizationStructure) {
        this.perOrganizationStructure = perOrganizationStructure;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ORGUNIT_CODE", nullable=false)
    public PerOrgunitCode getPerOrgunitCode() {
        return this.perOrgunitCode;
    }
    
    public void setPerOrgunitCode(PerOrgunitCode perOrgunitCode) {
        this.perOrgunitCode = perOrgunitCode;
    }

    
    @Column(name="TARGET_DESC", length=2000)
    public String getTargetDesc() {
        return this.targetDesc;
    }
    
    public void setTargetDesc(String targetDesc) {
        this.targetDesc = targetDesc;
    }

    
    @Column(name="TARGET_NOTES", length=500)
    public String getTargetNotes() {
        return this.targetNotes;
    }
    
    public void setTargetNotes(String targetNotes) {
        this.targetNotes = targetNotes;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perHumanPlan")
    public Set<PerHumanActivity> getPerHumanActivities() {
        return this.perHumanActivities;
    }
    
    public void setPerHumanActivities(Set<PerHumanActivity> perHumanActivities) {
        this.perHumanActivities = perHumanActivities;
    }




}


