package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PerJobGroup generated by hbm2java
 */
@Entity
@Table(name="PER_JOB_GROUP"
    ,schema="SHAMS"
)
public class PerJobGroup  implements java.io.Serializable {


     private short jobGroupCode;
     private String jobGroupName;
     private Byte jobGroupOrder;

    public PerJobGroup() {
    }

	
    public PerJobGroup(short jobGroupCode) {
        this.jobGroupCode = jobGroupCode;
    }
    public PerJobGroup(short jobGroupCode, String jobGroupName, Byte jobGroupOrder) {
       this.jobGroupCode = jobGroupCode;
       this.jobGroupName = jobGroupName;
       this.jobGroupOrder = jobGroupOrder;
    }
   
     @Id 

    
    @Column(name="JOB_GROUP_CODE", unique=true, nullable=false, precision=4, scale=0)
    public short getJobGroupCode() {
        return this.jobGroupCode;
    }
    
    public void setJobGroupCode(short jobGroupCode) {
        this.jobGroupCode = jobGroupCode;
    }

    
    @Column(name="JOB_GROUP_NAME", length=40)
    public String getJobGroupName() {
        return this.jobGroupName;
    }
    
    public void setJobGroupName(String jobGroupName) {
        this.jobGroupName = jobGroupName;
    }

    
    @Column(name="JOB_GROUP_ORDER", precision=2, scale=0)
    public Byte getJobGroupOrder() {
        return this.jobGroupOrder;
    }
    
    public void setJobGroupOrder(Byte jobGroupOrder) {
        this.jobGroupOrder = jobGroupOrder;
    }




}


