package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PerJobLaw generated by hbm2java
 */
@Entity
@Table(name="PER_JOB_LAW"
    ,schema="SHAMS"
)
public class PerJobLaw  implements java.io.Serializable {


     private String lawSeq;
     private short lawNumber;
     private String lawName;
     private boolean lawType;
     private Boolean lawKindSal;
     private Set<PerEmploymentMasters> perEmploymentMasterses = new HashSet<PerEmploymentMasters>(0);
     private Set<PerFiscalDegreeCodeNew> perFiscalDegreeCodeNews = new HashSet<PerFiscalDegreeCodeNew>(0);
     private Set<PerEmpHistory> perEmpHistories = new HashSet<PerEmpHistory>(0);

    public PerJobLaw() {
    }

	
    public PerJobLaw(String lawSeq, short lawNumber, String lawName, boolean lawType) {
        this.lawSeq = lawSeq;
        this.lawNumber = lawNumber;
        this.lawName = lawName;
        this.lawType = lawType;
    }
    public PerJobLaw(String lawSeq, short lawNumber, String lawName, boolean lawType, Boolean lawKindSal, Set<PerEmploymentMasters> perEmploymentMasterses, Set<PerFiscalDegreeCodeNew> perFiscalDegreeCodeNews, Set<PerEmpHistory> perEmpHistories) {
       this.lawSeq = lawSeq;
       this.lawNumber = lawNumber;
       this.lawName = lawName;
       this.lawType = lawType;
       this.lawKindSal = lawKindSal;
       this.perEmploymentMasterses = perEmploymentMasterses;
       this.perFiscalDegreeCodeNews = perFiscalDegreeCodeNews;
       this.perEmpHistories = perEmpHistories;
    }
   
     @Id 

    
    @Column(name="LAW_SEQ", unique=true, nullable=false, length=3)
    public String getLawSeq() {
        return this.lawSeq;
    }
    
    public void setLawSeq(String lawSeq) {
        this.lawSeq = lawSeq;
    }

    
    @Column(name="LAW_NUMBER", nullable=false, precision=3, scale=0)
    public short getLawNumber() {
        return this.lawNumber;
    }
    
    public void setLawNumber(short lawNumber) {
        this.lawNumber = lawNumber;
    }

    
    @Column(name="LAW_NAME", nullable=false, length=100)
    public String getLawName() {
        return this.lawName;
    }
    
    public void setLawName(String lawName) {
        this.lawName = lawName;
    }

    
    @Column(name="LAW_TYPE", nullable=false, precision=1, scale=0)
    public boolean isLawType() {
        return this.lawType;
    }
    
    public void setLawType(boolean lawType) {
        this.lawType = lawType;
    }

    
    @Column(name="LAW_KIND_SAL", precision=1, scale=0)
    public Boolean getLawKindSal() {
        return this.lawKindSal;
    }
    
    public void setLawKindSal(Boolean lawKindSal) {
        this.lawKindSal = lawKindSal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perJobLaw")
    public Set<PerEmploymentMasters> getPerEmploymentMasterses() {
        return this.perEmploymentMasterses;
    }
    
    public void setPerEmploymentMasterses(Set<PerEmploymentMasters> perEmploymentMasterses) {
        this.perEmploymentMasterses = perEmploymentMasterses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perJobLaw")
    public Set<PerFiscalDegreeCodeNew> getPerFiscalDegreeCodeNews() {
        return this.perFiscalDegreeCodeNews;
    }
    
    public void setPerFiscalDegreeCodeNews(Set<PerFiscalDegreeCodeNew> perFiscalDegreeCodeNews) {
        this.perFiscalDegreeCodeNews = perFiscalDegreeCodeNews;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perJobLaw")
    public Set<PerEmpHistory> getPerEmpHistories() {
        return this.perEmpHistories;
    }
    
    public void setPerEmpHistories(Set<PerEmpHistory> perEmpHistories) {
        this.perEmpHistories = perEmpHistories;
    }




}


