package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerJobDetail generated by hbm2java
 */
@Entity
@Table(name="PER_JOB_DETAIL"
    ,schema="SHAMS"
)
public class PerJobDetail  implements java.io.Serializable {


     private PerJobDetailId id;
     private PerSpecialistCode perSpecialistCode;
     private PerJobCode perJobCode;
     private PerQualCode perQualCode;
     private PerQualSpecialist perQualSpecialist;
     private String notes;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;

    public PerJobDetail() {
    }

	
    public PerJobDetail(PerJobDetailId id, PerSpecialistCode perSpecialistCode, PerJobCode perJobCode, PerQualCode perQualCode, PerQualSpecialist perQualSpecialist) {
        this.id = id;
        this.perSpecialistCode = perSpecialistCode;
        this.perJobCode = perJobCode;
        this.perQualCode = perQualCode;
        this.perQualSpecialist = perQualSpecialist;
    }
    public PerJobDetail(PerJobDetailId id, PerSpecialistCode perSpecialistCode, PerJobCode perJobCode, PerQualCode perQualCode, PerQualSpecialist perQualSpecialist, String notes, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate) {
       this.id = id;
       this.perSpecialistCode = perSpecialistCode;
       this.perJobCode = perJobCode;
       this.perQualCode = perQualCode;
       this.perQualSpecialist = perQualSpecialist;
       this.notes = notes;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="jobCode", column=@Column(name="JOB_CODE", nullable=false, length=5) ), 
        @AttributeOverride(name="jobDetailSp", column=@Column(name="JOB_DETAIL_SP", nullable=false, length=2) ) } )
    public PerJobDetailId getId() {
        return this.id;
    }
    
    public void setId(PerJobDetailId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SPECIALIST_CODE", nullable=false)
    public PerSpecialistCode getPerSpecialistCode() {
        return this.perSpecialistCode;
    }
    
    public void setPerSpecialistCode(PerSpecialistCode perSpecialistCode) {
        this.perSpecialistCode = perSpecialistCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="JOB_CODE", nullable=false, insertable=false, updatable=false)
    public PerJobCode getPerJobCode() {
        return this.perJobCode;
    }
    
    public void setPerJobCode(PerJobCode perJobCode) {
        this.perJobCode = perJobCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="QUAL_CODE", nullable=false)
    public PerQualCode getPerQualCode() {
        return this.perQualCode;
    }
    
    public void setPerQualCode(PerQualCode perQualCode) {
        this.perQualCode = perQualCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="QUAL_CODE", referencedColumnName="QUAL_CODE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="SPECIALIST_CODE", referencedColumnName="SPECIALIST_CODE", nullable=false, insertable=false, updatable=false) } )
    public PerQualSpecialist getPerQualSpecialist() {
        return this.perQualSpecialist;
    }
    
    public void setPerQualSpecialist(PerQualSpecialist perQualSpecialist) {
        this.perQualSpecialist = perQualSpecialist;
    }

    
    @Column(name="NOTES", length=100)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }




}


