package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerLocationCodes generated by hbm2java
 */
@Entity
@Table(name="PER_LOCATION_CODES"
    ,schema="SHAMS"
)
public class PerLocationCodes  implements java.io.Serializable {


     private PerLocationCodesId id;
     private PerGovernorateCode perGovernorateCode;
     private BudLocation budLocation;
     private String locName;
     private String locAddress;
     private String locTel;
     private String locFax;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private Set<PayLocationBandFile> payLocationBandFiles = new HashSet<PayLocationBandFile>(0);
     private Set<PayDeserveEmp> payDeserveEmps = new HashSet<PayDeserveEmp>(0);
     private Set<PerEmploymentMasters> perEmploymentMasterses = new HashSet<PerEmploymentMasters>(0);
     private Set<PerEmpHistory> perEmpHistoriesForPerehPerlcFromFk = new HashSet<PerEmpHistory>(0);
     private Set<PerLocationCodeDepartment> perLocationCodeDepartments = new HashSet<PerLocationCodeDepartment>(0);
     private Set<PerElawaTransaction> perElawaTransactions = new HashSet<PerElawaTransaction>(0);
     private Set<PerEmpHistory> perEmpHistoriesForPerehPerlcFk = new HashSet<PerEmpHistory>(0);
     private Set<PerSectionCode> perSectionCodes = new HashSet<PerSectionCode>(0);

    public PerLocationCodes() {
    }

	
    public PerLocationCodes(PerLocationCodesId id, PerGovernorateCode perGovernorateCode, BudLocation budLocation, String locName) {
        this.id = id;
        this.perGovernorateCode = perGovernorateCode;
        this.budLocation = budLocation;
        this.locName = locName;
    }
    public PerLocationCodes(PerLocationCodesId id, PerGovernorateCode perGovernorateCode, BudLocation budLocation, String locName, String locAddress, String locTel, String locFax, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, Set<PayLocationBandFile> payLocationBandFiles, Set<PayDeserveEmp> payDeserveEmps, Set<PerEmploymentMasters> perEmploymentMasterses, Set<PerEmpHistory> perEmpHistoriesForPerehPerlcFromFk, Set<PerLocationCodeDepartment> perLocationCodeDepartments, Set<PerElawaTransaction> perElawaTransactions, Set<PerEmpHistory> perEmpHistoriesForPerehPerlcFk, Set<PerSectionCode> perSectionCodes) {
       this.id = id;
       this.perGovernorateCode = perGovernorateCode;
       this.budLocation = budLocation;
       this.locName = locName;
       this.locAddress = locAddress;
       this.locTel = locTel;
       this.locFax = locFax;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.payLocationBandFiles = payLocationBandFiles;
       this.payDeserveEmps = payDeserveEmps;
       this.perEmploymentMasterses = perEmploymentMasterses;
       this.perEmpHistoriesForPerehPerlcFromFk = perEmpHistoriesForPerehPerlcFromFk;
       this.perLocationCodeDepartments = perLocationCodeDepartments;
       this.perElawaTransactions = perElawaTransactions;
       this.perEmpHistoriesForPerehPerlcFk = perEmpHistoriesForPerehPerlcFk;
       this.perSectionCodes = perSectionCodes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="locCode", column=@Column(name="LOC_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="locationCode", column=@Column(name="LOCATION_CODE", nullable=false, length=3) ) } )
    public PerLocationCodesId getId() {
        return this.id;
    }
    
    public void setId(PerLocationCodesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="COUNTRY_CODE", referencedColumnName="COUNTRY_CODE", nullable=false), 
        @JoinColumn(name="GOV_CODE", referencedColumnName="GOV_CODE", nullable=false) } )
    public PerGovernorateCode getPerGovernorateCode() {
        return this.perGovernorateCode;
    }
    
    public void setPerGovernorateCode(PerGovernorateCode perGovernorateCode) {
        this.perGovernorateCode = perGovernorateCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LOCATION_CODE", nullable=false, insertable=false, updatable=false)
    public BudLocation getBudLocation() {
        return this.budLocation;
    }
    
    public void setBudLocation(BudLocation budLocation) {
        this.budLocation = budLocation;
    }

    
    @Column(name="LOC_NAME", nullable=false, length=50)
    public String getLocName() {
        return this.locName;
    }
    
    public void setLocName(String locName) {
        this.locName = locName;
    }

    
    @Column(name="LOC_ADDRESS", length=100)
    public String getLocAddress() {
        return this.locAddress;
    }
    
    public void setLocAddress(String locAddress) {
        this.locAddress = locAddress;
    }

    
    @Column(name="LOC_TEL", length=10)
    public String getLocTel() {
        return this.locTel;
    }
    
    public void setLocTel(String locTel) {
        this.locTel = locTel;
    }

    
    @Column(name="LOC_FAX", length=10)
    public String getLocFax() {
        return this.locFax;
    }
    
    public void setLocFax(String locFax) {
        this.locFax = locFax;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perLocationCodes")
    public Set<PayLocationBandFile> getPayLocationBandFiles() {
        return this.payLocationBandFiles;
    }
    
    public void setPayLocationBandFiles(Set<PayLocationBandFile> payLocationBandFiles) {
        this.payLocationBandFiles = payLocationBandFiles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perLocationCodes")
    public Set<PayDeserveEmp> getPayDeserveEmps() {
        return this.payDeserveEmps;
    }
    
    public void setPayDeserveEmps(Set<PayDeserveEmp> payDeserveEmps) {
        this.payDeserveEmps = payDeserveEmps;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perLocationCodes")
    public Set<PerEmploymentMasters> getPerEmploymentMasterses() {
        return this.perEmploymentMasterses;
    }
    
    public void setPerEmploymentMasterses(Set<PerEmploymentMasters> perEmploymentMasterses) {
        this.perEmploymentMasterses = perEmploymentMasterses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perLocationCodesByPerehPerlcFromFk")
    public Set<PerEmpHistory> getPerEmpHistoriesForPerehPerlcFromFk() {
        return this.perEmpHistoriesForPerehPerlcFromFk;
    }
    
    public void setPerEmpHistoriesForPerehPerlcFromFk(Set<PerEmpHistory> perEmpHistoriesForPerehPerlcFromFk) {
        this.perEmpHistoriesForPerehPerlcFromFk = perEmpHistoriesForPerehPerlcFromFk;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perLocationCodes")
    public Set<PerLocationCodeDepartment> getPerLocationCodeDepartments() {
        return this.perLocationCodeDepartments;
    }
    
    public void setPerLocationCodeDepartments(Set<PerLocationCodeDepartment> perLocationCodeDepartments) {
        this.perLocationCodeDepartments = perLocationCodeDepartments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perLocationCodes")
    public Set<PerElawaTransaction> getPerElawaTransactions() {
        return this.perElawaTransactions;
    }
    
    public void setPerElawaTransactions(Set<PerElawaTransaction> perElawaTransactions) {
        this.perElawaTransactions = perElawaTransactions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perLocationCodesByPerehPerlcFk")
    public Set<PerEmpHistory> getPerEmpHistoriesForPerehPerlcFk() {
        return this.perEmpHistoriesForPerehPerlcFk;
    }
    
    public void setPerEmpHistoriesForPerehPerlcFk(Set<PerEmpHistory> perEmpHistoriesForPerehPerlcFk) {
        this.perEmpHistoriesForPerehPerlcFk = perEmpHistoriesForPerehPerlcFk;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perLocationCodes")
    public Set<PerSectionCode> getPerSectionCodes() {
        return this.perSectionCodes;
    }
    
    public void setPerSectionCodes(Set<PerSectionCode> perSectionCodes) {
        this.perSectionCodes = perSectionCodes;
    }




}


