package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerMaritalCode generated by hbm2java
 */
@Entity
@Table(name="PER_MARITAL_CODE"
    ,schema="SHAMS"
)
public class PerMaritalCode  implements java.io.Serializable {


     private String maritalCode;
     private String maritalName;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private Set<PerEmploymentMasters> perEmploymentMasterses = new HashSet<PerEmploymentMasters>(0);

    public PerMaritalCode() {
    }

	
    public PerMaritalCode(String maritalCode, String maritalName) {
        this.maritalCode = maritalCode;
        this.maritalName = maritalName;
    }
    public PerMaritalCode(String maritalCode, String maritalName, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, Set<PerEmploymentMasters> perEmploymentMasterses) {
       this.maritalCode = maritalCode;
       this.maritalName = maritalName;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.perEmploymentMasterses = perEmploymentMasterses;
    }
   
     @Id 

    
    @Column(name="MARITAL_CODE", unique=true, nullable=false, length=2)
    public String getMaritalCode() {
        return this.maritalCode;
    }
    
    public void setMaritalCode(String maritalCode) {
        this.maritalCode = maritalCode;
    }

    
    @Column(name="MARITAL_NAME", nullable=false, length=50)
    public String getMaritalName() {
        return this.maritalName;
    }
    
    public void setMaritalName(String maritalName) {
        this.maritalName = maritalName;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perMaritalCode")
    public Set<PerEmploymentMasters> getPerEmploymentMasterses() {
        return this.perEmploymentMasterses;
    }
    
    public void setPerEmploymentMasterses(Set<PerEmploymentMasters> perEmploymentMasterses) {
        this.perEmploymentMasterses = perEmploymentMasterses;
    }




}


