package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerMilitaryCode generated by hbm2java
 */
@Entity
@Table(name="PER_MILITARY_CODE"
    ,schema="SHAMS"
)
public class PerMilitaryCode  implements java.io.Serializable {


     private String militaryCode;
     private String militaryName;
     private boolean sexType;
     private byte priorityFlag;
     private boolean followFlag;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private Set<PerEmploymentMasters> perEmploymentMasterses = new HashSet<PerEmploymentMasters>(0);

    public PerMilitaryCode() {
    }

	
    public PerMilitaryCode(String militaryCode, String militaryName, boolean sexType, byte priorityFlag, boolean followFlag) {
        this.militaryCode = militaryCode;
        this.militaryName = militaryName;
        this.sexType = sexType;
        this.priorityFlag = priorityFlag;
        this.followFlag = followFlag;
    }
    public PerMilitaryCode(String militaryCode, String militaryName, boolean sexType, byte priorityFlag, boolean followFlag, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, Set<PerEmploymentMasters> perEmploymentMasterses) {
       this.militaryCode = militaryCode;
       this.militaryName = militaryName;
       this.sexType = sexType;
       this.priorityFlag = priorityFlag;
       this.followFlag = followFlag;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.perEmploymentMasterses = perEmploymentMasterses;
    }
   
     @Id 

    
    @Column(name="MILITARY_CODE", unique=true, nullable=false, length=2)
    public String getMilitaryCode() {
        return this.militaryCode;
    }
    
    public void setMilitaryCode(String militaryCode) {
        this.militaryCode = militaryCode;
    }

    
    @Column(name="MILITARY_NAME", nullable=false, length=50)
    public String getMilitaryName() {
        return this.militaryName;
    }
    
    public void setMilitaryName(String militaryName) {
        this.militaryName = militaryName;
    }

    
    @Column(name="SEX_TYPE", nullable=false, precision=1, scale=0)
    public boolean isSexType() {
        return this.sexType;
    }
    
    public void setSexType(boolean sexType) {
        this.sexType = sexType;
    }

    
    @Column(name="PRIORITY_FLAG", nullable=false, precision=2, scale=0)
    public byte getPriorityFlag() {
        return this.priorityFlag;
    }
    
    public void setPriorityFlag(byte priorityFlag) {
        this.priorityFlag = priorityFlag;
    }

    
    @Column(name="FOLLOW_FLAG", nullable=false, precision=1, scale=0)
    public boolean isFollowFlag() {
        return this.followFlag;
    }
    
    public void setFollowFlag(boolean followFlag) {
        this.followFlag = followFlag;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perMilitaryCode")
    public Set<PerEmploymentMasters> getPerEmploymentMasterses() {
        return this.perEmploymentMasterses;
    }
    
    public void setPerEmploymentMasterses(Set<PerEmploymentMasters> perEmploymentMasterses) {
        this.perEmploymentMasterses = perEmploymentMasterses;
    }




}


