package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PerOrganizationStructure generated by hbm2java
 */
@Entity
@Table(name="PER_ORGANIZATION_STRUCTURE"
    ,schema="SHAMS"
    , uniqueConstraints = @UniqueConstraint(columnNames={"LOCATION_CODE", "ORGUNIT_CODE", "ORG_ID"}) 
)
public class PerOrganizationStructure  implements java.io.Serializable {


     private String orgId;
     private PerOrganizationStructure perOrganizationStructure;
     private PerOrgunitCode perOrgunitCode;
     private BudLocation budLocation;
     private String orgName;
     private String orgDesc;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private String orgCode;
     private String empDirectBoss;
     private String empBigBoss;
     private Set<PerAnnualEval> perAnnualEvals = new HashSet<PerAnnualEval>(0);
     private Set<PerAnnualEvalModel> perAnnualEvalModels = new HashSet<PerAnnualEvalModel>(0);
     private Set<PerHumanBalJobDistribute> perHumanBalJobDistributesForOrgIdMinus = new HashSet<PerHumanBalJobDistribute>(0);
     private Set<PerOrganizationStructure> perOrganizationStructures = new HashSet<PerOrganizationStructure>(0);
     private Set<PerHumanBalJobDistributeN> perHumanBalJobDistributeNsForOrgId = new HashSet<PerHumanBalJobDistributeN>(0);
     private Set<PerHumanBalOrg> perHumanBalOrgs = new HashSet<PerHumanBalOrg>(0);
     private Set<PerHumanBalOrgNew> perHumanBalOrgNews = new HashSet<PerHumanBalOrgNew>(0);
     private Set<PerComplaintData> perComplaintDatasForOrgIdExec = new HashSet<PerComplaintData>(0);
     private Set<PerEmpHistory> perEmpHistoriesForOrgId = new HashSet<PerEmpHistory>(0);
     private Set<PerEmploymentMasters> perEmploymentMastersesForOrgIdFrom = new HashSet<PerEmploymentMasters>(0);
     private Set<PerEmpHistory> perEmpHistoriesForOrgIdFrom = new HashSet<PerEmpHistory>(0);
     private Set<PerHumanBalJobDistributeN> perHumanBalJobDistributeNsForOrgIdMinus = new HashSet<PerHumanBalJobDistributeN>(0);
     private Set<PerHumanPlan> perHumanPlans = new HashSet<PerHumanPlan>(0);
     private Set<PerHumanBalJobDistribute> perHumanBalJobDistributesForOrgId = new HashSet<PerHumanBalJobDistribute>(0);
     private Set<PerComplaintData> perComplaintDatasForOrgId = new HashSet<PerComplaintData>(0);
     private Set<PerEmploymentMasters> perEmploymentMastersesForOrgId = new HashSet<PerEmploymentMasters>(0);

    public PerOrganizationStructure() {
    }

	
    public PerOrganizationStructure(String orgId, BudLocation budLocation) {
        this.orgId = orgId;
        this.budLocation = budLocation;
    }
    public PerOrganizationStructure(String orgId, PerOrganizationStructure perOrganizationStructure, PerOrgunitCode perOrgunitCode, BudLocation budLocation, String orgName, String orgDesc, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, String orgCode, String empDirectBoss, String empBigBoss, Set<PerAnnualEval> perAnnualEvals, Set<PerAnnualEvalModel> perAnnualEvalModels, Set<PerHumanBalJobDistribute> perHumanBalJobDistributesForOrgIdMinus, Set<PerOrganizationStructure> perOrganizationStructures, Set<PerHumanBalJobDistributeN> perHumanBalJobDistributeNsForOrgId, Set<PerHumanBalOrg> perHumanBalOrgs, Set<PerHumanBalOrgNew> perHumanBalOrgNews, Set<PerComplaintData> perComplaintDatasForOrgIdExec, Set<PerEmpHistory> perEmpHistoriesForOrgId, Set<PerEmploymentMasters> perEmploymentMastersesForOrgIdFrom, Set<PerEmpHistory> perEmpHistoriesForOrgIdFrom, Set<PerHumanBalJobDistributeN> perHumanBalJobDistributeNsForOrgIdMinus, Set<PerHumanPlan> perHumanPlans, Set<PerHumanBalJobDistribute> perHumanBalJobDistributesForOrgId, Set<PerComplaintData> perComplaintDatasForOrgId, Set<PerEmploymentMasters> perEmploymentMastersesForOrgId) {
       this.orgId = orgId;
       this.perOrganizationStructure = perOrganizationStructure;
       this.perOrgunitCode = perOrgunitCode;
       this.budLocation = budLocation;
       this.orgName = orgName;
       this.orgDesc = orgDesc;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.orgCode = orgCode;
       this.empDirectBoss = empDirectBoss;
       this.empBigBoss = empBigBoss;
       this.perAnnualEvals = perAnnualEvals;
       this.perAnnualEvalModels = perAnnualEvalModels;
       this.perHumanBalJobDistributesForOrgIdMinus = perHumanBalJobDistributesForOrgIdMinus;
       this.perOrganizationStructures = perOrganizationStructures;
       this.perHumanBalJobDistributeNsForOrgId = perHumanBalJobDistributeNsForOrgId;
       this.perHumanBalOrgs = perHumanBalOrgs;
       this.perHumanBalOrgNews = perHumanBalOrgNews;
       this.perComplaintDatasForOrgIdExec = perComplaintDatasForOrgIdExec;
       this.perEmpHistoriesForOrgId = perEmpHistoriesForOrgId;
       this.perEmploymentMastersesForOrgIdFrom = perEmploymentMastersesForOrgIdFrom;
       this.perEmpHistoriesForOrgIdFrom = perEmpHistoriesForOrgIdFrom;
       this.perHumanBalJobDistributeNsForOrgIdMinus = perHumanBalJobDistributeNsForOrgIdMinus;
       this.perHumanPlans = perHumanPlans;
       this.perHumanBalJobDistributesForOrgId = perHumanBalJobDistributesForOrgId;
       this.perComplaintDatasForOrgId = perComplaintDatasForOrgId;
       this.perEmploymentMastersesForOrgId = perEmploymentMastersesForOrgId;
    }
   
     @Id 

    
    @Column(name="ORG_ID", unique=true, nullable=false, length=5)
    public String getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="PARENT_ORG_ID")
    public PerOrganizationStructure getPerOrganizationStructure() {
        return this.perOrganizationStructure;
    }
    
    public void setPerOrganizationStructure(PerOrganizationStructure perOrganizationStructure) {
        this.perOrganizationStructure = perOrganizationStructure;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ORGUNIT_CODE")
    public PerOrgunitCode getPerOrgunitCode() {
        return this.perOrgunitCode;
    }
    
    public void setPerOrgunitCode(PerOrgunitCode perOrgunitCode) {
        this.perOrgunitCode = perOrgunitCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="LOCATION_CODE", nullable=false)
    public BudLocation getBudLocation() {
        return this.budLocation;
    }
    
    public void setBudLocation(BudLocation budLocation) {
        this.budLocation = budLocation;
    }

    
    @Column(name="ORG_NAME", length=100)
    public String getOrgName() {
        return this.orgName;
    }
    
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    
    @Column(name="ORG_DESC", length=1000)
    public String getOrgDesc() {
        return this.orgDesc;
    }
    
    public void setOrgDesc(String orgDesc) {
        this.orgDesc = orgDesc;
    }

    
    @Column(name="RECORD_CREATE_USER", length=5)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

    
    @Column(name="ORG_CODE", length=15)
    public String getOrgCode() {
        return this.orgCode;
    }
    
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    
    @Column(name="EMP_DIRECT_BOSS", length=10)
    public String getEmpDirectBoss() {
        return this.empDirectBoss;
    }
    
    public void setEmpDirectBoss(String empDirectBoss) {
        this.empDirectBoss = empDirectBoss;
    }

    
    @Column(name="EMP_BIG_BOSS", length=10)
    public String getEmpBigBoss() {
        return this.empBigBoss;
    }
    
    public void setEmpBigBoss(String empBigBoss) {
        this.empBigBoss = empBigBoss;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perOrganizationStructure")
    public Set<PerAnnualEval> getPerAnnualEvals() {
        return this.perAnnualEvals;
    }
    
    public void setPerAnnualEvals(Set<PerAnnualEval> perAnnualEvals) {
        this.perAnnualEvals = perAnnualEvals;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perOrganizationStructure")
    public Set<PerAnnualEvalModel> getPerAnnualEvalModels() {
        return this.perAnnualEvalModels;
    }
    
    public void setPerAnnualEvalModels(Set<PerAnnualEvalModel> perAnnualEvalModels) {
        this.perAnnualEvalModels = perAnnualEvalModels;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perOrganizationStructureByOrgIdMinus")
    public Set<PerHumanBalJobDistribute> getPerHumanBalJobDistributesForOrgIdMinus() {
        return this.perHumanBalJobDistributesForOrgIdMinus;
    }
    
    public void setPerHumanBalJobDistributesForOrgIdMinus(Set<PerHumanBalJobDistribute> perHumanBalJobDistributesForOrgIdMinus) {
        this.perHumanBalJobDistributesForOrgIdMinus = perHumanBalJobDistributesForOrgIdMinus;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perOrganizationStructure")
    public Set<PerOrganizationStructure> getPerOrganizationStructures() {
        return this.perOrganizationStructures;
    }
    
    public void setPerOrganizationStructures(Set<PerOrganizationStructure> perOrganizationStructures) {
        this.perOrganizationStructures = perOrganizationStructures;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perOrganizationStructureByOrgId")
    public Set<PerHumanBalJobDistributeN> getPerHumanBalJobDistributeNsForOrgId() {
        return this.perHumanBalJobDistributeNsForOrgId;
    }
    
    public void setPerHumanBalJobDistributeNsForOrgId(Set<PerHumanBalJobDistributeN> perHumanBalJobDistributeNsForOrgId) {
        this.perHumanBalJobDistributeNsForOrgId = perHumanBalJobDistributeNsForOrgId;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perOrganizationStructure")
    public Set<PerHumanBalOrg> getPerHumanBalOrgs() {
        return this.perHumanBalOrgs;
    }
    
    public void setPerHumanBalOrgs(Set<PerHumanBalOrg> perHumanBalOrgs) {
        this.perHumanBalOrgs = perHumanBalOrgs;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perOrganizationStructure")
    public Set<PerHumanBalOrgNew> getPerHumanBalOrgNews() {
        return this.perHumanBalOrgNews;
    }
    
    public void setPerHumanBalOrgNews(Set<PerHumanBalOrgNew> perHumanBalOrgNews) {
        this.perHumanBalOrgNews = perHumanBalOrgNews;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perOrganizationStructureByOrgIdExec")
    public Set<PerComplaintData> getPerComplaintDatasForOrgIdExec() {
        return this.perComplaintDatasForOrgIdExec;
    }
    
    public void setPerComplaintDatasForOrgIdExec(Set<PerComplaintData> perComplaintDatasForOrgIdExec) {
        this.perComplaintDatasForOrgIdExec = perComplaintDatasForOrgIdExec;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perOrganizationStructureByOrgId")
    public Set<PerEmpHistory> getPerEmpHistoriesForOrgId() {
        return this.perEmpHistoriesForOrgId;
    }
    
    public void setPerEmpHistoriesForOrgId(Set<PerEmpHistory> perEmpHistoriesForOrgId) {
        this.perEmpHistoriesForOrgId = perEmpHistoriesForOrgId;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perOrganizationStructureByOrgIdFrom")
    public Set<PerEmploymentMasters> getPerEmploymentMastersesForOrgIdFrom() {
        return this.perEmploymentMastersesForOrgIdFrom;
    }
    
    public void setPerEmploymentMastersesForOrgIdFrom(Set<PerEmploymentMasters> perEmploymentMastersesForOrgIdFrom) {
        this.perEmploymentMastersesForOrgIdFrom = perEmploymentMastersesForOrgIdFrom;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perOrganizationStructureByOrgIdFrom")
    public Set<PerEmpHistory> getPerEmpHistoriesForOrgIdFrom() {
        return this.perEmpHistoriesForOrgIdFrom;
    }
    
    public void setPerEmpHistoriesForOrgIdFrom(Set<PerEmpHistory> perEmpHistoriesForOrgIdFrom) {
        this.perEmpHistoriesForOrgIdFrom = perEmpHistoriesForOrgIdFrom;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perOrganizationStructureByOrgIdMinus")
    public Set<PerHumanBalJobDistributeN> getPerHumanBalJobDistributeNsForOrgIdMinus() {
        return this.perHumanBalJobDistributeNsForOrgIdMinus;
    }
    
    public void setPerHumanBalJobDistributeNsForOrgIdMinus(Set<PerHumanBalJobDistributeN> perHumanBalJobDistributeNsForOrgIdMinus) {
        this.perHumanBalJobDistributeNsForOrgIdMinus = perHumanBalJobDistributeNsForOrgIdMinus;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perOrganizationStructure")
    public Set<PerHumanPlan> getPerHumanPlans() {
        return this.perHumanPlans;
    }
    
    public void setPerHumanPlans(Set<PerHumanPlan> perHumanPlans) {
        this.perHumanPlans = perHumanPlans;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perOrganizationStructureByOrgId")
    public Set<PerHumanBalJobDistribute> getPerHumanBalJobDistributesForOrgId() {
        return this.perHumanBalJobDistributesForOrgId;
    }
    
    public void setPerHumanBalJobDistributesForOrgId(Set<PerHumanBalJobDistribute> perHumanBalJobDistributesForOrgId) {
        this.perHumanBalJobDistributesForOrgId = perHumanBalJobDistributesForOrgId;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perOrganizationStructureByOrgId")
    public Set<PerComplaintData> getPerComplaintDatasForOrgId() {
        return this.perComplaintDatasForOrgId;
    }
    
    public void setPerComplaintDatasForOrgId(Set<PerComplaintData> perComplaintDatasForOrgId) {
        this.perComplaintDatasForOrgId = perComplaintDatasForOrgId;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perOrganizationStructureByOrgId")
    public Set<PerEmploymentMasters> getPerEmploymentMastersesForOrgId() {
        return this.perEmploymentMastersesForOrgId;
    }
    
    public void setPerEmploymentMastersesForOrgId(Set<PerEmploymentMasters> perEmploymentMastersesForOrgId) {
        this.perEmploymentMastersesForOrgId = perEmploymentMastersesForOrgId;
    }




}


