package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PerPromotionGradeRuleN generated by hbm2java
 */
@Entity
@Table(name="PER_PROMOTION_GRADE_RULE_N"
    ,schema="SHAMS"
)
public class PerPromotionGradeRuleN  implements java.io.Serializable {


     private PerPromotionGradeRuleNId id;
     private PerFiscalDegreeCodeNew perFiscalDegreeCodeNew;
     private PerPromotionTransNew perPromotionTransNew;
     private PerEvalPercentage perEvalPercentage;
     private String annualId;

    public PerPromotionGradeRuleN() {
    }

    public PerPromotionGradeRuleN(PerPromotionGradeRuleNId id, PerFiscalDegreeCodeNew perFiscalDegreeCodeNew, PerPromotionTransNew perPromotionTransNew, PerEvalPercentage perEvalPercentage, String annualId) {
       this.id = id;
       this.perFiscalDegreeCodeNew = perFiscalDegreeCodeNew;
       this.perPromotionTransNew = perPromotionTransNew;
       this.perEvalPercentage = perEvalPercentage;
       this.annualId = annualId;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="gradeRuleId", column=@Column(name="GRADE_RULE_ID", nullable=false, length=3) ), 
        @AttributeOverride(name="transId", column=@Column(name="TRANS_ID", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="promotionType", column=@Column(name="PROMOTION_TYPE", nullable=false, length=5) ), 
        @AttributeOverride(name="locationCode", column=@Column(name="LOCATION_CODE", nullable=false, length=3) ) } )
    public PerPromotionGradeRuleNId getId() {
        return this.id;
    }
    
    public void setId(PerPromotionGradeRuleNId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="FISCAL_DEGREE_CODE_NEW", nullable=false)
    public PerFiscalDegreeCodeNew getPerFiscalDegreeCodeNew() {
        return this.perFiscalDegreeCodeNew;
    }
    
    public void setPerFiscalDegreeCodeNew(PerFiscalDegreeCodeNew perFiscalDegreeCodeNew) {
        this.perFiscalDegreeCodeNew = perFiscalDegreeCodeNew;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="LOCATION_CODE", referencedColumnName="LOCATION_CODE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="PROMOTION_TYPE", referencedColumnName="PROMOTION_TYPE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="TRANS_ID", referencedColumnName="TRANS_ID", nullable=false, insertable=false, updatable=false) } )
    public PerPromotionTransNew getPerPromotionTransNew() {
        return this.perPromotionTransNew;
    }
    
    public void setPerPromotionTransNew(PerPromotionTransNew perPromotionTransNew) {
        this.perPromotionTransNew = perPromotionTransNew;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="GRADE_CODE", nullable=false)
    public PerEvalPercentage getPerEvalPercentage() {
        return this.perEvalPercentage;
    }
    
    public void setPerEvalPercentage(PerEvalPercentage perEvalPercentage) {
        this.perEvalPercentage = perEvalPercentage;
    }

    
    @Column(name="ANNUAL_ID", nullable=false, length=5)
    public String getAnnualId() {
        return this.annualId;
    }
    
    public void setAnnualId(String annualId) {
        this.annualId = annualId;
    }




}


