package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerPromotionTrans generated by hbm2java
 */
@Entity
@Table(name="PER_PROMOTION_TRANS"
    ,schema="SHAMS"
)
public class PerPromotionTrans  implements java.io.Serializable {


     private PerPromotionTransId id;
     private PerCommityMaster perCommityMaster;
     private PerFiscalDegreeCode perFiscalDegreeCodeByFiscalDegreeCodeEndSalary;
     private PerFiscalDegreeCode perFiscalDegreeCodeByFiscalDegreeCodeNew;
     private PerGroupTypeCode perGroupTypeCode;
     private PerJobCode perJobCode;
     private PerPromotionRule perPromotionRule;
     private BudLocation budLocation;
     private Date promotionDate;
     private String fiscalDegreeCode;
     private Byte promotionRate;
     private boolean aprPromotion;
     private String decisionNo;
     private Date decisionDate;
     private Date postDate;
     private Byte promotionRateMain;
     private BigDecimal elawaRatio;
     private Date salaryMonth;
     private boolean elawaCalc;
     private boolean degreeEndSalaryFlg;
     private Short VBandCode;
     private Byte VMethodType;
     private Byte addElawaType;
     private Set<PerEmpPromotion> perEmpPromotions = new HashSet<PerEmpPromotion>(0);

    public PerPromotionTrans() {
    }

	
    public PerPromotionTrans(PerPromotionTransId id, PerCommityMaster perCommityMaster, PerFiscalDegreeCode perFiscalDegreeCodeByFiscalDegreeCodeNew, PerPromotionRule perPromotionRule, BudLocation budLocation, Date promotionDate, String fiscalDegreeCode, boolean aprPromotion, boolean elawaCalc, boolean degreeEndSalaryFlg) {
        this.id = id;
        this.perCommityMaster = perCommityMaster;
        this.perFiscalDegreeCodeByFiscalDegreeCodeNew = perFiscalDegreeCodeByFiscalDegreeCodeNew;
        this.perPromotionRule = perPromotionRule;
        this.budLocation = budLocation;
        this.promotionDate = promotionDate;
        this.fiscalDegreeCode = fiscalDegreeCode;
        this.aprPromotion = aprPromotion;
        this.elawaCalc = elawaCalc;
        this.degreeEndSalaryFlg = degreeEndSalaryFlg;
    }
    public PerPromotionTrans(PerPromotionTransId id, PerCommityMaster perCommityMaster, PerFiscalDegreeCode perFiscalDegreeCodeByFiscalDegreeCodeEndSalary, PerFiscalDegreeCode perFiscalDegreeCodeByFiscalDegreeCodeNew, PerGroupTypeCode perGroupTypeCode, PerJobCode perJobCode, PerPromotionRule perPromotionRule, BudLocation budLocation, Date promotionDate, String fiscalDegreeCode, Byte promotionRate, boolean aprPromotion, String decisionNo, Date decisionDate, Date postDate, Byte promotionRateMain, BigDecimal elawaRatio, Date salaryMonth, boolean elawaCalc, boolean degreeEndSalaryFlg, Short VBandCode, Byte VMethodType, Byte addElawaType, Set<PerEmpPromotion> perEmpPromotions) {
       this.id = id;
       this.perCommityMaster = perCommityMaster;
       this.perFiscalDegreeCodeByFiscalDegreeCodeEndSalary = perFiscalDegreeCodeByFiscalDegreeCodeEndSalary;
       this.perFiscalDegreeCodeByFiscalDegreeCodeNew = perFiscalDegreeCodeByFiscalDegreeCodeNew;
       this.perGroupTypeCode = perGroupTypeCode;
       this.perJobCode = perJobCode;
       this.perPromotionRule = perPromotionRule;
       this.budLocation = budLocation;
       this.promotionDate = promotionDate;
       this.fiscalDegreeCode = fiscalDegreeCode;
       this.promotionRate = promotionRate;
       this.aprPromotion = aprPromotion;
       this.decisionNo = decisionNo;
       this.decisionDate = decisionDate;
       this.postDate = postDate;
       this.promotionRateMain = promotionRateMain;
       this.elawaRatio = elawaRatio;
       this.salaryMonth = salaryMonth;
       this.elawaCalc = elawaCalc;
       this.degreeEndSalaryFlg = degreeEndSalaryFlg;
       this.VBandCode = VBandCode;
       this.VMethodType = VMethodType;
       this.addElawaType = addElawaType;
       this.perEmpPromotions = perEmpPromotions;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="locationCode", column=@Column(name="LOCATION_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="promotionType", column=@Column(name="PROMOTION_TYPE", nullable=false, length=5) ), 
        @AttributeOverride(name="transId", column=@Column(name="TRANS_ID", nullable=false, precision=10, scale=0) ) } )
    public PerPromotionTransId getId() {
        return this.id;
    }
    
    public void setId(PerPromotionTransId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( { 
        @JoinColumn(name="LOCATION_CODE", referencedColumnName="LOCATION_CODE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="COMMITY_NO", referencedColumnName="COMMITY_NO", insertable=false, updatable=false) } )
    public PerCommityMaster getPerCommityMaster() {
        return this.perCommityMaster;
    }
    
    public void setPerCommityMaster(PerCommityMaster perCommityMaster) {
        this.perCommityMaster = perCommityMaster;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="FISCAL_DEGREE_CODE_END_SALARY")
    public PerFiscalDegreeCode getPerFiscalDegreeCodeByFiscalDegreeCodeEndSalary() {
        return this.perFiscalDegreeCodeByFiscalDegreeCodeEndSalary;
    }
    
    public void setPerFiscalDegreeCodeByFiscalDegreeCodeEndSalary(PerFiscalDegreeCode perFiscalDegreeCodeByFiscalDegreeCodeEndSalary) {
        this.perFiscalDegreeCodeByFiscalDegreeCodeEndSalary = perFiscalDegreeCodeByFiscalDegreeCodeEndSalary;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="FISCAL_DEGREE_CODE_NEW", nullable=false)
    public PerFiscalDegreeCode getPerFiscalDegreeCodeByFiscalDegreeCodeNew() {
        return this.perFiscalDegreeCodeByFiscalDegreeCodeNew;
    }
    
    public void setPerFiscalDegreeCodeByFiscalDegreeCodeNew(PerFiscalDegreeCode perFiscalDegreeCodeByFiscalDegreeCodeNew) {
        this.perFiscalDegreeCodeByFiscalDegreeCodeNew = perFiscalDegreeCodeByFiscalDegreeCodeNew;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="GROUP_TYPE_CODE")
    public PerGroupTypeCode getPerGroupTypeCode() {
        return this.perGroupTypeCode;
    }
    
    public void setPerGroupTypeCode(PerGroupTypeCode perGroupTypeCode) {
        this.perGroupTypeCode = perGroupTypeCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="JOB_CODE")
    public PerJobCode getPerJobCode() {
        return this.perJobCode;
    }
    
    public void setPerJobCode(PerJobCode perJobCode) {
        this.perJobCode = perJobCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="PROMOTION_TYPE", nullable=false, insertable=false, updatable=false)
    public PerPromotionRule getPerPromotionRule() {
        return this.perPromotionRule;
    }
    
    public void setPerPromotionRule(PerPromotionRule perPromotionRule) {
        this.perPromotionRule = perPromotionRule;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="LOCATION_CODE", nullable=false, insertable=false, updatable=false)
    public BudLocation getBudLocation() {
        return this.budLocation;
    }
    
    public void setBudLocation(BudLocation budLocation) {
        this.budLocation = budLocation;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="PROMOTION_DATE", nullable=false, length=7)
    public Date getPromotionDate() {
        return this.promotionDate;
    }
    
    public void setPromotionDate(Date promotionDate) {
        this.promotionDate = promotionDate;
    }

    
    @Column(name="FISCAL_DEGREE_CODE", nullable=false, length=3)
    public String getFiscalDegreeCode() {
        return this.fiscalDegreeCode;
    }
    
    public void setFiscalDegreeCode(String fiscalDegreeCode) {
        this.fiscalDegreeCode = fiscalDegreeCode;
    }

    
    @Column(name="PROMOTION_RATE", precision=2, scale=0)
    public Byte getPromotionRate() {
        return this.promotionRate;
    }
    
    public void setPromotionRate(Byte promotionRate) {
        this.promotionRate = promotionRate;
    }

    
    @Column(name="APR_PROMOTION", nullable=false, precision=1, scale=0)
    public boolean isAprPromotion() {
        return this.aprPromotion;
    }
    
    public void setAprPromotion(boolean aprPromotion) {
        this.aprPromotion = aprPromotion;
    }

    
    @Column(name="DECISION_NO", length=10)
    public String getDecisionNo() {
        return this.decisionNo;
    }
    
    public void setDecisionNo(String decisionNo) {
        this.decisionNo = decisionNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DECISION_DATE", length=7)
    public Date getDecisionDate() {
        return this.decisionDate;
    }
    
    public void setDecisionDate(Date decisionDate) {
        this.decisionDate = decisionDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="POST_DATE", length=7)
    public Date getPostDate() {
        return this.postDate;
    }
    
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }

    
    @Column(name="PROMOTION_RATE_MAIN", precision=2, scale=0)
    public Byte getPromotionRateMain() {
        return this.promotionRateMain;
    }
    
    public void setPromotionRateMain(Byte promotionRateMain) {
        this.promotionRateMain = promotionRateMain;
    }

    
    @Column(name="ELAWA_RATIO", precision=5)
    public BigDecimal getElawaRatio() {
        return this.elawaRatio;
    }
    
    public void setElawaRatio(BigDecimal elawaRatio) {
        this.elawaRatio = elawaRatio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="SALARY_MONTH", length=7)
    public Date getSalaryMonth() {
        return this.salaryMonth;
    }
    
    public void setSalaryMonth(Date salaryMonth) {
        this.salaryMonth = salaryMonth;
    }

    
    @Column(name="ELAWA_CALC", nullable=false, precision=1, scale=0)
    public boolean isElawaCalc() {
        return this.elawaCalc;
    }
    
    public void setElawaCalc(boolean elawaCalc) {
        this.elawaCalc = elawaCalc;
    }

    
    @Column(name="DEGREE_END_SALARY_FLG", nullable=false, precision=1, scale=0)
    public boolean isDegreeEndSalaryFlg() {
        return this.degreeEndSalaryFlg;
    }
    
    public void setDegreeEndSalaryFlg(boolean degreeEndSalaryFlg) {
        this.degreeEndSalaryFlg = degreeEndSalaryFlg;
    }

    
    @Column(name="V_BAND_CODE", precision=4, scale=0)
    public Short getVBandCode() {
        return this.VBandCode;
    }
    
    public void setVBandCode(Short VBandCode) {
        this.VBandCode = VBandCode;
    }

    
    @Column(name="V_METHOD_TYPE", precision=2, scale=0)
    public Byte getVMethodType() {
        return this.VMethodType;
    }
    
    public void setVMethodType(Byte VMethodType) {
        this.VMethodType = VMethodType;
    }

    
    @Column(name="ADD_ELAWA_TYPE", precision=2, scale=0)
    public Byte getAddElawaType() {
        return this.addElawaType;
    }
    
    public void setAddElawaType(Byte addElawaType) {
        this.addElawaType = addElawaType;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perPromotionTrans")
    public Set<PerEmpPromotion> getPerEmpPromotions() {
        return this.perEmpPromotions;
    }
    
    public void setPerEmpPromotions(Set<PerEmpPromotion> perEmpPromotions) {
        this.perEmpPromotions = perEmpPromotions;
    }




}


