package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerPromotionRule generated by hbm2java
 */
@Entity
@Table(name="PER_PROMOTION_RULE"
    ,schema="SHAMS"
)
public class PerPromotionRule  implements java.io.Serializable {


     private String promotionType;
     private PerGeneralCode perGeneralCode;
     private String promotionName;
     private boolean promotionMethod;
     private boolean promotionAction;
     private boolean periodFlag;
     private boolean emptyDegreeFlag;
     private String remarks;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private Set<PerPromotionTrans> perPromotionTranses = new HashSet<PerPromotionTrans>(0);
     private Set<PerPromotionTransNew> perPromotionTransNews = new HashSet<PerPromotionTransNew>(0);

    public PerPromotionRule() {
    }

	
    public PerPromotionRule(String promotionType, PerGeneralCode perGeneralCode, String promotionName, boolean promotionMethod, boolean promotionAction, boolean periodFlag, boolean emptyDegreeFlag) {
        this.promotionType = promotionType;
        this.perGeneralCode = perGeneralCode;
        this.promotionName = promotionName;
        this.promotionMethod = promotionMethod;
        this.promotionAction = promotionAction;
        this.periodFlag = periodFlag;
        this.emptyDegreeFlag = emptyDegreeFlag;
    }
    public PerPromotionRule(String promotionType, PerGeneralCode perGeneralCode, String promotionName, boolean promotionMethod, boolean promotionAction, boolean periodFlag, boolean emptyDegreeFlag, String remarks, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, Set<PerPromotionTrans> perPromotionTranses, Set<PerPromotionTransNew> perPromotionTransNews) {
       this.promotionType = promotionType;
       this.perGeneralCode = perGeneralCode;
       this.promotionName = promotionName;
       this.promotionMethod = promotionMethod;
       this.promotionAction = promotionAction;
       this.periodFlag = periodFlag;
       this.emptyDegreeFlag = emptyDegreeFlag;
       this.remarks = remarks;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.perPromotionTranses = perPromotionTranses;
       this.perPromotionTransNews = perPromotionTransNews;
    }
   
     @Id 

    
    @Column(name="PROMOTION_TYPE", unique=true, nullable=false, length=5)
    public String getPromotionType() {
        return this.promotionType;
    }
    
    public void setPromotionType(String promotionType) {
        this.promotionType = promotionType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GENERAL_CODE", nullable=false)
    public PerGeneralCode getPerGeneralCode() {
        return this.perGeneralCode;
    }
    
    public void setPerGeneralCode(PerGeneralCode perGeneralCode) {
        this.perGeneralCode = perGeneralCode;
    }

    
    @Column(name="PROMOTION_NAME", nullable=false, length=30)
    public String getPromotionName() {
        return this.promotionName;
    }
    
    public void setPromotionName(String promotionName) {
        this.promotionName = promotionName;
    }

    
    @Column(name="PROMOTION_METHOD", nullable=false, precision=1, scale=0)
    public boolean isPromotionMethod() {
        return this.promotionMethod;
    }
    
    public void setPromotionMethod(boolean promotionMethod) {
        this.promotionMethod = promotionMethod;
    }

    
    @Column(name="PROMOTION_ACTION", nullable=false, precision=1, scale=0)
    public boolean isPromotionAction() {
        return this.promotionAction;
    }
    
    public void setPromotionAction(boolean promotionAction) {
        this.promotionAction = promotionAction;
    }

    
    @Column(name="PERIOD_FLAG", nullable=false, precision=1, scale=0)
    public boolean isPeriodFlag() {
        return this.periodFlag;
    }
    
    public void setPeriodFlag(boolean periodFlag) {
        this.periodFlag = periodFlag;
    }

    
    @Column(name="EMPTY_DEGREE_FLAG", nullable=false, precision=1, scale=0)
    public boolean isEmptyDegreeFlag() {
        return this.emptyDegreeFlag;
    }
    
    public void setEmptyDegreeFlag(boolean emptyDegreeFlag) {
        this.emptyDegreeFlag = emptyDegreeFlag;
    }

    
    @Column(name="REMARKS", length=100)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perPromotionRule")
    public Set<PerPromotionTrans> getPerPromotionTranses() {
        return this.perPromotionTranses;
    }
    
    public void setPerPromotionTranses(Set<PerPromotionTrans> perPromotionTranses) {
        this.perPromotionTranses = perPromotionTranses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="perPromotionRule")
    public Set<PerPromotionTransNew> getPerPromotionTransNews() {
        return this.perPromotionTransNews;
    }
    
    public void setPerPromotionTransNews(Set<PerPromotionTransNew> perPromotionTransNews) {
        this.perPromotionTransNews = perPromotionTransNews;
    }




}


