package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PerPromotionTrainRuleN generated by hbm2java
 */
@Entity
@Table(name="PER_PROMOTION_TRAIN_RULE_N"
    ,schema="SHAMS"
)
public class PerPromotionTrainRuleN  implements java.io.Serializable {


     private PerPromotionTrainRuleNId id;
     private PerPromotionTransNew perPromotionTransNew;
     private PerGroupTypeCode perGroupTypeCode;
     private String scopeTypeCode;
     private String courseCode;

    public PerPromotionTrainRuleN() {
    }

    public PerPromotionTrainRuleN(PerPromotionTrainRuleNId id, PerPromotionTransNew perPromotionTransNew, PerGroupTypeCode perGroupTypeCode, String scopeTypeCode, String courseCode) {
       this.id = id;
       this.perPromotionTransNew = perPromotionTransNew;
       this.perGroupTypeCode = perGroupTypeCode;
       this.scopeTypeCode = scopeTypeCode;
       this.courseCode = courseCode;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="locationCode", column=@Column(name="LOCATION_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="promotionType", column=@Column(name="PROMOTION_TYPE", nullable=false, length=5) ), 
        @AttributeOverride(name="transId", column=@Column(name="TRANS_ID", nullable=false, precision=10, scale=0) ), 
        @AttributeOverride(name="trainRuleId", column=@Column(name="TRAIN_RULE_ID", nullable=false, length=3) ) } )
    public PerPromotionTrainRuleNId getId() {
        return this.id;
    }
    
    public void setId(PerPromotionTrainRuleNId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="LOCATION_CODE", referencedColumnName="LOCATION_CODE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="PROMOTION_TYPE", referencedColumnName="PROMOTION_TYPE", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="TRANS_ID", referencedColumnName="TRANS_ID", nullable=false, insertable=false, updatable=false) } )
    public PerPromotionTransNew getPerPromotionTransNew() {
        return this.perPromotionTransNew;
    }
    
    public void setPerPromotionTransNew(PerPromotionTransNew perPromotionTransNew) {
        this.perPromotionTransNew = perPromotionTransNew;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="GROUP_TYPE_CODE", nullable=false)
    public PerGroupTypeCode getPerGroupTypeCode() {
        return this.perGroupTypeCode;
    }
    
    public void setPerGroupTypeCode(PerGroupTypeCode perGroupTypeCode) {
        this.perGroupTypeCode = perGroupTypeCode;
    }

    
    @Column(name="SCOPE_TYPE_CODE", nullable=false, length=5)
    public String getScopeTypeCode() {
        return this.scopeTypeCode;
    }
    
    public void setScopeTypeCode(String scopeTypeCode) {
        this.scopeTypeCode = scopeTypeCode;
    }

    
    @Column(name="COURSE_CODE", nullable=false, length=5)
    public String getCourseCode() {
        return this.courseCode;
    }
    
    public void setCourseCode(String courseCode) {
        this.courseCode = courseCode;
    }




}


