package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerQualCode generated by hbm2java
 */
@Entity
@Table(name="PER_QUAL_CODE"
    ,schema="SHAMS"
)
public class PerQualCode  implements java.io.Serializable {


     private String qualCode;
     private PerQualClass perQualClass;
     private String qualName;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private Set<PayExecutionSpecificEmp> payExecutionSpecificEmps = new HashSet<PayExecutionSpecificEmp>(0);
     private Set<PerEmpQualification> perEmpQualifications = new HashSet<PerEmpQualification>(0);
     private Set<PerEmploymentMasters> perEmploymentMastersesForQualCodeFirst = new HashSet<PerEmploymentMasters>(0);
     private Set<PerQualSpecialist> perQualSpecialists = new HashSet<PerQualSpecialist>(0);
     private Set<PerJobDetail> perJobDetails = new HashSet<PerJobDetail>(0);
     private Set<PerEmploymentMasters> perEmploymentMastersesForQualCodeBegin = new HashSet<PerEmploymentMasters>(0);
     private Set<PerEmploymentMasters> perEmploymentMastersesForQualCode = new HashSet<PerEmploymentMasters>(0);
     private Set<PerQualFaculty> perQualFaculties = new HashSet<PerQualFaculty>(0);

    public PerQualCode() {
    }

	
    public PerQualCode(String qualCode, PerQualClass perQualClass, String qualName) {
        this.qualCode = qualCode;
        this.perQualClass = perQualClass;
        this.qualName = qualName;
    }
    public PerQualCode(String qualCode, PerQualClass perQualClass, String qualName, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, Set<PayExecutionSpecificEmp> payExecutionSpecificEmps, Set<PerEmpQualification> perEmpQualifications, Set<PerEmploymentMasters> perEmploymentMastersesForQualCodeFirst, Set<PerQualSpecialist> perQualSpecialists, Set<PerJobDetail> perJobDetails, Set<PerEmploymentMasters> perEmploymentMastersesForQualCodeBegin, Set<PerEmploymentMasters> perEmploymentMastersesForQualCode, Set<PerQualFaculty> perQualFaculties) {
       this.qualCode = qualCode;
       this.perQualClass = perQualClass;
       this.qualName = qualName;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.payExecutionSpecificEmps = payExecutionSpecificEmps;
       this.perEmpQualifications = perEmpQualifications;
       this.perEmploymentMastersesForQualCodeFirst = perEmploymentMastersesForQualCodeFirst;
       this.perQualSpecialists = perQualSpecialists;
       this.perJobDetails = perJobDetails;
       this.perEmploymentMastersesForQualCodeBegin = perEmploymentMastersesForQualCodeBegin;
       this.perEmploymentMastersesForQualCode = perEmploymentMastersesForQualCode;
       this.perQualFaculties = perQualFaculties;
    }
   
     @Id 

    
    @Column(name="QUAL_CODE", unique=true, nullable=false, length=5)
    public String getQualCode() {
        return this.qualCode;
    }
    
    public void setQualCode(String qualCode) {
        this.qualCode = qualCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="QUAL_CLASS_CODE", nullable=false)
    public PerQualClass getPerQualClass() {
        return this.perQualClass;
    }
    
    public void setPerQualClass(PerQualClass perQualClass) {
        this.perQualClass = perQualClass;
    }

    
    @Column(name="QUAL_NAME", nullable=false, length=100)
    public String getQualName() {
        return this.qualName;
    }
    
    public void setQualName(String qualName) {
        this.qualName = qualName;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perQualCode")
    public Set<PayExecutionSpecificEmp> getPayExecutionSpecificEmps() {
        return this.payExecutionSpecificEmps;
    }
    
    public void setPayExecutionSpecificEmps(Set<PayExecutionSpecificEmp> payExecutionSpecificEmps) {
        this.payExecutionSpecificEmps = payExecutionSpecificEmps;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perQualCode")
    public Set<PerEmpQualification> getPerEmpQualifications() {
        return this.perEmpQualifications;
    }
    
    public void setPerEmpQualifications(Set<PerEmpQualification> perEmpQualifications) {
        this.perEmpQualifications = perEmpQualifications;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perQualCodeByQualCodeFirst")
    public Set<PerEmploymentMasters> getPerEmploymentMastersesForQualCodeFirst() {
        return this.perEmploymentMastersesForQualCodeFirst;
    }
    
    public void setPerEmploymentMastersesForQualCodeFirst(Set<PerEmploymentMasters> perEmploymentMastersesForQualCodeFirst) {
        this.perEmploymentMastersesForQualCodeFirst = perEmploymentMastersesForQualCodeFirst;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perQualCode")
    public Set<PerQualSpecialist> getPerQualSpecialists() {
        return this.perQualSpecialists;
    }
    
    public void setPerQualSpecialists(Set<PerQualSpecialist> perQualSpecialists) {
        this.perQualSpecialists = perQualSpecialists;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perQualCode")
    public Set<PerJobDetail> getPerJobDetails() {
        return this.perJobDetails;
    }
    
    public void setPerJobDetails(Set<PerJobDetail> perJobDetails) {
        this.perJobDetails = perJobDetails;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perQualCodeByQualCodeBegin")
    public Set<PerEmploymentMasters> getPerEmploymentMastersesForQualCodeBegin() {
        return this.perEmploymentMastersesForQualCodeBegin;
    }
    
    public void setPerEmploymentMastersesForQualCodeBegin(Set<PerEmploymentMasters> perEmploymentMastersesForQualCodeBegin) {
        this.perEmploymentMastersesForQualCodeBegin = perEmploymentMastersesForQualCodeBegin;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perQualCodeByQualCode")
    public Set<PerEmploymentMasters> getPerEmploymentMastersesForQualCode() {
        return this.perEmploymentMastersesForQualCode;
    }
    
    public void setPerEmploymentMastersesForQualCode(Set<PerEmploymentMasters> perEmploymentMastersesForQualCode) {
        this.perEmploymentMastersesForQualCode = perEmploymentMastersesForQualCode;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perQualCode")
    public Set<PerQualFaculty> getPerQualFaculties() {
        return this.perQualFaculties;
    }
    
    public void setPerQualFaculties(Set<PerQualFaculty> perQualFaculties) {
        this.perQualFaculties = perQualFaculties;
    }




}


