package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PerSetup generated by hbm2java
 */
@Entity
@Table(name="PER_SETUP"
    ,schema="SHAMS"
)
public class PerSetup  implements java.io.Serializable {


     private PerSetupId id;
     private BudLocation budLocation;
     private String perOrgMan;
     private boolean attendanceFlg;
     private boolean historyFlg;
     private String perOrgManTitle;
     private String signature1;
     private String title1;
     private String signature2;
     private String title2;
     private String signature3;
     private String title3;
     private String signature4;
     private String title4;
     private String signature5;
     private String title5;
     private String signature6;
     private String title6;
     private String notes;
     private String bhSignature1;
     private String bhTitle1;
     private String bhSignature2;
     private String bhTitle2;
     private String bhSignature3;
     private String bhTitle3;
     private String bhNotes;
     private String bhGehaName;
     private String signature7;
     private String title7;
     private String bhSignature4;
     private String bhTitle4;
     private String bhSignature5;
     private String bhTitle5;
     private String attendancePwd;
     private Boolean chkTerm;

    public PerSetup() {
    }

	
    public PerSetup(PerSetupId id, BudLocation budLocation, boolean attendanceFlg, boolean historyFlg) {
        this.id = id;
        this.budLocation = budLocation;
        this.attendanceFlg = attendanceFlg;
        this.historyFlg = historyFlg;
    }
    public PerSetup(PerSetupId id, BudLocation budLocation, String perOrgMan, boolean attendanceFlg, boolean historyFlg, String perOrgManTitle, String signature1, String title1, String signature2, String title2, String signature3, String title3, String signature4, String title4, String signature5, String title5, String signature6, String title6, String notes, String bhSignature1, String bhTitle1, String bhSignature2, String bhTitle2, String bhSignature3, String bhTitle3, String bhNotes, String bhGehaName, String signature7, String title7, String bhSignature4, String bhTitle4, String bhSignature5, String bhTitle5, String attendancePwd, Boolean chkTerm) {
       this.id = id;
       this.budLocation = budLocation;
       this.perOrgMan = perOrgMan;
       this.attendanceFlg = attendanceFlg;
       this.historyFlg = historyFlg;
       this.perOrgManTitle = perOrgManTitle;
       this.signature1 = signature1;
       this.title1 = title1;
       this.signature2 = signature2;
       this.title2 = title2;
       this.signature3 = signature3;
       this.title3 = title3;
       this.signature4 = signature4;
       this.title4 = title4;
       this.signature5 = signature5;
       this.title5 = title5;
       this.signature6 = signature6;
       this.title6 = title6;
       this.notes = notes;
       this.bhSignature1 = bhSignature1;
       this.bhTitle1 = bhTitle1;
       this.bhSignature2 = bhSignature2;
       this.bhTitle2 = bhTitle2;
       this.bhSignature3 = bhSignature3;
       this.bhTitle3 = bhTitle3;
       this.bhNotes = bhNotes;
       this.bhGehaName = bhGehaName;
       this.signature7 = signature7;
       this.title7 = title7;
       this.bhSignature4 = bhSignature4;
       this.bhTitle4 = bhTitle4;
       this.bhSignature5 = bhSignature5;
       this.bhTitle5 = bhTitle5;
       this.attendancePwd = attendancePwd;
       this.chkTerm = chkTerm;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="locationCode", column=@Column(name="LOCATION_CODE", nullable=false, length=3) ), 
        @AttributeOverride(name="setupDate", column=@Column(name="SETUP_DATE", nullable=false, length=7) ) } )
    public PerSetupId getId() {
        return this.id;
    }
    
    public void setId(PerSetupId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="LOCATION_CODE", nullable=false, insertable=false, updatable=false)
    public BudLocation getBudLocation() {
        return this.budLocation;
    }
    
    public void setBudLocation(BudLocation budLocation) {
        this.budLocation = budLocation;
    }

    
    @Column(name="PER_ORG_MAN", length=75)
    public String getPerOrgMan() {
        return this.perOrgMan;
    }
    
    public void setPerOrgMan(String perOrgMan) {
        this.perOrgMan = perOrgMan;
    }

    
    @Column(name="ATTENDANCE_FLG", nullable=false, precision=1, scale=0)
    public boolean isAttendanceFlg() {
        return this.attendanceFlg;
    }
    
    public void setAttendanceFlg(boolean attendanceFlg) {
        this.attendanceFlg = attendanceFlg;
    }

    
    @Column(name="HISTORY_FLG", nullable=false, precision=1, scale=0)
    public boolean isHistoryFlg() {
        return this.historyFlg;
    }
    
    public void setHistoryFlg(boolean historyFlg) {
        this.historyFlg = historyFlg;
    }

    
    @Column(name="PER_ORG_MAN_TITLE", length=100)
    public String getPerOrgManTitle() {
        return this.perOrgManTitle;
    }
    
    public void setPerOrgManTitle(String perOrgManTitle) {
        this.perOrgManTitle = perOrgManTitle;
    }

    
    @Column(name="SIGNATURE_1", length=75)
    public String getSignature1() {
        return this.signature1;
    }
    
    public void setSignature1(String signature1) {
        this.signature1 = signature1;
    }

    
    @Column(name="TITLE_1", length=50)
    public String getTitle1() {
        return this.title1;
    }
    
    public void setTitle1(String title1) {
        this.title1 = title1;
    }

    
    @Column(name="SIGNATURE_2", length=75)
    public String getSignature2() {
        return this.signature2;
    }
    
    public void setSignature2(String signature2) {
        this.signature2 = signature2;
    }

    
    @Column(name="TITLE_2", length=50)
    public String getTitle2() {
        return this.title2;
    }
    
    public void setTitle2(String title2) {
        this.title2 = title2;
    }

    
    @Column(name="SIGNATURE_3", length=75)
    public String getSignature3() {
        return this.signature3;
    }
    
    public void setSignature3(String signature3) {
        this.signature3 = signature3;
    }

    
    @Column(name="TITLE_3", length=50)
    public String getTitle3() {
        return this.title3;
    }
    
    public void setTitle3(String title3) {
        this.title3 = title3;
    }

    
    @Column(name="SIGNATURE_4", length=75)
    public String getSignature4() {
        return this.signature4;
    }
    
    public void setSignature4(String signature4) {
        this.signature4 = signature4;
    }

    
    @Column(name="TITLE_4", length=50)
    public String getTitle4() {
        return this.title4;
    }
    
    public void setTitle4(String title4) {
        this.title4 = title4;
    }

    
    @Column(name="SIGNATURE_5", length=75)
    public String getSignature5() {
        return this.signature5;
    }
    
    public void setSignature5(String signature5) {
        this.signature5 = signature5;
    }

    
    @Column(name="TITLE_5", length=50)
    public String getTitle5() {
        return this.title5;
    }
    
    public void setTitle5(String title5) {
        this.title5 = title5;
    }

    
    @Column(name="SIGNATURE_6", length=75)
    public String getSignature6() {
        return this.signature6;
    }
    
    public void setSignature6(String signature6) {
        this.signature6 = signature6;
    }

    
    @Column(name="TITLE_6", length=50)
    public String getTitle6() {
        return this.title6;
    }
    
    public void setTitle6(String title6) {
        this.title6 = title6;
    }

    
    @Column(name="NOTES", length=250)
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    
    @Column(name="BH_SIGNATURE_1", length=75)
    public String getBhSignature1() {
        return this.bhSignature1;
    }
    
    public void setBhSignature1(String bhSignature1) {
        this.bhSignature1 = bhSignature1;
    }

    
    @Column(name="BH_TITLE_1", length=50)
    public String getBhTitle1() {
        return this.bhTitle1;
    }
    
    public void setBhTitle1(String bhTitle1) {
        this.bhTitle1 = bhTitle1;
    }

    
    @Column(name="BH_SIGNATURE_2", length=75)
    public String getBhSignature2() {
        return this.bhSignature2;
    }
    
    public void setBhSignature2(String bhSignature2) {
        this.bhSignature2 = bhSignature2;
    }

    
    @Column(name="BH_TITLE_2", length=50)
    public String getBhTitle2() {
        return this.bhTitle2;
    }
    
    public void setBhTitle2(String bhTitle2) {
        this.bhTitle2 = bhTitle2;
    }

    
    @Column(name="BH_SIGNATURE_3", length=75)
    public String getBhSignature3() {
        return this.bhSignature3;
    }
    
    public void setBhSignature3(String bhSignature3) {
        this.bhSignature3 = bhSignature3;
    }

    
    @Column(name="BH_TITLE_3", length=50)
    public String getBhTitle3() {
        return this.bhTitle3;
    }
    
    public void setBhTitle3(String bhTitle3) {
        this.bhTitle3 = bhTitle3;
    }

    
    @Column(name="BH_NOTES", length=250)
    public String getBhNotes() {
        return this.bhNotes;
    }
    
    public void setBhNotes(String bhNotes) {
        this.bhNotes = bhNotes;
    }

    
    @Column(name="BH_GEHA_NAME", length=150)
    public String getBhGehaName() {
        return this.bhGehaName;
    }
    
    public void setBhGehaName(String bhGehaName) {
        this.bhGehaName = bhGehaName;
    }

    
    @Column(name="SIGNATURE_7", length=75)
    public String getSignature7() {
        return this.signature7;
    }
    
    public void setSignature7(String signature7) {
        this.signature7 = signature7;
    }

    
    @Column(name="TITLE_7", length=75)
    public String getTitle7() {
        return this.title7;
    }
    
    public void setTitle7(String title7) {
        this.title7 = title7;
    }

    
    @Column(name="BH_SIGNATURE_4", length=75)
    public String getBhSignature4() {
        return this.bhSignature4;
    }
    
    public void setBhSignature4(String bhSignature4) {
        this.bhSignature4 = bhSignature4;
    }

    
    @Column(name="BH_TITLE_4", length=50)
    public String getBhTitle4() {
        return this.bhTitle4;
    }
    
    public void setBhTitle4(String bhTitle4) {
        this.bhTitle4 = bhTitle4;
    }

    
    @Column(name="BH_SIGNATURE_5", length=75)
    public String getBhSignature5() {
        return this.bhSignature5;
    }
    
    public void setBhSignature5(String bhSignature5) {
        this.bhSignature5 = bhSignature5;
    }

    
    @Column(name="BH_TITLE_5", length=50)
    public String getBhTitle5() {
        return this.bhTitle5;
    }
    
    public void setBhTitle5(String bhTitle5) {
        this.bhTitle5 = bhTitle5;
    }

    
    @Column(name="ATTENDANCE_PWD", length=15)
    public String getAttendancePwd() {
        return this.attendancePwd;
    }
    
    public void setAttendancePwd(String attendancePwd) {
        this.attendancePwd = attendancePwd;
    }

    
    @Column(name="CHK_TERM", precision=1, scale=0)
    public Boolean getChkTerm() {
        return this.chkTerm;
    }
    
    public void setChkTerm(Boolean chkTerm) {
        this.chkTerm = chkTerm;
    }




}


