package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerSetupGeneral generated by hbm2java
 */
@Entity
@Table(name="PER_SETUP_GENERAL"
    ,schema="SHAMS"
)
public class PerSetupGeneral  implements java.io.Serializable {


     private Date setupDate;
     private boolean employeeNoFlg;
     private boolean jobCodeFlg;
     private Date minBirthDate;
     private boolean hireCodeFlg;
     private boolean locCodeFlg;
     private boolean orgCodeFlag;
     private boolean hireMenuFlg;
     private boolean religonCodeFlg;
     private boolean fiscalDegreeCodeFlg;
     private boolean generalCodeFlg;
     private boolean quilCodeFlg;
     private boolean groupCodeFlg;
     private boolean statusFlg;
     private boolean workTypeFlg;
     private boolean employeeDataFlg;
     private boolean salaryFlg;
     private String vacationPwd;
     private boolean mosqueFlg;
     private Boolean chkDegreePriorityDate;
     private boolean nationalFlg;
     private Byte evalPermission;
     private Boolean vacSalDate;
     private Boolean nameFlg;
     private boolean employeeLawFlg;
     private Boolean attendTransData;
     private String insPwd;
     private Byte nadbPeriod;
     private Boolean fiscalDegreeNameFlg;
     private Boolean empNameFlg;
     private Boolean webLogic;
     private Boolean state;
     private Boolean decArch;
     private String javaIpServer;
     private Short gehaCode;

    public PerSetupGeneral() {
    }

	
    public PerSetupGeneral(Date setupDate, boolean employeeNoFlg, boolean jobCodeFlg, Date minBirthDate, boolean hireCodeFlg, boolean locCodeFlg, boolean orgCodeFlag, boolean hireMenuFlg, boolean religonCodeFlg, boolean fiscalDegreeCodeFlg, boolean generalCodeFlg, boolean quilCodeFlg, boolean groupCodeFlg, boolean statusFlg, boolean workTypeFlg, boolean employeeDataFlg, boolean salaryFlg, String vacationPwd, boolean mosqueFlg, boolean nationalFlg, boolean employeeLawFlg, String insPwd) {
        this.setupDate = setupDate;
        this.employeeNoFlg = employeeNoFlg;
        this.jobCodeFlg = jobCodeFlg;
        this.minBirthDate = minBirthDate;
        this.hireCodeFlg = hireCodeFlg;
        this.locCodeFlg = locCodeFlg;
        this.orgCodeFlag = orgCodeFlag;
        this.hireMenuFlg = hireMenuFlg;
        this.religonCodeFlg = religonCodeFlg;
        this.fiscalDegreeCodeFlg = fiscalDegreeCodeFlg;
        this.generalCodeFlg = generalCodeFlg;
        this.quilCodeFlg = quilCodeFlg;
        this.groupCodeFlg = groupCodeFlg;
        this.statusFlg = statusFlg;
        this.workTypeFlg = workTypeFlg;
        this.employeeDataFlg = employeeDataFlg;
        this.salaryFlg = salaryFlg;
        this.vacationPwd = vacationPwd;
        this.mosqueFlg = mosqueFlg;
        this.nationalFlg = nationalFlg;
        this.employeeLawFlg = employeeLawFlg;
        this.insPwd = insPwd;
    }
    public PerSetupGeneral(Date setupDate, boolean employeeNoFlg, boolean jobCodeFlg, Date minBirthDate, boolean hireCodeFlg, boolean locCodeFlg, boolean orgCodeFlag, boolean hireMenuFlg, boolean religonCodeFlg, boolean fiscalDegreeCodeFlg, boolean generalCodeFlg, boolean quilCodeFlg, boolean groupCodeFlg, boolean statusFlg, boolean workTypeFlg, boolean employeeDataFlg, boolean salaryFlg, String vacationPwd, boolean mosqueFlg, Boolean chkDegreePriorityDate, boolean nationalFlg, Byte evalPermission, Boolean vacSalDate, Boolean nameFlg, boolean employeeLawFlg, Boolean attendTransData, String insPwd, Byte nadbPeriod, Boolean fiscalDegreeNameFlg, Boolean empNameFlg, Boolean webLogic, Boolean state, Boolean decArch, String javaIpServer, Short gehaCode) {
       this.setupDate = setupDate;
       this.employeeNoFlg = employeeNoFlg;
       this.jobCodeFlg = jobCodeFlg;
       this.minBirthDate = minBirthDate;
       this.hireCodeFlg = hireCodeFlg;
       this.locCodeFlg = locCodeFlg;
       this.orgCodeFlag = orgCodeFlag;
       this.hireMenuFlg = hireMenuFlg;
       this.religonCodeFlg = religonCodeFlg;
       this.fiscalDegreeCodeFlg = fiscalDegreeCodeFlg;
       this.generalCodeFlg = generalCodeFlg;
       this.quilCodeFlg = quilCodeFlg;
       this.groupCodeFlg = groupCodeFlg;
       this.statusFlg = statusFlg;
       this.workTypeFlg = workTypeFlg;
       this.employeeDataFlg = employeeDataFlg;
       this.salaryFlg = salaryFlg;
       this.vacationPwd = vacationPwd;
       this.mosqueFlg = mosqueFlg;
       this.chkDegreePriorityDate = chkDegreePriorityDate;
       this.nationalFlg = nationalFlg;
       this.evalPermission = evalPermission;
       this.vacSalDate = vacSalDate;
       this.nameFlg = nameFlg;
       this.employeeLawFlg = employeeLawFlg;
       this.attendTransData = attendTransData;
       this.insPwd = insPwd;
       this.nadbPeriod = nadbPeriod;
       this.fiscalDegreeNameFlg = fiscalDegreeNameFlg;
       this.empNameFlg = empNameFlg;
       this.webLogic = webLogic;
       this.state = state;
       this.decArch = decArch;
       this.javaIpServer = javaIpServer;
       this.gehaCode = gehaCode;
    }
   
     @Id 

    @Temporal(TemporalType.DATE)
    @Column(name="SETUP_DATE", unique=true, nullable=false, length=7)
    public Date getSetupDate() {
        return this.setupDate;
    }
    
    public void setSetupDate(Date setupDate) {
        this.setupDate = setupDate;
    }

    
    @Column(name="EMPLOYEE_NO_FLG", nullable=false, precision=1, scale=0)
    public boolean isEmployeeNoFlg() {
        return this.employeeNoFlg;
    }
    
    public void setEmployeeNoFlg(boolean employeeNoFlg) {
        this.employeeNoFlg = employeeNoFlg;
    }

    
    @Column(name="JOB_CODE_FLG", nullable=false, precision=1, scale=0)
    public boolean isJobCodeFlg() {
        return this.jobCodeFlg;
    }
    
    public void setJobCodeFlg(boolean jobCodeFlg) {
        this.jobCodeFlg = jobCodeFlg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MIN_BIRTH_DATE", nullable=false, length=7)
    public Date getMinBirthDate() {
        return this.minBirthDate;
    }
    
    public void setMinBirthDate(Date minBirthDate) {
        this.minBirthDate = minBirthDate;
    }

    
    @Column(name="HIRE_CODE_FLG", nullable=false, precision=1, scale=0)
    public boolean isHireCodeFlg() {
        return this.hireCodeFlg;
    }
    
    public void setHireCodeFlg(boolean hireCodeFlg) {
        this.hireCodeFlg = hireCodeFlg;
    }

    
    @Column(name="LOC_CODE_FLG", nullable=false, precision=1, scale=0)
    public boolean isLocCodeFlg() {
        return this.locCodeFlg;
    }
    
    public void setLocCodeFlg(boolean locCodeFlg) {
        this.locCodeFlg = locCodeFlg;
    }

    
    @Column(name="ORG_CODE_FLAG", nullable=false, precision=1, scale=0)
    public boolean isOrgCodeFlag() {
        return this.orgCodeFlag;
    }
    
    public void setOrgCodeFlag(boolean orgCodeFlag) {
        this.orgCodeFlag = orgCodeFlag;
    }

    
    @Column(name="HIRE_MENU_FLG", nullable=false, precision=1, scale=0)
    public boolean isHireMenuFlg() {
        return this.hireMenuFlg;
    }
    
    public void setHireMenuFlg(boolean hireMenuFlg) {
        this.hireMenuFlg = hireMenuFlg;
    }

    
    @Column(name="RELIGON_CODE_FLG", nullable=false, precision=1, scale=0)
    public boolean isReligonCodeFlg() {
        return this.religonCodeFlg;
    }
    
    public void setReligonCodeFlg(boolean religonCodeFlg) {
        this.religonCodeFlg = religonCodeFlg;
    }

    
    @Column(name="FISCAL_DEGREE_CODE_FLG", nullable=false, precision=1, scale=0)
    public boolean isFiscalDegreeCodeFlg() {
        return this.fiscalDegreeCodeFlg;
    }
    
    public void setFiscalDegreeCodeFlg(boolean fiscalDegreeCodeFlg) {
        this.fiscalDegreeCodeFlg = fiscalDegreeCodeFlg;
    }

    
    @Column(name="GENERAL_CODE_FLG", nullable=false, precision=1, scale=0)
    public boolean isGeneralCodeFlg() {
        return this.generalCodeFlg;
    }
    
    public void setGeneralCodeFlg(boolean generalCodeFlg) {
        this.generalCodeFlg = generalCodeFlg;
    }

    
    @Column(name="QUIL_CODE_FLG", nullable=false, precision=1, scale=0)
    public boolean isQuilCodeFlg() {
        return this.quilCodeFlg;
    }
    
    public void setQuilCodeFlg(boolean quilCodeFlg) {
        this.quilCodeFlg = quilCodeFlg;
    }

    
    @Column(name="GROUP_CODE_FLG", nullable=false, precision=1, scale=0)
    public boolean isGroupCodeFlg() {
        return this.groupCodeFlg;
    }
    
    public void setGroupCodeFlg(boolean groupCodeFlg) {
        this.groupCodeFlg = groupCodeFlg;
    }

    
    @Column(name="STATUS_FLG", nullable=false, precision=1, scale=0)
    public boolean isStatusFlg() {
        return this.statusFlg;
    }
    
    public void setStatusFlg(boolean statusFlg) {
        this.statusFlg = statusFlg;
    }

    
    @Column(name="WORK_TYPE_FLG", nullable=false, precision=1, scale=0)
    public boolean isWorkTypeFlg() {
        return this.workTypeFlg;
    }
    
    public void setWorkTypeFlg(boolean workTypeFlg) {
        this.workTypeFlg = workTypeFlg;
    }

    
    @Column(name="EMPLOYEE_DATA_FLG", nullable=false, precision=1, scale=0)
    public boolean isEmployeeDataFlg() {
        return this.employeeDataFlg;
    }
    
    public void setEmployeeDataFlg(boolean employeeDataFlg) {
        this.employeeDataFlg = employeeDataFlg;
    }

    
    @Column(name="SALARY_FLG", nullable=false, precision=1, scale=0)
    public boolean isSalaryFlg() {
        return this.salaryFlg;
    }
    
    public void setSalaryFlg(boolean salaryFlg) {
        this.salaryFlg = salaryFlg;
    }

    
    @Column(name="VACATION_PWD", nullable=false, length=20)
    public String getVacationPwd() {
        return this.vacationPwd;
    }
    
    public void setVacationPwd(String vacationPwd) {
        this.vacationPwd = vacationPwd;
    }

    
    @Column(name="MOSQUE_FLG", nullable=false, precision=1, scale=0)
    public boolean isMosqueFlg() {
        return this.mosqueFlg;
    }
    
    public void setMosqueFlg(boolean mosqueFlg) {
        this.mosqueFlg = mosqueFlg;
    }

    
    @Column(name="CHK_DEGREE_PRIORITY_DATE", precision=1, scale=0)
    public Boolean getChkDegreePriorityDate() {
        return this.chkDegreePriorityDate;
    }
    
    public void setChkDegreePriorityDate(Boolean chkDegreePriorityDate) {
        this.chkDegreePriorityDate = chkDegreePriorityDate;
    }

    
    @Column(name="NATIONAL_FLG", nullable=false, precision=1, scale=0)
    public boolean isNationalFlg() {
        return this.nationalFlg;
    }
    
    public void setNationalFlg(boolean nationalFlg) {
        this.nationalFlg = nationalFlg;
    }

    
    @Column(name="EVAL_PERMISSION", precision=2, scale=0)
    public Byte getEvalPermission() {
        return this.evalPermission;
    }
    
    public void setEvalPermission(Byte evalPermission) {
        this.evalPermission = evalPermission;
    }

    
    @Column(name="VAC_SAL_DATE", precision=1, scale=0)
    public Boolean getVacSalDate() {
        return this.vacSalDate;
    }
    
    public void setVacSalDate(Boolean vacSalDate) {
        this.vacSalDate = vacSalDate;
    }

    
    @Column(name="NAME_FLG", precision=1, scale=0)
    public Boolean getNameFlg() {
        return this.nameFlg;
    }
    
    public void setNameFlg(Boolean nameFlg) {
        this.nameFlg = nameFlg;
    }

    
    @Column(name="EMPLOYEE_LAW_FLG", nullable=false, precision=1, scale=0)
    public boolean isEmployeeLawFlg() {
        return this.employeeLawFlg;
    }
    
    public void setEmployeeLawFlg(boolean employeeLawFlg) {
        this.employeeLawFlg = employeeLawFlg;
    }

    
    @Column(name="ATTEND_TRANS_DATA", precision=1, scale=0)
    public Boolean getAttendTransData() {
        return this.attendTransData;
    }
    
    public void setAttendTransData(Boolean attendTransData) {
        this.attendTransData = attendTransData;
    }

    
    @Column(name="INS_PWD", nullable=false, length=20)
    public String getInsPwd() {
        return this.insPwd;
    }
    
    public void setInsPwd(String insPwd) {
        this.insPwd = insPwd;
    }

    
    @Column(name="NADB_PERIOD", precision=2, scale=0)
    public Byte getNadbPeriod() {
        return this.nadbPeriod;
    }
    
    public void setNadbPeriod(Byte nadbPeriod) {
        this.nadbPeriod = nadbPeriod;
    }

    
    @Column(name="FISCAL_DEGREE_NAME_FLG", precision=1, scale=0)
    public Boolean getFiscalDegreeNameFlg() {
        return this.fiscalDegreeNameFlg;
    }
    
    public void setFiscalDegreeNameFlg(Boolean fiscalDegreeNameFlg) {
        this.fiscalDegreeNameFlg = fiscalDegreeNameFlg;
    }

    
    @Column(name="EMP_NAME_FLG", precision=1, scale=0)
    public Boolean getEmpNameFlg() {
        return this.empNameFlg;
    }
    
    public void setEmpNameFlg(Boolean empNameFlg) {
        this.empNameFlg = empNameFlg;
    }

    
    @Column(name="WEB_LOGIC", precision=1, scale=0)
    public Boolean getWebLogic() {
        return this.webLogic;
    }
    
    public void setWebLogic(Boolean webLogic) {
        this.webLogic = webLogic;
    }

    
    @Column(name="STATE", precision=1, scale=0)
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }

    
    @Column(name="DEC_ARCH", precision=1, scale=0)
    public Boolean getDecArch() {
        return this.decArch;
    }
    
    public void setDecArch(Boolean decArch) {
        this.decArch = decArch;
    }

    
    @Column(name="JAVA_IP_SERVER", length=30)
    public String getJavaIpServer() {
        return this.javaIpServer;
    }
    
    public void setJavaIpServer(String javaIpServer) {
        this.javaIpServer = javaIpServer;
    }

    
    @Column(name="GEHA_CODE", precision=4, scale=0)
    public Short getGehaCode() {
        return this.gehaCode;
    }
    
    public void setGehaCode(Short gehaCode) {
        this.gehaCode = gehaCode;
    }




}


