package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerSpecialistCode generated by hbm2java
 */
@Entity
@Table(name="PER_SPECIALIST_CODE"
    ,schema="SHAMS"
)
public class PerSpecialistCode  implements java.io.Serializable {


     private String specialistCode;
     private String specialistName;
     private Date recordUpdateDate;
     private String recordUpdateUser;
     private Date recordCreateDate;
     private String recordCreateUser;
     private Set<PerEmploymentMasters> perEmploymentMastersesForSpecialistCodeBegin = new HashSet<PerEmploymentMasters>(0);
     private Set<PerEmploymentMasters> perEmploymentMastersesForSpecialistCodeFirst = new HashSet<PerEmploymentMasters>(0);
     private Set<PerEmpQualification> perEmpQualifications = new HashSet<PerEmpQualification>(0);
     private Set<PerQualSpecialist> perQualSpecialists = new HashSet<PerQualSpecialist>(0);
     private Set<PerEmploymentMasters> perEmploymentMastersesForSpecialistCode = new HashSet<PerEmploymentMasters>(0);
     private Set<PerJobDetail> perJobDetails = new HashSet<PerJobDetail>(0);

    public PerSpecialistCode() {
    }

	
    public PerSpecialistCode(String specialistCode, String specialistName) {
        this.specialistCode = specialistCode;
        this.specialistName = specialistName;
    }
    public PerSpecialistCode(String specialistCode, String specialistName, Date recordUpdateDate, String recordUpdateUser, Date recordCreateDate, String recordCreateUser, Set<PerEmploymentMasters> perEmploymentMastersesForSpecialistCodeBegin, Set<PerEmploymentMasters> perEmploymentMastersesForSpecialistCodeFirst, Set<PerEmpQualification> perEmpQualifications, Set<PerQualSpecialist> perQualSpecialists, Set<PerEmploymentMasters> perEmploymentMastersesForSpecialistCode, Set<PerJobDetail> perJobDetails) {
       this.specialistCode = specialistCode;
       this.specialistName = specialistName;
       this.recordUpdateDate = recordUpdateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordCreateUser = recordCreateUser;
       this.perEmploymentMastersesForSpecialistCodeBegin = perEmploymentMastersesForSpecialistCodeBegin;
       this.perEmploymentMastersesForSpecialistCodeFirst = perEmploymentMastersesForSpecialistCodeFirst;
       this.perEmpQualifications = perEmpQualifications;
       this.perQualSpecialists = perQualSpecialists;
       this.perEmploymentMastersesForSpecialistCode = perEmploymentMastersesForSpecialistCode;
       this.perJobDetails = perJobDetails;
    }
   
     @Id 

    
    @Column(name="SPECIALIST_CODE", unique=true, nullable=false, length=5)
    public String getSpecialistCode() {
        return this.specialistCode;
    }
    
    public void setSpecialistCode(String specialistCode) {
        this.specialistCode = specialistCode;
    }

    
    @Column(name="SPECIALIST_NAME", nullable=false, length=50)
    public String getSpecialistName() {
        return this.specialistName;
    }
    
    public void setSpecialistName(String specialistName) {
        this.specialistName = specialistName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perSpecialistCodeBySpecialistCodeBegin")
    public Set<PerEmploymentMasters> getPerEmploymentMastersesForSpecialistCodeBegin() {
        return this.perEmploymentMastersesForSpecialistCodeBegin;
    }
    
    public void setPerEmploymentMastersesForSpecialistCodeBegin(Set<PerEmploymentMasters> perEmploymentMastersesForSpecialistCodeBegin) {
        this.perEmploymentMastersesForSpecialistCodeBegin = perEmploymentMastersesForSpecialistCodeBegin;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perSpecialistCodeBySpecialistCodeFirst")
    public Set<PerEmploymentMasters> getPerEmploymentMastersesForSpecialistCodeFirst() {
        return this.perEmploymentMastersesForSpecialistCodeFirst;
    }
    
    public void setPerEmploymentMastersesForSpecialistCodeFirst(Set<PerEmploymentMasters> perEmploymentMastersesForSpecialistCodeFirst) {
        this.perEmploymentMastersesForSpecialistCodeFirst = perEmploymentMastersesForSpecialistCodeFirst;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perSpecialistCode")
    public Set<PerEmpQualification> getPerEmpQualifications() {
        return this.perEmpQualifications;
    }
    
    public void setPerEmpQualifications(Set<PerEmpQualification> perEmpQualifications) {
        this.perEmpQualifications = perEmpQualifications;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perSpecialistCode")
    public Set<PerQualSpecialist> getPerQualSpecialists() {
        return this.perQualSpecialists;
    }
    
    public void setPerQualSpecialists(Set<PerQualSpecialist> perQualSpecialists) {
        this.perQualSpecialists = perQualSpecialists;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perSpecialistCodeBySpecialistCode")
    public Set<PerEmploymentMasters> getPerEmploymentMastersesForSpecialistCode() {
        return this.perEmploymentMastersesForSpecialistCode;
    }
    
    public void setPerEmploymentMastersesForSpecialistCode(Set<PerEmploymentMasters> perEmploymentMastersesForSpecialistCode) {
        this.perEmploymentMastersesForSpecialistCode = perEmploymentMastersesForSpecialistCode;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perSpecialistCode")
    public Set<PerJobDetail> getPerJobDetails() {
        return this.perJobDetails;
    }
    
    public void setPerJobDetails(Set<PerJobDetail> perJobDetails) {
        this.perJobDetails = perJobDetails;
    }




}


