package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PerUsers generated by hbm2java
 */
@Entity
@Table(name="PER_USERS"
    ,schema="SHAMS"
)
public class PerUsers  implements java.io.Serializable {


     private String employeeId;
     private PerEmploymentMasters perEmploymentMasters;
     private String employeeNo;
     private String userPwd;
     private Boolean onStatus;

    public PerUsers() {
    }

	
    public PerUsers(PerEmploymentMasters perEmploymentMasters, String employeeNo, String userPwd) {
        this.perEmploymentMasters = perEmploymentMasters;
        this.employeeNo = employeeNo;
        this.userPwd = userPwd;
    }
    public PerUsers(PerEmploymentMasters perEmploymentMasters, String employeeNo, String userPwd, Boolean onStatus) {
       this.perEmploymentMasters = perEmploymentMasters;
       this.employeeNo = employeeNo;
       this.userPwd = userPwd;
       this.onStatus = onStatus;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="perEmploymentMasters"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="EMPLOYEE_ID", unique=true, nullable=false, length=10)
    public String getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

@OneToOne(fetch=FetchType.EAGER)@PrimaryKeyJoinColumn
    public PerEmploymentMasters getPerEmploymentMasters() {
        return this.perEmploymentMasters;
    }
    
    public void setPerEmploymentMasters(PerEmploymentMasters perEmploymentMasters) {
        this.perEmploymentMasters = perEmploymentMasters;
    }

    
    @Column(name="EMPLOYEE_NO", nullable=false, length=10)
    public String getEmployeeNo() {
        return this.employeeNo;
    }
    
    public void setEmployeeNo(String employeeNo) {
        this.employeeNo = employeeNo;
    }

    
    @Column(name="USER_PWD", nullable=false, length=15)
    public String getUserPwd() {
        return this.userPwd;
    }
    
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd;
    }

    
    @Column(name="ON_STATUS", precision=1, scale=0)
    public Boolean getOnStatus() {
        return this.onStatus;
    }
    
    public void setOnStatus(Boolean onStatus) {
        this.onStatus = onStatus;
    }




}


