package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PerVacationRuleDoc generated by hbm2java
 */
@Entity
@Table(name="PER_VACATION_RULE_DOC"
    ,schema="SHAMS"
)
public class PerVacationRuleDoc  implements java.io.Serializable {


     private PerVacationRuleDocId id;
     private PerVacationCode perVacationCode;
     private PerVacDocCode perVacDocCode;
     private String remarks;

    public PerVacationRuleDoc() {
    }

	
    public PerVacationRuleDoc(PerVacationRuleDocId id, PerVacationCode perVacationCode, PerVacDocCode perVacDocCode) {
        this.id = id;
        this.perVacationCode = perVacationCode;
        this.perVacDocCode = perVacDocCode;
    }
    public PerVacationRuleDoc(PerVacationRuleDocId id, PerVacationCode perVacationCode, PerVacDocCode perVacDocCode, String remarks) {
       this.id = id;
       this.perVacationCode = perVacationCode;
       this.perVacDocCode = perVacDocCode;
       this.remarks = remarks;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="vacationCode", column=@Column(name="VACATION_CODE", nullable=false, length=2) ), 
        @AttributeOverride(name="vacDocCode", column=@Column(name="VAC_DOC_CODE", nullable=false, length=3) ) } )
    public PerVacationRuleDocId getId() {
        return this.id;
    }
    
    public void setId(PerVacationRuleDocId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VACATION_CODE", nullable=false, insertable=false, updatable=false)
    public PerVacationCode getPerVacationCode() {
        return this.perVacationCode;
    }
    
    public void setPerVacationCode(PerVacationCode perVacationCode) {
        this.perVacationCode = perVacationCode;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="VAC_DOC_CODE", nullable=false, insertable=false, updatable=false)
    public PerVacDocCode getPerVacDocCode() {
        return this.perVacDocCode;
    }
    
    public void setPerVacDocCode(PerVacDocCode perVacDocCode) {
        this.perVacDocCode = perVacDocCode;
    }

    
    @Column(name="REMARKS", length=100)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


