package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Mar 9, 2021 2:52:01 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerVacationCode generated by hbm2java
 */
@Entity
@Table(name="PER_VACATION_CODE"
    ,schema="SHAMS"
)
public class PerVacationCode  implements java.io.Serializable {


     private String vacationCode;
     private PerGeneralCode perGeneralCode;
     private String vacationName;
     private String vacationType;
     private Boolean vacationPost;
     private String recordCreateUser;
     private Date recordCreateDate;
     private String recordUpdateUser;
     private Date recordUpdateDate;
     private Set<PerEmpVacationReqJava> perEmpVacationReqJavas = new HashSet<PerEmpVacationReqJava>(0);
     private Set<PerElawaVacationRule> perElawaVacationRules = new HashSet<PerElawaVacationRule>(0);
     private Set<PerPromotionVacationRuleN> perPromotionVacationRuleNs = new HashSet<PerPromotionVacationRuleN>(0);
     private Set<PerVacationRuleDoc> perVacationRuleDocs = new HashSet<PerVacationRuleDoc>(0);
     private Set<PerVacationRuleEmp> perVacationRuleEmps = new HashSet<PerVacationRuleEmp>(0);
     private Set<PerEmpVacationBalance> perEmpVacationBalances = new HashSet<PerEmpVacationBalance>(0);
     private Set<PerEmpVacationTrans> perEmpVacationTranses = new HashSet<PerEmpVacationTrans>(0);

    public PerVacationCode() {
    }

	
    public PerVacationCode(String vacationCode, String vacationName, String vacationType) {
        this.vacationCode = vacationCode;
        this.vacationName = vacationName;
        this.vacationType = vacationType;
    }
    public PerVacationCode(String vacationCode, PerGeneralCode perGeneralCode, String vacationName, String vacationType, Boolean vacationPost, String recordCreateUser, Date recordCreateDate, String recordUpdateUser, Date recordUpdateDate, Set<PerEmpVacationReqJava> perEmpVacationReqJavas, Set<PerElawaVacationRule> perElawaVacationRules, Set<PerPromotionVacationRuleN> perPromotionVacationRuleNs, Set<PerVacationRuleDoc> perVacationRuleDocs, Set<PerVacationRuleEmp> perVacationRuleEmps, Set<PerEmpVacationBalance> perEmpVacationBalances, Set<PerEmpVacationTrans> perEmpVacationTranses) {
       this.vacationCode = vacationCode;
       this.perGeneralCode = perGeneralCode;
       this.vacationName = vacationName;
       this.vacationType = vacationType;
       this.vacationPost = vacationPost;
       this.recordCreateUser = recordCreateUser;
       this.recordCreateDate = recordCreateDate;
       this.recordUpdateUser = recordUpdateUser;
       this.recordUpdateDate = recordUpdateDate;
       this.perEmpVacationReqJavas = perEmpVacationReqJavas;
       this.perElawaVacationRules = perElawaVacationRules;
       this.perPromotionVacationRuleNs = perPromotionVacationRuleNs;
       this.perVacationRuleDocs = perVacationRuleDocs;
       this.perVacationRuleEmps = perVacationRuleEmps;
       this.perEmpVacationBalances = perEmpVacationBalances;
       this.perEmpVacationTranses = perEmpVacationTranses;
    }
   
     @Id 

    
    @Column(name="VACATION_CODE", unique=true, nullable=false, length=2)
    public String getVacationCode() {
        return this.vacationCode;
    }
    
    public void setVacationCode(String vacationCode) {
        this.vacationCode = vacationCode;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="GENERAL_CODE")
    public PerGeneralCode getPerGeneralCode() {
        return this.perGeneralCode;
    }
    
    public void setPerGeneralCode(PerGeneralCode perGeneralCode) {
        this.perGeneralCode = perGeneralCode;
    }

    
    @Column(name="VACATION_NAME", nullable=false, length=50)
    public String getVacationName() {
        return this.vacationName;
    }
    
    public void setVacationName(String vacationName) {
        this.vacationName = vacationName;
    }

    
    @Column(name="VACATION_TYPE", nullable=false, length=1)
    public String getVacationType() {
        return this.vacationType;
    }
    
    public void setVacationType(String vacationType) {
        this.vacationType = vacationType;
    }

    
    @Column(name="VACATION_POST", precision=1, scale=0)
    public Boolean getVacationPost() {
        return this.vacationPost;
    }
    
    public void setVacationPost(Boolean vacationPost) {
        this.vacationPost = vacationPost;
    }

    
    @Column(name="RECORD_CREATE_USER", length=15)
    public String getRecordCreateUser() {
        return this.recordCreateUser;
    }
    
    public void setRecordCreateUser(String recordCreateUser) {
        this.recordCreateUser = recordCreateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_CREATE_DATE", length=7)
    public Date getRecordCreateDate() {
        return this.recordCreateDate;
    }
    
    public void setRecordCreateDate(Date recordCreateDate) {
        this.recordCreateDate = recordCreateDate;
    }

    
    @Column(name="RECORD_UPDATE_USER", length=15)
    public String getRecordUpdateUser() {
        return this.recordUpdateUser;
    }
    
    public void setRecordUpdateUser(String recordUpdateUser) {
        this.recordUpdateUser = recordUpdateUser;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="RECORD_UPDATE_DATE", length=7)
    public Date getRecordUpdateDate() {
        return this.recordUpdateDate;
    }
    
    public void setRecordUpdateDate(Date recordUpdateDate) {
        this.recordUpdateDate = recordUpdateDate;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perVacationCode")
    public Set<PerEmpVacationReqJava> getPerEmpVacationReqJavas() {
        return this.perEmpVacationReqJavas;
    }
    
    public void setPerEmpVacationReqJavas(Set<PerEmpVacationReqJava> perEmpVacationReqJavas) {
        this.perEmpVacationReqJavas = perEmpVacationReqJavas;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perVacationCode")
    public Set<PerElawaVacationRule> getPerElawaVacationRules() {
        return this.perElawaVacationRules;
    }
    
    public void setPerElawaVacationRules(Set<PerElawaVacationRule> perElawaVacationRules) {
        this.perElawaVacationRules = perElawaVacationRules;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perVacationCode")
    public Set<PerPromotionVacationRuleN> getPerPromotionVacationRuleNs() {
        return this.perPromotionVacationRuleNs;
    }
    
    public void setPerPromotionVacationRuleNs(Set<PerPromotionVacationRuleN> perPromotionVacationRuleNs) {
        this.perPromotionVacationRuleNs = perPromotionVacationRuleNs;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perVacationCode")
    public Set<PerVacationRuleDoc> getPerVacationRuleDocs() {
        return this.perVacationRuleDocs;
    }
    
    public void setPerVacationRuleDocs(Set<PerVacationRuleDoc> perVacationRuleDocs) {
        this.perVacationRuleDocs = perVacationRuleDocs;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perVacationCode")
    public Set<PerVacationRuleEmp> getPerVacationRuleEmps() {
        return this.perVacationRuleEmps;
    }
    
    public void setPerVacationRuleEmps(Set<PerVacationRuleEmp> perVacationRuleEmps) {
        this.perVacationRuleEmps = perVacationRuleEmps;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perVacationCode")
    public Set<PerEmpVacationBalance> getPerEmpVacationBalances() {
        return this.perEmpVacationBalances;
    }
    
    public void setPerEmpVacationBalances(Set<PerEmpVacationBalance> perEmpVacationBalances) {
        this.perEmpVacationBalances = perEmpVacationBalances;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="perVacationCode")
    public Set<PerEmpVacationTrans> getPerEmpVacationTranses() {
        return this.perEmpVacationTranses;
    }
    
    public void setPerEmpVacationTranses(Set<PerEmpVacationTrans> perEmpVacationTranses) {
        this.perEmpVacationTranses = perEmpVacationTranses;
    }




}


