package com.ahramattend.www._0_0_0_2_0_DB_Entities;
// Generated Feb 23, 2021 6:24:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerVacationTemp generated by hbm2java
 */
@Entity
@Table(name="PER_VACATION_TEMP"
    ,schema="SHAMS"
)
public class PerVacationTemp  implements java.io.Serializable {


     private String serial;
     private Date vacDate;

    public PerVacationTemp() {
    }

    public PerVacationTemp(String serial, Date vacDate) {
       this.serial = serial;
       this.vacDate = vacDate;
    }
   
     @Id 

    
    @Column(name="SERIAL", unique=true, nullable=false, length=5)
    public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VAC_DATE", nullable=false, length=7)
    public Date getVacDate() {
        return this.vacDate;
    }
    
    public void setVacDate(Date vacDate) {
        this.vacDate = vacDate;
    }




}


